### ISSUE TITLE
jx diagnose can't handle windows git version 

### ISSUE THREAD

**Issue by survivant** [jenkins-x/jx#6880] opened 2020-03-06 18:44 UTC
### Summary 
I'm trying to find what going on with my jx setup on minikube (Windows), but when I enter the command : `jx diagnose`

jx is not able to parse the git server version

### Steps to reproduce the behavior

jx diagnose

### Expected behavior

should be able to handle alphanumeric version

### Actual behavior

parsing error

```
PS C:\temp> jx diagnose                                                                                                 Running in namespace: jx
ERROR: Unable to get the Jenkins X Version
error: Command failed 'jx version --no-version-check': NAME               VERSION
jx                 2.0.1232
jenkins x platform 2.0.2052
Kubernetes cluster v1.17.3
kubectl            v1.17.3
helm client        2.16.1
git                2.25.1.windows.1
Operating System   Windows 10 Enterprise 1909 build 18363


verifying packages
error: [failed to parse semantic version for current version 2.25.1.windows.1 for package git: Invalid character(s) found in patch number "1.windows.1", package kubectl is using version 1.17.3 which is too new. The version stream requires a version earlier than 1.17.0] exit status 1

```
### Jx version

The output of `jx version` is:

```
PS C:\temp> jx version                                                                                                  NAME               VERSION
jx                 2.0.1232
jenkins x platform 2.0.2052
Kubernetes cluster v1.17.3
kubectl            v1.17.3
helm client        2.16.1
git                2.25.1.windows.1
Operating System   Windows 10 Enterprise 1909 build 18363


verifying packages

WARNING: jx version 2.0.1233 is available in the version stream. You are using 2.0.1232. We highly recommend you upgrade to it.

? Would you like to upgrade to the jx version? [? for help] (Y/n)                                                                                                                                                                               
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ X] Classic Jenkins

### Kubernetes cluster

PS C:\temp> jx create cluster minikube --advanced-mode=true -c=3 -s=100GB -m=10000 -d=hyperv --default-admin-password=admin --git-provider-url=http://10.1.3.23:7990 --git-api-token=ODE1NzI2NTQ2MTQ3OgHa6/tUF5x2Qp70ON8VigJe2j3u --git-provider-kind=bitbucketserver --git-username=admin --static-jenkins --verbose                                                   

### Operating system / Environment

PS C:\temp> jx version                                                                                                  NAME               VERSION
jx                 2.0.1232
jenkins x platform 2.0.2052
Kubernetes cluster v1.17.3
kubectl            v1.17.3
helm client        2.16.1
git                2.25.1.windows.1
Operating System   Windows 10 Enterprise 1909 build 18363

**Comment by hervelemeur** [comment] 2020-03-09 11:06
Duplicate of https://github.com/jenkins-x/jx/issues/6825

**Comment by deanesmith** [comment] 2020-03-09 12:44
Closing -Already reported

**Closed by deanesmith** 2020-03-09 12:44 UTC
