### ISSUE TITLE
Jenkins X cluster on Azure doesn't survive scheduled shutdown

### ISSUE THREAD

**Issue by spennec** [jenkins-x/jx#770] opened 2018-05-07 19:22 UTC
Hello,

I've created successfully a Kubernetes cluster and Jenkins X installation on my Azure subscription. Since it's only a POC, my VMs are scheduled to shutdown every night at 7 pm.

After the creation, all seems to work fine: I can log onto Jenkins, see my project and the pipeline. After one shutdown, connecting to the console gives a 503 error, and at least one of the Kubernetes machines do not start anymore.

Nothing was touched on the machines, the only operation done after the installation is the creation of a spring demo project.

**Comment by jstrachan** [comment] 2018-05-08 10:45
Sorry to hear that.

I wonder what `kubectl get pod` lists? Are most pods up and running?

I was slightly confused - the console you refer to above - is that the Jenkins Console right? So it worked fine after one restart - but not after another?

I wonder if the IP address of your ingr as changes after a restart?

**Comment by spennec** [comment] 2018-05-08 11:38
Hi James,

Can't test kubectl right now, will tonight. Until then, some answers to your questions :) 

The console I refer is the one that is brought up when I type jx console. It worked fine until the first shutdown. 

So basically, the reproducer is:
jx create cluster aks
...
jx create spring -d web -d actuator
...
jx console

... let time pass, untill Azure automatically shutsdown the vms, and once I start them back up, the installation is broken.

**Comment by ccojocar** [comment] 2019-01-15 09:19
This issue seems to be rather caused by Azure/AKS than jx. I am going to close it for now. Please open another issue if you see the problem occurring again.

**Closed by ccojocar** 2019-01-15 09:19 UTC
