### ISSUE TITLE
jx promote command never returns

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#2318] opened 2018-11-23 13:55 UTC
### Summary 
When running jx promote command, it keeps the terminal busy and never returns even after the promotion has been done successfully.

### Steps to reproduce the behavior

1. Run `jx promote your-app --version x.x.x --env production`
2. Wait for the promotion to be done

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.583
jenkins x platform 0.0.2871
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.10.4
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)

### Kubernetes cluster

GKE

### Operating system / Environment
Mac OS 10.14 Mojave

### Expected behavior
Command line should returns the hand to the user

### Actual behavior
CLI keeps the terminal busy.
Last line displayed is:
Merge commit has not yet any statuses on repo your-org/environment-xxxxxx-production merge sha 07412f68abcdefghijdc938d756bea9a5d1d9d6e

**Comment by romainverduci** [comment] 2018-11-23 14:07
Imported as PLAT-350

**Comment by amuniz** [comment] 2018-12-11 09:33
Root cause is https://github.com/jenkins-x/jx/issues/2410 (which already has a workaround merged in master).

**Closed by amuniz** 2018-12-11 09:33 UTC
Labels: kubecd, kubecd-imported, kubecd-triaged
