### ISSUE TITLE
jx diagnose Unable to get the Jenkins X Status

### ISSUE THREAD

**Issue by msigler-cb** [jenkins-x/jx#2324] opened 2018-11-25 12:47 UTC
### Summary 

```jx diagnose``` error msg ```Unable to get the Jenkins X Status```

### Steps to reproduce the behavior

```
jx diagnose
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.591
jenkins x platform 0.0.2902
Kubernetes cluster v1.11.2-gke.18
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1
Operating System   Mac OS X 10.14.1 build 18B75
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

```
$ jx status
? Pick service to open:  jenkins-x-chartmuseum
Jenkins X checks passed for Cluster(jx-cluster): 3 nodes, memory 2% of 145611636Ki, cpu 13% of 23730m. Jenkins is running at https://chartmuseum.jx.cd.jenkins-x.io
```

### Operating system / Environment

Operating System   Mac OS X 10.14.1 build 18B75

### Actual behavior

```
$ jx diagnose
Running in namespace: jx
Jenkins X Version:
 NAME               VERSION
jx                 1.3.591
jenkins x platform 0.0.2902
Kubernetes cluster v1.11.2-gke.18
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1
Operating System   Mac OS X 10.14.1 build 18B75
Unable to get the Jenkins X Status
? Pick service to open:   [Use arrows to move, type to filter]
> jenkins-x-chartmuseum
  jenkins-x-docker-registry
  jenkins-x-mongodb
  jenkins-x-monocular-api
  jenkins-x-monocular-prerender
  jenkins-x-monocular-ui
Cluster(jx-cluster): 3 nodes, memory 2% of 145611636Ki, cpu 13% of 23730m Jenkins not found
error: EOF exit status 1
```

**Comment by ccojocar** [comment] 2019-01-16 09:41
I think it work fine with Jenkins. It's more an issue related to `prow/serverless` installation. 

```
jx diagnose
Running in namespace: jx

Jenkins X Version:
 NAME               VERSION
jx                 1.3.704-dev+5d884bf2
jenkins x platform 0.0.3143
Kubernetes cluster v1.10.9-gke.5
kubectl            v1.13.1
helm client        Client: v2.10.0-rc.1+gaa98e7e
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.2 build 18C54

Jenkins X Status:
 Jenkins X checks passed for Cluster(gke_jenkinsx-dev): 3 nodes, memory 14% of 17334268Ki, cpu 38% of 5790m. Jenkins is running at
```

I am going to close this issue. It seems to be a duplicate of #2343

**Closed by ccojocar** 2019-01-16 09:41 UTC
Labels: x-internal, x-triaged
