### ISSUE TITLE
jx install failure: Error executing 'postInstallation': Group '4294967294' not found

### ISSUE THREAD

**Issue by stevegszabo** [jenkins-x/jx#759] opened 2018-05-03 17:50 UTC
jx install fails, looks like mongo fails to start:

```
sszabo@tor976568e1 [/home/sszabo] $ kubectl -n jx get pods
NAME                                             READY     STATUS              RESTARTS   AGE
jenkins-6c69766b8d-wrz7m                         0/1       Running             2          6m
jenkins-x-chartmuseum-77dcdf7f87-fq6tm           1/1       Running             0          6m
jenkins-x-docker-registry-76dd6bddd4-rk864       1/1       Running             0          6m
jenkins-x-heapster-57b558bf9b-wv7cq              2/2       Running             0          6m
jenkins-x-mongodb-5fb7868bd-xmw8v                0/1       CrashLoopBackOff    5          6m
jenkins-x-monocular-api-5c7df778b4-j9b9k         0/1       CrashLoopBackOff    5          6m
jenkins-x-monocular-prerender-74f49ffdc7-lxml6   1/1       Running             0          6m
jenkins-x-monocular-ui-5bf75b547b-brhhr          1/1       Running             0          6m
jenkins-x-nexus-786fcdbd98-5ld7n                 0/1       ContainerCreating   0          6m
pipelinecontroller-5c5f5df7ff-qb98q              1/1       Running             0          6m

sszabo@tor976568e1 [/home/sszabo] $ kubectl -n jx logs jenkins-x-monocular-api-5c7df778b4-j9b9k
time="2018-05-03T17:45:43Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml" 
time="2018-05-03T17:45:43Z" level=info msg="Configuration file found!" 
time="2018-05-03T17:45:43Z" level=info msg="Loading CORS from config file" 
time="2018-05-03T17:45:43Z" level=info msg="Loading repositories from config file" 
time="2018-05-03T17:45:43Z" level=info msg="Configuration bootstrap finished" 
time="2018-05-03T17:45:54Z" level=fatal msg="unable to connect to MongoDB" host="jenkins-x-mongodb:27017" 

sszabo@tor976568e1 [/home/sszabo] $ kubectl -n jx logs jenkins-x-mongodb-5fb7868bd-xmw8v

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '4294967294' not found


```

**Comment by jstrachan** [comment] 2018-05-04 07:40
@stevegszabo does the mongodb pod ever recover or does it just keep restarting forever? I've never seen that error before.

Whats the output of `jx version` - and what kind of kubernetes cluster are you trying?

**Comment by stevegszabo** [comment] 2018-05-05 19:48
jx: 1.2.37
I'm using a k8s 1.8 cluster at IBM/SoftLayer

**Comment by arhe** [comment] 2018-05-28 14:07
Hello,
i'v the same error : 
`nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '2007' not found`

Have you find a solution please ?

**Comment by arhe** [comment] 2018-05-30 10:11
this bug is caused by bitnami image. move bitnami/mongodb:3.4.9-r1 to  bitnami/mongodb:3.6.5 and it will be OK.

**Comment by rvennam** [comment] 2018-06-11 19:22
I had the same issue and moving to bitnami/mongodb:3.6.5 fixed it.

**Comment by jstrachan** [comment] 2018-08-19 10:41
I've just upgraded to the latest chartmuseum, but that didn't look like it fixed it - its still using ` bitnami/mongodb:3.4.9-r1`

**Comment by jstrachan** [comment] 2018-08-19 11:13
just trying moving to the latest greatest monocular that uses a 4.x mongo image... https://github.com/jenkins-x/jenkins-x-platform/pull/3019

**Comment by wangyf2010** [comment] 2018-09-25 17:06
have jx 1.3.316 include the fix? I still have same problem.

**Comment by johnmcollier** [comment] 2018-10-10 18:38
Yeah, I'm also seeing this on one cluster with the latest JX versions.

**Comment by msteenhu** [comment] 2018-11-04 16:19
+1
Kubernetes 12.2. Newest jx...

**Comment by ccojocar** [comment] 2019-02-20 10:05
@stevegszabo I am going to close this issue. The mongodb seems to work in the current platform version. Please feel free to open another issue if you are still seeing the problem occurring. Thanks

**Closed by ccojocar** 2019-02-20 10:05 UTC
Labels: area/install, kind/bug, priority/important-soon
