### ISSUE TITLE
Latest Version: Failed to enrich commits with issues during ``jx step changelog``

### ISSUE THREAD

**Issue by beebird** [jenkins-x/jx#3731] opened 2019-04-24 15:18 UTC
### Summary 
I encountered the issue after I upgraded my jx platform to 2.0.6.
I can see that there're similar issues closed recently so I thought the problem has gone, while it seems not.

Is that because the builder image is outdated? The one I'm using in this job is ``gcr.io/jenkinsxio/builder-python2:0.1.419``

Can someone take a look? 

### Jx version

The output of `jx version` is:
```
jx                 2.0.6
jenkins x platform 2.0.106
Kubernetes cluster v1.13.1
kubectl            v1.14.0
helm client        v2.11.0+g2e55dbe
helm server        v2.12.2+g7d2b0c7
git                git version 2.21.0
Operating System   Mac OS X 10.14.4 build 18E226
```

```
+ jx step changelog --version vx.xx.xxx
Using batch mode as inside a pipeline
Converted /home/jenkins/workspace/xxxx/charts/xxx to an unshallow repository
Generating change log from git ref x.xx.xxx => xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
Finding issues in commit messages using git format
Associating user xxx in users.jenkins.io with email xxx@xxx.xx to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user xxx in users.jenkins.io
WARNING: Failed to enrich commits with issues: User.jenkins.io "xxx" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user xxx in users.jenkins.io with email xxx@xxx.xx to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user xxx in users.jenkins.io
WARNING: Failed to enrich commits with issues: User.jenkins.io "xxx" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
WARNING: Failed to enrich commits with issues: User.jenkins.io "" is invalid: metadata.name: Required value: name or generateName is required
Associating user xxx in users.jenkins.io with email xxx@xxx.xx to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user xxx in users.jenkins.io
WARNING: Failed to enrich commits with issues: User.jenkins.io "xxx" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user xxx in users.jenkins.io with email xxx@xxx.xx to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user xxx in users.jenkins.io```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [ ] Next Generation (Tekton + Prow)
- [- ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

<!--
custom installations of Kubernetes 
-->

### Operating system / Environment

<!--
macOS 10.14
-->

**Comment by anub1s187** [comment] 2019-06-05 08:35
I too am getting this message flooding the logs at the "jx step changelog" stage, any help on this?

**Comment by pmuir** [comment] 2019-06-24 16:35
Looks like dupe of #3818 so closing - please reopen if it isn't

**Closed by pmuir** 2019-06-24 16:35 UTC

**Comment by stepanselyuk** [comment] 2019-09-15 14:17
I got this while promoting to staging:
```
Using batch mode as inside a pipeline
Generating change log from git ref c532d44f406f82c07cb03616527f90c3c788e87b => 1367a65bb31f099a0a6f93c62574b6f32668a325
Associating user stepanselyuk in users.jenkins.io with email xxxxx@xxxxx.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user stepanselyuk in users.jenkins.io
WARNING: Failed to enrich commit dc65d5a6927014c830d851f614c8c8b0e7d7330f with issues: User.jenkins.io "stepanselyuk" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user stepanselyuk in users.jenkins.io with email stepan@selyuk.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user stepanselyuk in users.jenkins.io
WARNING: Failed to enrich commit dc65d5a6927014c830d851f614c8c8b0e7d7330f with issues: User.jenkins.io "stepanselyuk" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

If I check the user config, using `kubectl edit user stepanselyuk` I see this:
```
apiVersion: jenkins.io/v1
kind: User
metadata:
  creationTimestamp: "2019-09-14T18:58:23Z"
  generation: 2
  labels:
    jenkins.io/git-github-userid: stepanselyuk
  name: stepanselyuk
  namespace: jx
  resourceVersion: "1121600"
  selfLink: /apis/jenkins.io/v1/namespaces/jx/users/stepanselyuk
  uid: a05601da-d721-11e9-aad5-0293dc1354ba
spec:
  accountReference:
  - id: stepanselyuk
    provider: jenkins.io/git-github-userid
  email: xxxxx@xxxxx.com
  login: stepanselyuk
  name: Stepan Seliuk
user: {}
```

Also, I deleted the user `x-0`, no idea how it has been created. But there the name was "Stephan Seliuk", I believe somewhere in installation steps I put my corporative email, cause there such pronunciation (I did not check that user config before deleting).

**Comment by savealive** [comment] 2019-11-13 20:26
I've got the same issue. 
```
+ jx step changelog --version v0.0.0-dev-025eb77f-40 --update-release=false
Using batch mode as inside a pipeline
Generating change log from git ref b919a98ab5dbd7cdf95e26f1519f749e39a8024c => 9cbfbad40682fd5c4e0c6641f6158b19435d9e82
Associating user savealive in users.jenkins.io with email oleks.savchenko@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user savealive in users.jenkins.io
WARNING: Failed to enrich commit 025eb77f1993cf013894b444a7c826b66e3af493 with issues: User.jenkins.io "savealive" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user savealive in users.jenkins.io with email oleks.savchenko@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user savealive in users.jenkins.io
WARNING: Failed to enrich commit 025eb77f1993cf013894b444a7c826b66e3af493 with issues: User.jenkins.io "savealive" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
Associating user savealive in users.jenkins.io with email oleks.savchenko@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user savealive in users.jenkins.io```
jx version is latest.
