### ISSUE TITLE
jx install fails: expose job complains about unknown user

### ISSUE THREAD

**Issue by robertgartman** [jenkins-x/jx#1547] opened 2018-08-28 16:58 UTC
### Summary 
jx install fails with **Error: failed install perform step: job failed: BackoffLimitExceeded': exit status 1**
### Steps to reproduce the behavior
Fresh install of jx:
```
brew uninstall --force jx
rm -r ~/.jx/*
brew install jx

```
Fresh GKE cluster - just created
### Jx version

The output of `jx version` is:

```
1.3.191
```

### Kubernetes cluster

GKE
`gcloud container clusters create cluster-with-ip-alias --enable-ip-alias --create-subnetwork name=main-cluster-subnet --cluster-version=1.10.6-gke.2`

### Operating system / Environment
Mac OS: 10.13.6
### Expected behavior
Installed Jenkins X

### Actual behavior

Fails as below:
```
jx install --helm3  --provider=gke --recreate-existing-draft-repos --git-username THEGITREPO --git-api-token  ea03THETOKEN83a7
helm3 not found
<cut>
helm installed and configured
? No existing ingress controller found in the kube-system namespace, shall we install one? No
Lets set up a git username and API token to be able to perform CI/CD

? GitHub user name: THEGITREPO
To be able to create a repository on GitHub we need an API Token
Please click this URL https://github.com/settings/tokens/new?scopes=repo,read:user,read:org,user:email,write:repo_hook,delete_repo

Then COPY the token and enter in into the form below:

? API Token: ****************************************
Cloning the Jenkins X cloud environments repo to /Users/robert/.jx/cloud-environments
Counting objects: 849, done.
Compressing objects: 100% (12/12), done.
Total 849 (delta 7), reused 9 (delta 4), pack-reused 833
Generated helm values /Users/robert/.jx/extraValues.yaml
Installing Jenkins X platform helm chart from: /Users/robert/.jx/cloud-environments/env-gke
error: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm3 upgrade --namespace jx --install --timeout 6000 --version 0.0.2252 --values ./secrets.yaml --values /Users/robert/.jx/gitSecrets.yaml --values /Users/robert/.jx/adminSecrets.yaml --values /Users/robert/.jx/extraValues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '/Users/robert/.jx/cloud-environments/env-gke', output: 'Release "jenkins-x" does not exist. Installing it now.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/svc-primary-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/heapster/templates/heapster-crb.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-activities/templates/job.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/chartmuseum/templates/serviceaccount.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/templates/chartmuseum-link-service.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/statefulset-primary-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/chartmuseum/templates/ingress.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/cleanup/templates/configmap.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/statefulset-secondary-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-previews/templates/deployment.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-activities/templates/deployment.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/heapster/templates/serviceaccount.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-activities/templates/clusterrole.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-previews/templates/job.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/templates/nexus-link-service.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/poddisruptionbudget-secondary-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/configmap.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-activities/templates/daemonset.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/poddisruptionbudget-arbiter-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/heapster/templates/pod-nanny-role.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/templates/chartmuseum-link-secret.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/docker-registry/templates/ingress.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/jenkins/templates/jenkins-master-networkpolicy.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/statefulset-arbiter-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/chartmuseum/templates/pvc.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/jenkins/templates/jenkins-master-ingress.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-previews/templates/service.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-activities/templates/service.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/headless-svc-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-activities/templates/clusterrolebinding.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/templates/ingress.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/poddisruptionbudget-primary-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-previews/templates/daemonset.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/heapster/templates/pod-nanny-rolebinding.yaml" is empty. Skipping.
Error: failed install perform step: job failed: BackoffLimitExceeded': exit status 1
```

Checking GKE Dashboard, it turns out that `expose` is failing. The dashbord flags it with...
`Error with exit code 255`
... and the log of that job shows this error:
`"failed to create new strategy: failed to create ingress expose strategy: failed to get a domain: failed to find any nodes: nodes is forbidden: User "system:serviceaccount:jx:expose" cannot list nodes at the cluster scope: Unknown user "system:serviceaccount:jx:expose""  `

**Comment by robertgartman** [comment] 2018-08-28 17:50
Som more investigations on the issue. Found this report indication issues with helm:
https://github.com/jenkins-x/jx/issues/730#issuecomment-386503539

Tried (re)creating helm security roles based on this recommendation:
https://stackoverflow.com/a/46688254

Running:
`jx install --helm3  --provider=gke --recreate-existing-draft-repos` again results in a different error:

```
....
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-activities/templates/daemonset.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/chartmuseum/templates/ingress.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/templates/chartmuseum-link-secret.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/charts/mongodb/templates/poddisruptionbudget-arbiter-rs.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/heapster/templates/heapster-crb.yaml" is empty. Skipping.
Error: failed install perform step: release jenkins-x failed: clusterroles.rbac.authorization.k8s.io "gc-previews-jx" already exists': exit status 1
```

Might be something left in the cluster. Removing Jenkins:
```
jx uninstall                                                                                                                                                                          
? Are you sure you wish to remove the Jenkins X platform from the 'jx' namespace on cluster 'https://35.228.81.112'? : Yes
Removing installation of Jenkins X in team namespace jx
error: failed to purge the jenkins-x chart: failed to run 'helm delete --purge jenkins-x' command in directory '', output: 'Error: release: "jenkins-x" not found': exit status 1
```

Perhaps OK. Installation wasn't ready. Wiping the cluster on GKE and reinstalling with instructions below (output removed - all commands successful):

```
gcloud container clusters create cluster-with-ip-alias --enable-ip-alias --create-subnetwork name=main-cluster-subnet --cluster-version=1.10.6-gke.2
gcloud container clusters get-credentials cluster-with-ip-alias
helm init
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'      
helm init --service-account tiller --upgrade
```

Time for jx again:
`jx install --helm3  --provider=gke --recreate-existing-draft-repos`

And the result is
```
...
hooks.go:93: info: manifest "jenkins-x-platform/charts/gc-previews/templates/service.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/cleanup/templates/configmap.yaml" is empty. Skipping.
hooks.go:93: info: manifest "jenkins-x-platform/charts/monocular/templates/ingress.yaml" is empty. Skipping.
Error: failed install perform step: job failed: BackoffLimitExceeded': exit status 1
```

Still expose being grumpy about unknown user.

**Comment by ccojocar** [comment] 2019-01-15 13:37
The issue was caused by not having the correct RBAC role on `expose` service account. This issue should be fixed by now.

**Closed by ccojocar** 2019-01-15 13:37 UTC
