### ISSUE TITLE
bug: PipelineActivity is garbage collected

### ISSUE THREAD

**Issue by tomfrenken** [jenkins-x/jx#6683] opened 2020-02-03 09:07 UTC
### Summary 
I enabled cloud storage for my logs and if I look into the `gs` bucket, I can still see the logs in there.
However, when I use `jx get build logs` they don't appear in the list and they are also not listed in the `jx ui`.
Looking further into it, the `PipelineActivity` seems to be partially garbage collected, as I see when running `kubectl get act`:

```
tomfrenken-environment-jx-eval-01-dev-pr-1-1       https://github.com/tomfrenken/environment-jx-eval-01-dev.git       Succeeded
tomfrenken-environment-jx-eval-01-dev-pr-2-1       https://github.com/tomfrenken/environment-jx-eval-01-dev.git       Succeeded
tomfrenken-environment-jx-eval-01-staging-pr-1-1   https://github.com/tomfrenken/environment-jx-eval-01-staging.git   Succeeded
tomfrenken-environment-jx-eval-01-staging-pr-2-1   https://github.com/tomfrenken/environment-jx-eval-01-staging.git   Succeeded
tomfrenken-environment-jx-eval-01-staging-pr-3-1   https://github.com/tomfrenken/environment-jx-eval-01-staging.git   Succeeded
tomfrenken-environment-jx-eval-01-staging-pr-4-1   https://github.com/tomfrenken/environment-jx-eval-01-staging.git   Succeeded
```
as you can see, only logs from the `dev` and `staging` environment are left.

### Steps to reproduce the behavior
Enable cloud storage for `logs`.
Run a build.
Wait approx. 3 days and then run `jx get build logs`

### Jx version

The output of `jx version` is:

```
jx                 2.0.1177
Kubernetes cluster v1.13.11-gke.23
kubectl            v1.17.2
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.3 build 19D76
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

**Comment by abayer** [comment] 2020-02-04 06:51
So the PipelineActivity GC may be too aggressive out of the box. It can be tweaked, but yeah, in the end, the problem we have is that we use a single CRD for runtime and historic purposes, and that doesn’t work well, since you really don’t want to be having CRDs living a long time to solely be used as build history as we do currently. It’s a problem area we need to rework significantly.

**Comment by abayer** [comment] 2020-02-09 08:29
I'm closing this, since it's not a bug, it's just annoying.

**Closed by abayer** 2020-02-09 08:29 UTC
