### ISSUE TITLE
Edit buildpack not working server could not find the requested resource (get buildpacks.jenkins.io)

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jx#2483] opened 2018-12-11 16:43 UTC
### Summary 
I have upgraded my jx-platform and now the buildpacks from the old git repo migrated to new. And i when i am trying to use the old repo by `jx edit buildpack` i am getting the following error

### Jx version

The output of `jx version` is:

```
ubuntu@ip-172-30-1-79:~$ jx get buildpack
 https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git master
ubuntu@ip-172-30-1-79:~$ jx edit buildpack
error: the server could not find the requested resource (get buildpacks.jenkins.io)
ubuntu@ip-172-30-1-79:~$ jx version
NAME               VERSION
jx                 1.3.645
jenkins x platform 0.0.3034
Kubernetes cluster v1.10.3
kubectl            v1.13.0
helm client        v2.10.0+g9ad53aa
helm server        v2.11.0+g2e55dbe
git                git version 2.7.4
Operating System   Ubuntu 16.04.4 LTS
```

**Comment by ccojocar** [comment] 2019-01-16 11:13
@ysaakpr Are you still facing this issue? Not clear to me which are the steps to reproduce the bug. Please could you provide more details? Thanks

It seems that it works for me with the latest version.

**Comment by ccojocar** [comment] 2019-02-20 09:05
@ysaakpr I am going to close this issue, sine the requested evidence weren't provided.

**Closed by ccojocar** 2019-02-20 09:05 UTC
Labels: area/buildpack, kind/bug, priority/awaiting-more-evidence
