### ISSUE TITLE
Have cron job to GC Preview environments after PR merges

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#544] opened 2018-04-02 09:51 UTC
We should have a TTL defined per team (on the Dev Environment CRD) to know how long to leave a preview environment before removing it with `jx delete env`

**Comment by rawlingsj** [comment] 2018-04-03 08:44
I think this is a duplicate of https://github.com/jenkins-x/jx/issues/420

**Comment by rawlingsj** [comment] 2018-07-13 12:59
The cron job is in and working now.

**Closed by rawlingsj** 2018-07-13 12:59 UTC
