### ISSUE TITLE
Fails to initiate staging environment pipeline

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3800] opened 2019-04-29 16:54 UTC
### Summary 

When creating a tekton-based jx cluster, environments repos fail to start builds.

### Steps to reproduce the behavior

```bash
PROJECT=[...] # Replace `[...]` with the name of the GCP project (e.g. jx).

echo "nexus:
  enabled: false
docker-registry:
  enabled: true
" | tee myvalues.yaml

jx create cluster gke \
    --cluster-name jx-rocks \
    --project-id $PROJECT \
    --region us-east1 \
    --machine-type n1-standard-2 \
    --min-num-nodes 1 \
    --max-num-nodes 2 \
    --default-admin-password=admin \
    --default-environment-prefix tekton \
    --git-provider-kind github \
    --namespace cd \
    --prow \
    --tekton \
    --batch-mode

# Import any project or create a quickstart
```

### Expected behavior

Runs the first pipeline successfully.

### Actual behavior

```bash
jx get build logs
```

```
...
Promoting app go-demo-6 version 1.0.51 to namespace cd-staging
Created Pull Request: https://github.com/vfarcic/environment-tekton-staging/pull/1

error: Pull request https://github.com/vfarcic/environment-tekton-staging/pull/1 last commit has status error for ref 9845add985e446f6c5dc69c977e767320e1813fd
{"component":"entrypoint","error":"wrapped process failed: exit status 1","level":"error","msg":"Error executing test process","time":"2019-04-29T16:38:49Z"}
```

```bash
kubectl get pods
```

```
...
vfarcic-go-demo-6-master-1-from-build-pack-gxdsw-pod-a16bfd   0/1     Init:Error   0          9m
```

The Pod for the build of the staging environment was not even created.

Any subsequential push fails to create pipeline Pod. It's as if only the first build/push creates a pipeline Pod and after that nothing.

Webhooks from GitHub were successful. 

Pull request created in the staging environment shows `unexpected response from pipeline runner service: 400 Bad`.

The commands used to create the cluster (this is a fresh one) are the same as before (when it worked). On top of that, I tried the same in AWS and AKS and the same issue is happening there as well.

Please let me know if there is any other info I can provide to help to debug the issue.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.66
jenkins x platform 2.0.141
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE, EKS, AKS

### Operating system / Environment

macOS

**Comment by rawlingsj** [comment] 2019-04-29 19:01
Closing as duplicate of https://github.com/jenkins-x/jx/issues/3788 as that has logs attached.

**Closed by rawlingsj** 2019-04-29 19:01 UTC
