### ISSUE TITLE
add build pack for .Net

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#561] opened 2018-04-04 10:20 UTC

**Comment by connorads** [comment] 2018-04-09 09:17
Exciting stuff! Is the plan to add support for the .NET Framework, .NET Core ... or both?

**Comment by jstrachan** [comment] 2018-04-09 09:32
@connorads lets do both! :) 

I wonder how the `Dockerfile` would differ between them? Would a single `Dockerfile` be good enough to build all .NET projects for c#?

**Comment by connorads** [comment] 2018-04-10 08:15
### .NET Core

@jstrachan I reckon that it would probably be easier to start with building .NET Core only, which is multi-platform by design and therefore has proper Linux support.
https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server

.NET Core is also what people are predominantly using for containerised microservices development and is what is recommended for use by Microsoft.
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/net-core-net-framework-containers/general-guidance

Microsoft already have a Docker image for building ASP.NET Core projects using a Linux container.
https://hub.docker.com/r/microsoft/aspnetcore-build/

### .NET Framework

I believe that to build .NET framework project for Windows using Docker you would need to use a Windows Container which I'm assuming would be a no-go for Jenkins X, at least for the foreseeable future.

.NET Framework does have support for containers but it's Windows containers only. It's also not the default choice recommended by Microsoft for containerised .NET applications.
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/net-core-net-framework-containers/general-guidance

Microsoft also have a Docker image for building .NET Framework which uses Windows Server 2016 Server Core (Windows container only).
https://hub.docker.com/r/microsoft/dotnet-framework-build/

**Comment by connorads** [comment] 2018-04-10 08:32
Nice one @rawlingsj, I agree it should be relatively easy.

It might be a good idea to make it clear that this issue is for adding .NET **Core** support and update the [Jenkins X roadmap](http://jenkins-x.io/contribute/roadmap/) accordingly.

**Comment by jstrachan** [comment] 2018-06-07 17:19
btw I just added this quickstart https://github.com/jenkins-x-quickstarts/aspnet-app

wonder if we need a 'just .NET Core' one too?

**Comment by connorads** [comment] 2018-11-27 12:46
Can we close this issue?

.NET **Core** seems to be working with Jenkins-X.

I used the Jenkins-X ASP.NET Core Quickstart @jstraxhan added with jx & GCP and it [worked well](https://github.com/connorads/happy-birthday-world) 👌

I reckon you only need to keep this issue open if you plan to get jx to work for .NET **Framework** which I imagine jx doesn't plan to support as it is primarily Windows only.

**Closed** 2019-08-03 00:09 UTC
Labels: area/buildpack, kind/enhancement, lifecycle/rotten, priority/backlog
