### ISSUE TITLE
Jx boot creating clusters that CI but don't CD...

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#5914] opened 2019-10-23 16:48 UTC
### Summary 
I have just created a fresh cluster instance with `jx boot`, including external DNS, TLS and vault. The cluster appears to run build pipelines but is not automatically processing PRs on Dev or Staging environments.

Viewing the PRs on these environments shows '1 pending check' and 'tide Pending - Not mergeable'.

### Jx version

The output of `jx version` is:

```
jx                 2.0.902
Kubernetes cluster v1.13.10-gke.0
kubectl            v1.16.2
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

jx boot

**Comment by tdcox** [comment] 2019-10-24 16:50
Ok, I have just tried this with a fresh cluster and I'm getting exactly the same results. If I manually merge the change to staging, no pipeline is started. GitHub claims that webhooks are being sent successfully but I don't see any fresh activity in the hook logs if I force redelivery.

**Comment by tdcox** [comment] 2019-10-28 10:46
Tried a third cluster with jx 2.0.918 and I'm getting the same thing again so it's 100% reproduceable. The only error I can find is in `tekton-pipelines-controller`:

```
W1028 10:34:18.784211       1 reflector.go:270] k8s.io/client-go/informers/factory.go:131: watch of *v1.ConfigMap ended with: too old resource version: 9484 (11059)
{"level":"info","logger":"controller.pipeline-controller.config-store","caller":"configmap/store.go:166","msg":"pipelinerun config \"config-artifact-bucket\" config was added or updated: &{  []}","knative.dev/controller":"pipeline-controller"}
```

**Comment by tdcox** [comment] 2019-10-28 10:47
My config is:
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config.git
cluster:
  clusterName: d77
  environmentGitOwner: bootstrap-jersey
  environmentGitPublic: true
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  project: jx-mar19
  provider: gke
  registry: gcr.io
  zone: europe-west1-d
environments:
- ingress:
    cloud_dns_secret_name: external-dns-gcp-sa
    domain: kill-9.uk
    externalDNS: true
    namespaceSubDomain: -jx.
    tls:
      email: terry@bootstrap.je
      enabled: true
      production: true
  key: dev
- ingress:
    domain: kill-9.uk
    externalDNS: true
    namespaceSubDomain: -st
    tls:
      email: terry@bootstrap.je
      enabled: true
      production: true
  key: staging
- ingress:
    domain: kill-9.uk
    externalDNS: true
    namespaceSubDomain: -pr
    tls:
      email: terry@bootstrap.je
      enabled: true
      production: true
  key: production
gitops: true
ingress:
  cloud_dns_secret_name: external-dns-gcp-sa
  domain: kill-9.uk
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: terry@bootstrap.je
    enabled: true
    production: true
kaniko: true
secretStorage: vault
storage:
  backup:
    enabled: true
    url: gs://d77-backup-3aafe27b-7b00-47fb-ad4b-48f17386e4aa
  logs:
    enabled: true
    url: gs://d77-logs-57c6b269-f0e0-4838-a02f-2722fec0bf08
  reports:
    enabled: true
    url: gs://d77-reports-ede28e16-9f3a-4942-a132-459eba26eb23
  repository:
    enabled: true
    url: gs://d77-repository-62741a76-ffc4-4e5e-a23f-ef7c5fd6b0d7
vault: {}
velero: {}
versionStream:
  ref: v1.0.161
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```

**Comment by abayer** [comment] 2019-10-28 11:29
We’re not seeing this in BDD tests, which do include PRs to dev, staging, and production. There are sporadic hangs on production promotions in some of those tests, but rather infrequently, which I’m pretty sure are specific to manual `jx promote` calls or possibly just the production env, since all the other PRs within the tests to envs are working consistently. Not all of the test contexts are using external DNS+vault+TLS, but that combination is being tested, and it’s behaving in a consistent manner to other boot setups in test contexts. The one major difference in our test context vs your setup is that the tests use private repos, and due to us not yet having a paid org that supports sufficient private repos, we’re using a repo under the GitHub user for the env repos. That means no forking is done, and that feels like it might be relevant.

**Comment by tdcox** [comment] 2019-10-28 14:31
All the repos here are public...

**Comment by abayer** [comment] 2019-10-28 15:12
What's the URL configured in the GitHub webhooks for the dev and staging repos?

**Comment by ccojocar** [comment] 2019-10-28 15:14
Are all the webhooks to dev, staging and production environment properly configured with HTTP? 

Have you tried to open a PR agains the dev environment, and you haven't seen any even arriving in the hook? Usually, you can see it in the logs as a PullRequest event.

**Comment by ccojocar** [comment] 2019-10-29 09:00
Alright, what exactly is your setup? Why are you pointing two hooks to the same repository? Do you keep a mirrored cluster or something like that? Do you have `dev | staging | production` namespaces in both clusters pointing to the exact same environment repositories?

**Comment by abayer** [comment] 2019-10-29 12:25
I _think_ @tdcox meant that `jx logs` shows the log from one of the two `hook` pods.

So the events are showing up in the `hook` logs, but nothing's getting triggered?

**Comment by tdcox** [comment] 2019-10-29 12:30
Correct

**Comment by ccojocar** [comment] 2019-10-29 12:45
Go it. Do you see any `ProwJobs` being created when the even is coming in - check the prow pipeline pod logs as well? if so, do you see any `PipelineRuns` being created? Maybe you can also check the pipelinerunner logs in this case. I suspect the issue is somewhere in there.

**Comment by ccojocar** [comment] 2019-10-29 12:46
`kubectl get prowjobs -w` to watch if everything is being created. The same with `pipelinerun`, `pipeline`.

**Comment by tdcox** [comment] 2019-10-30 12:14
There are two ProwJobs, one of which has failed:
```
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: pr-build
  creationTimestamp: "2019-10-28T10:53:36Z"
  generation: 7
  labels:
    created-by-prow: "true"
    event-GUID: 30642180-f971-11e9-8195-2ad0bce09f26
    prow.k8s.io/job: pr-build
    prow.k8s.io/refs.org: Bootstrap-Jersey
    prow.k8s.io/refs.pull: "1"
    prow.k8s.io/refs.repo: test306
    prow.k8s.io/type: presubmit
  name: 3191a453-f971-11e9-a83c-86fb57ac00c5
  namespace: jx
  resourceVersion: "18747"
  selfLink: /apis/prow.k8s.io/v1/namespaces/jx/prowjobs/3191a453-f971-11e9-a83c-86fb57ac00c5
  uid: 31952ec8-f971-11e9-83ea-42010af0011f
spec:
  agent: tekton
  cluster: default
  context: pr-build
  job: pr-build
  namespace: jx
  refs:
    base_link: https://github.com/Bootstrap-Jersey/test306/commit/379024d8df2428b9526586ccae4618bfc22431e0
    base_ref: master
    base_sha: 379024d8df2428b9526586ccae4618bfc22431e0
    org: Bootstrap-Jersey
    pulls:
    - author: tdcox
      author_link: https://github.com/tdcox
      commit_link: https://github.com/Bootstrap-Jersey/test306/pull/1/commits/2dfb827fe31a71c981efca22f154ff016946b1c2
      link: https://github.com/Bootstrap-Jersey/test306/pull/1
      number: 1
      sha: 2dfb827fe31a71c981efca22f154ff016946b1c2
    repo: test306
    repo_link: https://github.com/Bootstrap-Jersey/test306
  report: true
  rerun_command: /test this
  type: presubmit
status:
  build_id: "1"
  completionTime: "2019-10-28T11:01:05Z"
  description: All Tasks have completed executing
  prev_report_states:
    github-reporter: success
  startTime: "2019-10-28T10:53:36Z"
  state: success
```

```
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: ""
  creationTimestamp: "2019-10-28T10:28:10Z"
  generation: 4
  labels:
    created-by-prow: "true"
    prow.k8s.io/job: ""
    prow.k8s.io/refs.org: Bootstrap-Jersey
    prow.k8s.io/refs.repo: test306
    prow.k8s.io/type: postsubmit
  name: a2952f5a-f96d-11e9-b377-a2011842d783
  namespace: jx
  resourceVersion: "26481"
  selfLink: /apis/prow.k8s.io/v1/namespaces/jx/prowjobs/a2952f5a-f96d-11e9-b377-a2011842d783
  uid: a372ba3c-f96d-11e9-83ea-42010af0011f
spec:
  agent: tekton
  refs:
    base_ref: master
    base_sha: 379024d8df2428b9526586ccae4618bfc22431e0
    org: Bootstrap-Jersey
    repo: test306
  type: postsubmit
status:
  build_id: "1"
  completionTime: "2019-10-28T11:29:50Z"
  description: TaskRun bootstrap-jersey-test306-master-1-from-build-pack-fbwvb has
    failed
  startTime: "2019-10-28T10:28:10Z"
  state: failure
```

There are two metapipeline and two PipelineRuns. One of the PipelineRuns has failed:
```
  taskRuns:
    bootstrap-jersey-test306-master-1-from-build-pack-fbwvb:
      pipelineTaskName: from-build-pack
      status:
        completionTime: "2019-10-28T11:29:50Z"
        conditions:
        - lastTransitionTime: "2019-10-28T11:29:50Z"
          message: '"step-promote-jx-promote" exited with code 1 (image: "docker-pullable://gcr.io/jenkinsxio/builder-go@sha256:a8beab88c665da954ad9579dbbc049c847f168ac0347799989a7e749c00b8352");
            for logs run: kubectl -n jx logs bootstrap-jersey-test306-master-1-from-build-pack-fbwvb-pod-b9463c
            -c step-promote-jx-promote'
          reason: Failed
          status: "False"
```

There is only a metapipeline and Pipeline for the preview build.

The only build log is:
```
Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-mtk5g[0m
{"level":"warn","ts":1572258527.912241,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572258527.9126816,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-fbcd8[0m
{"level":"warn","ts":1572258528.9037983,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1572258528.9050224,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-bootstrap-jersey-test306-master-c7wkn[0m
{"level":"warn","ts":1572258537.9564695,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572258539.0318947,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/Bootstrap-Jersey/test306.git @ v0.0.1 in path /workspace/source"}

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:379024d8df2428b9526586ccae4618bfc22431e0
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-make-build[0m
CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -ldflags '' -o bin/test306 main.go

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] No base image, nothing to extract            
[36mINFO[0m[0000] cmd: EXPOSE                                  
[36mINFO[0m[0000] Adding exposed port: 8080/tcp                
[36mINFO[0m[0000] Using files from context: [/workspace/source/bin] 
[36mINFO[0m[0000] Skipping unpacking as no commands require it. 
[36mINFO[0m[0000] Taking snapshot of full filesystem...        
[36mINFO[0m[0000] EXPOSE 8080                                  
[36mINFO[0m[0000] cmd: EXPOSE                                  
[36mINFO[0m[0000] Adding exposed port: 8080/tcp                
[36mINFO[0m[0000] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0000] ENTRYPOINT ["/test306"]                      
[36mINFO[0m[0000] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0000] Using files from context: [/workspace/source/bin] 
[36mINFO[0m[0000] COPY ./bin/ /                                
[36mINFO[0m[0000] Taking snapshot of files...                  
2019/10/28 10:29:08 pushed blob: sha256:a74b8a14aa5803d178159edc8b3cde73d0369037b6e554080ec5263f5b9c0c08
2019/10/28 10:29:08 pushed blob: sha256:e764a7e2c9095aaaa6d1a8e649b6347762346f8f09a60da600574cd435c83edb
2019/10/28 10:29:10 gcr.io/**-mar19/test306:0.0.1: digest: sha256:f8326e5364b72e4573727743cfa67298ffee7becc60510c940f96fed353f6b1a size: 428

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/test306 to an unshallow repository
Generating change log from git ref 1574e19f2ec5a8b6b5486eb37e26b441b94a23c9 => 84d33619938992cc8d7b8990f392bf4202825677
Associating user x-0 in users.jenkins.io with email terry@bootstrap.je to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 379024d8df2428b9526586ccae4618bfc22431e0 with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
WARNING: No release found for Bootstrap-Jersey/test306 and tag v0.0.1 so creating a new release
Updated the release information at https://github.com/Bootstrap-Jersey/test306/releases/tag/v0.0.1
generated: /workspace/source/charts/test306/templates/release.yaml
Created Release test306-0-0-1 resource in namespace **
Updating PipelineActivity bootstrap-jersey-test306-master-1 with version 0.0.1
Updated PipelineActivities bootstrap-jersey-test306-master-1 with release notes URL: https://github.com/Bootstrap-Jersey/test306/releases/tag/v0.0.1

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Read credentials for https://storage.googleapis.com/chartmuseum.jenkins-x.io from vault helm/repos
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Read credentials for http://jenkins-x-chartmuseum:8080 from vault helm/repos
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file test306-0.0.1.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mbootstrap-jersey-test306-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
Promoting app test306 version 0.0.1 to namespace **-staging
WARNING: Waiting for the fork of ********/environment-d77-staging to appear...
Forked Git repository to https://github.com/********/environment-d77-staging
Created Pull Request: https://github.com/Bootstrap-Jersey/environment-d77-staging/pull/1
WARNING: Failed to query the Pull Request last commit status for https://github.com/Bootstrap-Jersey/environment-d77-staging/pull/1 ref dc2e8398dc3edf067892b7f3073ae8426d9e1f5e Could not find a status for repository bootstrap-jersey/environment-d77-staging with ref dc2e8398dc3edf067892b7f3073ae8426d9e1f5e
error: Timed out waiting for pull request https://github.com/Bootstrap-Jersey/environment-d77-staging/pull/1 to merge. Waited 1h0m0s
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-promote-jx-promote'. The execution of the pipeline has stopped.[0m
```

**Comment by Sfynx** [comment] 2019-11-02 03:44
I noticed this issue as well, and environments I created later with `jx create environment` worked correcty (PRs getting merged automatically, deployments getting done upon merging to master). It's just the default environments that get created during installations that do not seem to trigger the pipelines.

**Comment by tdcox** [comment] 2019-11-18 17:12
Still seeing this with a fresh install using 2.0.998.

I set up a clean cluster and created a go quickstart instance. The project built and the PR on Staging merged, but there was no subsequent release build and no release.

Correllating GitHub WebHook calls with the logs from the two Hook pods, I am seeing some strange behaviours:

The first calls from Dev and Staging environments fail with 503, so there appears to be a race condition getting the Hook pods up in time to respond to the first calls.

Then I can see 9 WebHook calls that are marked with 200 responses on GitHub, but which have no entry in the Hook logs for either pod.

I see 11 calls that are successful on GitHub and in the Hook logs.

**Comment by deanesmith** [comment] 2019-11-22 01:13
@tdcox I'm going to try to repro this on a build tomorrow.  We're having troubles reliably repro'ing.  My config does differ slightly though.

**Comment by tdcox** [comment] 2019-11-24 20:37
Just tested again with 2.0.1011 and a github org that supports private repos. This time around, I get a branch created on staging for the promote but no PR is created, so it's getting worse.

**Comment by tdcox** [comment] 2019-11-24 20:55
Correction, the PR has been created and merged, but the redeploy of staging never occurs, so same symptoms as before.

I note that the webhook for the promote has the wrong author and committer details:
````
      "author": {
        "name": "jenkins-x-bot",
        "email": "jenkins-x@googlegroups.com"
      },
      "committer": {
        "name": "jenkins-x-bot",
        "email": "jenkins-x@googlegroups.com"
      },
````

**Comment by deanesmith** [comment] 2019-11-25 15:03
Thank you @tdcox.  We'll get on this one.

**Comment by tdcox** [comment] 2019-11-26 12:07
Ok, the plot thickens...

I tried a basic install by just following the `jx boot` prompts to install a platform with no dns, no tls, no vault. Hit exactly the same problem, so it's core functionality rather than due to anything optional.

I then tried creating a new environment with an `auto` promote strategy. Initially, I hit a problem because this doesn't add the pipeline bot user as a collaborator on the environment repo in the way that the original install does, which breaks the promotion stage of a build.

Once I added the bot user manually to the repo, builds were able to successfully automatically promote to the new environment, but still fail on staging.

What is interesting is that there is a difference in the log output for the promote attempts to the two environments:

```
Showing logs for build bootstrap-jersey/test310/master #3 stage from-build-pack and container step-promote-jx-promote
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/jx/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app test310 version 0.0.3 to namespace jx-man
Created Pull Request: https://github.com/Bootstrap-Jersey/environment-jx-man/pull/1
Added label updatebot to Pull Request https://github.com/Bootstrap-Jersey/environment-jx-man/pull/1
got git provider status pending from PR https://github.com/Bootstrap-Jersey/environment-jx-man/pull/1
got git provider status pending from PR https://github.com/Bootstrap-Jersey/environment-jx-man/pull/1
got git provider status pending from PR https://github.com/Bootstrap-Jersey/environment-jx-man/pull/1
got git provider status pending from PR https://github.com/Bootstrap-Jersey/environment-jx-man/pull/1
Pull Request https://github.com/Bootstrap-Jersey/environment-jx-man/pull/1 is merged at sha d133d7ab27d0139ebe9e374ed1146cfce98036e0
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace jx-man for names test310, jx-test310, jx-man-test310
Promoting app test310 version 0.0.3 to namespace jx-staging
Created Pull Request: https://github.com/Bootstrap-Jersey/environment-d80-staging/pull/2
Added label updatebot to Pull Request https://github.com/Bootstrap-Jersey/environment-d80-staging/pull/2
WARNING: Failed to query the Pull Request last commit status for https://github.com/Bootstrap-Jersey/environment-d80-staging/pull/2 ref 9590f8dadd36dbdbbbdd72d277281db9865e6b6a Could not find a status for repository bootstrap-jersey/environment-d80-staging with ref 9590f8dadd36dbdbbbdd72d277281db9865e6b6a
WARNING: Failed to query the Pull Request last commit status for https://github.com/Bootstrap-Jersey/environment-d80-staging/pull/2 ref 9590f8dadd36dbdbbbdd72d277281db9865e6b6a Could not find a status for repository bootstrap-jersey/environment-d80-staging with ref 9590f8dadd36dbdbbbdd72d277281db9865e6b6a
WARNING: Failed to query the Pull Request last commit status for https://github.com/Bootstrap-Jersey/environment-d80-staging/pull/2 ref 9590f8dadd36dbdbbbdd72d277281db9865e6b6a Could not find a status for repository bootstrap-jersey/environment-d80-staging with ref 9590f8dadd36dbdbbbdd72d277281db9865e6b6a
Pull Request https://github.com/Bootstrap-Jersey/environment-d80-staging/pull/2 is merged at sha c264887d33334b13343a8ae4d78cfa60430498ba
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace jx-staging for names test310, jx-test310, jx-staging-test310
```

**Comment by tdcox** [comment] 2019-11-26 13:58
I suggest testing with an organisation that contains upper case characters. I can see some inconsistency with respect to the handling of case, for example, the `url:` in the environment yaml for staging is lower case but for the one created by `jx create environment`, the same entry is mixed case.

This doesn't fix this bug, but has traditionally been a source of multiple errors in the past.

**Comment by tdcox** [comment] 2020-01-03 17:08
Still seeing the same problem with `2.0.1100`

**Comment by abayer** [comment] 2020-01-06 15:37
So the last log seems to show that the manually created environment is getting a pipeline triggered for its PR, but the staging environment is not, which fits with what was brought up earlier in this issue. Any chance you could send me the Prow config map from a cluster where you're seeing this? i.e., `kubectl get configmap config -o yaml`. You can send it to me directly on Slack.

**Comment by abayer** [comment] 2020-01-06 17:24
Ok, based on what @tdcox sent me, I'm pretty sure it is in fact the case of `environmentGitOwner`. The Prow config has the org/repo name for the `dev`, `staging`, and `production` env repos as `bootstrap-jersey/(whatever)`, but the actual org/repo name passed in by the webhooks is going to be `Bootstrap-Jersey/(whatever)`. Prow is case-sensitive when it checks to see if an org/repo name combo it sees in a hook should be acted on, since it's looking up the combo in the map generated from the Prow config map, so I would expect it not to fire anything in response to `Bootstrap-Jersey/(whatever)` hooks.

Waiting on verification that fixing the case in the config map by hand does the trick, and while I'm waiting, I'm trying to figure out a way we can test this properly short of adding a BDD test that uses a non-lowercase org name.

**Comment by tdcox** [comment] 2020-01-06 18:29
This bug has cropped up so many times over the past few years that I suggest a test organisation with camel case and a hyphen is necessary for all git related features.

**Comment by abayer** [comment] 2020-01-06 19:18
Verified - the combination of #6420 and https://github.com/jenkins-x-charts/jxboot-resources/pull/22 fixes things - we no longer force `environmentGitOwner` to be lower-case, and we make sure that the env repo `SourceRepository` names are lower-cased. Then things work correctly.

**Closed** 2020-01-06 20:00 UTC
Labels: area/promote, area/prow, in progress, kind/bug, priority/critical
