### ISSUE TITLE
prow-build: Error running controller: failed to wait for caches to sync

### ISSUE THREAD

**Issue by jglick** [jenkins-x/jx#2579] opened 2018-12-26 20:25 UTC
### Summary 

The `prow-build` deployment in our cluster sometimes goes into a `CrashLoopBackOff`. The logs show:

```
$ kail -d prow-build --since=1h
jx/prow-build-7996d4df65-6tqm7[prow-build]: time="2018-12-26T20:04:08Z" level=info msg="Setting up event handlers" 
jx/prow-build-7996d4df65-6tqm7[prow-build]: time="2018-12-26T20:04:08Z" level=info msg="Starting Build controller" 
jx/prow-build-7996d4df65-6tqm7[prow-build]: time="2018-12-26T20:04:08Z" level=info msg="Waiting for informer caches to sync" 
jx/prow-build-7996d4df65-6tqm7[prow-build]: time="2018-12-26T20:05:08Z" level=warning msg="Interrupt received, attempting clean shutdown..." 
jx/prow-build-7996d4df65-6tqm7[prow-build]: time="2018-12-26T20:05:08Z" level=fatal msg="Error running controller: failed to wait for caches to sync" 
jx/prow-build-7996d4df65-6tqm7[prow-build]: time="2018-12-26T20:06:10Z" level=warning msg="Interrupt received, attempting clean shutdown..." 
jx/prow-build-7996d4df65-6tqm7[prow-build]: time="2018-12-26T20:06:10Z" level=fatal msg="Error running controller: failed to wait for caches to sync" 
```

### Kubernetes cluster

GKE

### Investigation

Sometimes running

```sh
kubectl delete builds,prowjobs --all
kubectl delete pod prow-build-...
```

fixes the issue; sometimes it does not.

After one pod printed `Waiting for informer caches to sync` I `kubectl exec`ed in and `kill -QUIT`ted PID 1, getting a thread dump including

```
goroutine 1 [chan receive]:
k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000410400, 0xc0003eb198, 0xc00030a360, 0xc000046200, 0xc00043c900)
    /Users/jr/go/src/k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:330 +0x58
k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/util/wait.PollUntil(0x5f5e100, 0xc0003eb198, 0xc00030a360, 0x0, 0xc0003eb1b8)
    /Users/jr/go/src/k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:290 +0x56
k8s.io/test-infra/vendor/k8s.io/client-go/tools/cache.WaitForCacheSync(0xc00030a360, 0xc0003eb210, 0x1, 0x1, 0x0)
    /Users/jr/go/src/k8s.io/test-infra/vendor/k8s.io/client-go/tools/cache/shared_informer.go:108 +0x79
main.(*controller).Run(0xc000432850, 0x2, 0xc00030a360, 0x0, 0x0)
    /Users/jr/go/src/k8s.io/test-infra/prow/cmd/build/controller.go:158 +0x17d
main.main()
    /Users/jr/go/src/k8s.io/test-infra/prow/cmd/build/main.go:198 +0x80d
```

which is not particularly informative. There is no other apparent logging indicating what the process is attempting to do and why it fails. I am not sure whether this is in `jenkins-x/test-infra` or the upstream Prow code, and which exact version; the image is `rawlingsj/build:upstream76`, which [seems to be about a month old](https://hub.docker.com/r/rawlingsj/build/tags?page=2). Another cluster using the same image is not currently exhibiting this problem.

Not sure if this has anything to do with #2539.

**Comment by jglick** [comment] 2018-12-27 01:31
Seems like it spontaneously heals a few hours later.

**Comment by rawlingsj** [comment] 2018-12-27 12:06
Yeah this is a known issue and duplicate of #2539.  I've upgraded our own prod cluster before the festive break and it's been looking good so far.  When I return on the 7th I'll be working out the best way to release and roll out the fixes as it's not a simple `jx upgrade platform`.  Closing as duplicate of #2539.

**Closed by rawlingsj** 2018-12-27 12:06 UTC
Labels: area/prow, kind/bug

**Comment by jglick** [comment] 2018-12-31 18:44
Is there a hotfix? I tried `kubectl edit deployment prow-build` and then

```diff
--- broken.yaml
+++ working.yaml
@@ -34,7 +34,9 @@
       - args:
         - --tot-url
         - http://buildnum
-        image: rawlingsj/build:upstream76
+        - --config
+        - /etc/config/config.yaml
+        image: rawlingsj/build:upstream124
         imagePullPolicy: IfNotPresent
         livenessProbe:
           exec:
@@ -42,7 +44,7 @@
             - cat
             - /tmp/started
           failureThreshold: 1
-          initialDelaySeconds: 60
+          initialDelaySeconds: 360
           periodSeconds: 2
           successThreshold: 1
           timeoutSeconds: 1
@@ -59,13 +61,17 @@
           timeoutSeconds: 1
         resources:
           limits:
-            cpu: 200m
-            memory: 256Mi
+            cpu: 500m
+            memory: 1Gi
           requests:
-            cpu: 100m
-            memory: 128Mi
+            cpu: 250m
+            memory: 512Mi
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
+        volumeMounts:
+        - mountPath: /etc/config
+          name: config
+          readOnly: true
       dnsPolicy: ClusterFirst
       restartPolicy: Always
       schedulerName: default-scheduler
@@ -73,21 +79,27 @@
       serviceAccount: prow-build
       serviceAccountName: prow-build
       terminationGracePeriodSeconds: 30
+      volumes:
+      - configMap:
+          defaultMode: 420
+          name: config
+        name: config
 status:
```

which partially worked—`prow-build` starts fine and in fact runs builds, which you can follow via `jx get build log` etc.—but for every build prints an error

```
… controller.go:218] failed to reconcile /jx/…: update prow status: Operation cannot be fulfilled on prowjobs.prow.k8s.io "…": the object has been modified; please apply your changes to the latest version and try again
```

and the GitHub commit status is set to

> **serverless-jenkins** — missing end condition

**Comment by rawlingsj** [comment] 2018-12-31 20:08
There is and I tried to keep the associated issues as up to date as I could during the last two days before the festive break.  Like I said it is not a simple upgrade as it involves removing and reinstalling a new knative build release.  I'm on PTO until the 7th and I'll be on this as my priority but so until then the best workaround is to:
```
kubectl delete prowjobs --all
kubectl delete builds --all
```
And the `prowbuild` controller will start after a few attempts.  

As I'm on PTO I probably wont really have access to my laptop until I'm back, if the workaround above isn't enough or you really can't wait the 3 remaining working days then I can sort you cluster out before then, but if possible I'd ask you to wait until I can do this properly and not during the holiday period.

**Comment by rawlingsj** [comment] 2018-12-31 20:17
@jglick if you don't mind me connecting to your cluster, probably tomorrow I'll patch your install with the updates that I've not been able to release yet but fix this.  I'll update the issues with the details when I'm back but it will at least get you going wed/thurs/fri.  Just lemme know the cluster name.
