### ISSUE TITLE
Test failure on power: "bouk/monkey/replace.go:24:14: undefined: jmpToFunctionValue"

### ISSUE THREAD

**Issue by meghalidhoble** [jenkins-x/jx#2081] opened 2018-10-25 06:27 UTC
### Summary 
Test failure at bouk/monkey Go module. 

### Steps to reproduce the behavior
- Build the source for jenkinsX/jx using "make build"
- Run "make test" 

### Jx version
The output of `jx version` is:
```
NAME VERSION
jx   1.0.1
git  git version 2.7.4
```

### Kubernetes cluster
Local cluster, created using minikube setup.

### Operating system / Environment
Linux Ubuntu16.04 / ppc64le architecture 

### Expected behavior
Test should pass. 

### Actual behavior
Failing with a missing function message: 
```
# github.com/jenkins-x/jx/vendor/github.com/bouk/monkey
vendor/github.com/bouk/monkey/replace.go:24:14: undefined: jmpToFunctionValue
```
Looking at the code I observed that there are architecture specific implementation for monkey.so 
monkey_386.go:4:func jmpToFunctionValue(to uintptr) []byte {
monkey_amd64.go:4:func jmpToFunctionValue(to uintptr) []byte {

I could not find a generic implementation in place which should work for other architectures?
Is there a generic implementation available which I might have missed ? Some guideline to fix this would really help.

Thanks,
Meghali

**Comment by jtnord** [comment] 2018-11-26 17:01
I don't think the build has been tested on non intel architectures.

**Comment by ccojocar** [comment] 2019-01-15 16:14
This looks like a Go issue when compiling the code to a different architecture than x386/amd64.  The problem is in the `bouk/monkey` package which has a dependency to `amd64`. 

I am going to close this issue, because we are not planning to support non-intel architectures.

**Closed by ccojocar** 2019-01-15 16:14 UTC

**Comment by tinhtran24** [comment] 2021-05-11 08:25
Can we update for M1 apple silicon

**Comment by prashant-chai** [comment] 2021-08-13 08:20
This is sad, doesn't work on mac with new M1 chips. @ccojocar Any idea when it might be supported

**Comment by zcool321** [comment] 2021-08-30 09:54
M1 monkey doesn't work~~~

**Comment by keroro6** [comment] 2021-09-23 03:09
I also meet the problem,  It doesn't work  on mac with M1

**Comment by alexfaker** [comment] 2021-09-30 10:00
anybody has replaceable & wonderful way？

**Comment by dribler** [comment] 2021-09-30 10:25
As a workaround. Run with GOARCH=amd64 appears to work on M1. This also work in Golang, it the variable set in "Run/debug configuration".

**Comment by prashant-chai** [comment] 2021-09-30 10:39
Where to set the GOARCH? In the **environment** variables?

**Comment by dribler** [comment] 2021-09-30 10:41
Right in env variables
![image](https://user-images.githubusercontent.com/4450612/135440681-31acce35-9314-46c2-aadb-cd2070c650f3.png)

**Comment by prashant-chai** [comment] 2021-09-30 10:42
I'll try and let you know

**Comment by hpareek1996** [comment] 2021-10-18 16:04
Did it worked for you @prashant-chai ? I tried setting it up on terminal and run test case but facing same error. Can you please help @dribler

**Comment by abhinav2196** [comment] 2021-12-20 10:13
Putting this variable takes away ability to stop at break points while debugging. @prashant-chai

**Comment by ldominique92** [comment] 2022-02-07 15:07
It doesn't work with kafka tho because for kafka we need to say that the architecture is arm64

**Comment by sunhao1256** [comment] 2022-03-22 05:21
> Putting this variable takes away ability to stop at break points while debugging. @prashant-chai

i get same problem，how to fix

**Comment by prashant-chai** [comment] 2022-03-22 05:26
@sunhao1256 Yep breakpoints don't work for me too but you can always make the most from print statements

**Comment by temorfeouz** [comment] 2022-04-11 09:58
i just added this function jmpToFunctionValue for default architecture and breakpoints works. Going to check what can going wrong

**Comment by 41412179** [comment] 2022-05-11 02:44
不支持Apple Mac M1

**Comment by 41412179** [comment] 2022-05-11 02:56
解决了，方法：env文件里面加上那个goarch=arm64

**Comment by joeywang2020** [comment] 2022-05-12 07:18
> 解决了，方法：env文件里面加上那个goarch=arm64

are you sure? not work for me?

**Comment by hpareek1996** [comment] 2022-05-12 07:37
@joeywang2020 It should work, try adding the variable `GOARCH=arm64` by running it with Goland and adding this variable to by clicking on Modify run configuration.

**Comment by temorfeouz** [comment] 2022-05-27 09:10
if set GOARCH=arm64 on mac with m1 breakpoints stop working

**Comment by sunhao1256** [comment] 2022-05-27 09:12
> if set GOARCH=arm64 on mac with m1 breakpoints stop working

same probleam

**Comment by hasan356** [comment] 2022-06-09 06:43
Breakpoints also working for me i did the same change `GOARCH=amd64`, may be because of the golang version i am using go1.18

**Comment by fdx321** [comment] 2022-06-10 09:35
> if set GOARCH=arm64 on mac with m1 breakpoints stop working

same with you

**Comment by MrWangwj** [comment] 2022-06-30 12:44
> Right in env variables ![image](https://user-images.githubusercontent.com/4450612/135440681-31acce35-9314-46c2-aadb-cd2070c650f3.png)

this is method is OK

**Comment by procodr** [comment] 2022-11-02 23:01
The arm64 compile problem of bouk/monkey is fixed by @Leo-Guo here: https://github.com/Leo-Guo/monkey
but with wrong module name,
so I have simply fixed module name: https://github.com/procodr/monkey

Tested on M1 with `GOARCH=arm64` and working breakpoints.

**Comment by Leo-Guo** [comment] 2022-11-02 23:02
感谢您的邮件，祝您生活愉快

**Comment by zhangmanman** [comment] 2024-06-18 12:40
> As a workaround. Run with GOARCH=amd64 appears to work on M1. This also work in Golang, it the variable set in "Run/debug configuration".

It worked successfully

**Comment by Leo-Guo** [comment] 2024-06-18 12:41
感谢您的邮件，祝您生活愉快
