### ISSUE TITLE
Unable to install custom plugins

### ISSUE THREAD

**Issue by jonheckman** [jenkins-x/jx#1562] opened 2018-08-30 17:58 UTC
### Summary 
JenkinsX does not allow the ability to install custom plugins. When a plugin is installed it will work until the container is restarted. 
The install files for the plugin will still be on the volume, but Jenkins does not recognize it.

### Steps to reproduce the behavior
1. Install any plugin
2. Restart the container
3. Try to use the plugin

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.25
jenkins x platform 0.0.2252
kubernetes cluster v1.10.3
kubectl            v1.10.5
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.15.2
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Using a spotinst cluster on AWS created using Kops

### Expected behavior
The plugins should remain after the container is restarted

### Actual behavior
The plugin is no longer in Jenkins after the container restarts

### Notes
I have seen references to being able to create our own docker container from https://github.com/jenkins-x/jenkins-x-image
But I am unable to find any documentation about how to use this image when installing jenkins-x or if there is a proper way of installing custom plugins.

**Comment by hekonsek** [comment] 2018-10-02 19:09
Can you send us the commands to reproduce the issue using one of the standard plugins?

**Comment by ysaakpr** [comment] 2018-12-06 07:32
Can some one direct what is the way to install additional plugins, and configuring them in jenkins-x setup. Even i was facing the same issue, since the dynamically installed plugins are unable to work as expected after restart of the pod.

**Comment by ccojocar** [comment] 2019-01-15 13:45
You can add your plugins to https://github.com/jenkins-x/jenkins-x-image/blob/master/plugins.txt and build a custom docker image for jenkins. You can then use this image your  `~/.jx/myvalues.yaml`. 

I am going to close this issue for now.

**Closed by ccojocar** 2019-01-15 13:45 UTC
