### ISSUE TITLE
Invalid User.jenkins.io "" when username is all numbers

### ISSUE THREAD

**Issue by porterja31** [jenkins-x/jx#3818] opened 2019-04-30 21:08 UTC
### Summary 
When attempting to install the environment controller with cli I was met with an error.
 
### Steps to reproduce the behavior
jx create addon envctl -s https://github.com/my-org/my-env-repo.git --docker-registry ecrdomain.ecr.us-east-1.amazonaws.com

### Expected behavior
Environment Controller Installs

### Actual behavior
```
etched chart environment-controller to dir /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-624239272/jxet/chartFiles/environment-controller
error: Failed to run helm template --name jxet --namespace jx /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-624239272/jxet/chartFiles/environment-controller --output-dir /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-624239272/jxet/output --debug --set source.owner=my-org --set source.repo=my-env-repo --set source.serverURL=https://github.myorg.com --set source.gitKind=github --set source.user=myuserid --set source.token=mytoken --set dockerRegistry=ecrdomain.ecr.us-east-1.amazonaws.com --set tekton.rbac.cluster=false: failed to run 'helm template --name jxet --namespace jx /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-624239272/jxet/chartFiles/environment-controller --output-dir /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-624239272/jxet/output --debug --set source.owner=my-org --set source.repo=my-env-repo --set source.serverURL=https://github.myorg.com --set source.gitKind=github --set source.user=myuserid--set source.token=mytoken --set dockerRegistry=ecrdomain.dkr.ecr.us-east-1.amazonaws.com --set tekton.rbac.cluster=false' command in directory '', output: 'Error: render error in "environment-controller/templates/pipeline-git-secret.yaml": template: environment-controller/templates/pipeline-git-secret.yaml:16:37: executing "environment-controller/templates/pipeline-git-secret.yaml" at <b64enc>: wrong type for value; expected string; got float64'
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.70
Kubernetes cluster v1.11.8-eks-7c34c0
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.13.6 build 17G6030
```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [x] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
EKS 

### Operating system / Environment
macOS

**Comment by porterja31** [comment] 2019-05-13 20:43
Just wanted to bump this to see if anything was happening in this space.

**Comment by lgg42** [comment] 2019-05-25 11:02
Could you post the contents of pipeline-git-secret.yaml changing some/most sensitive values characters?

**Comment by porterja31** [comment] 2019-05-29 17:32
I'm also seeing a similar error now when trying to install using tekton. I think it might be related to the fact that our enterprise github uses only numbers for our user names ie. our 9 digit employee numbers.

`error: configuring and installing Prow: installing Prow: failed to install Tekton: after 2 attempts, last error: Failed to run helm template --name tekton --namespace jx /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-402217070/tekton/chartFiles/tekton --output-dir /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-402217070/tekton/output --debug --set  --set tillerNamespace= --set auth.git.username=999999999 --set auth.git.password=api token here: failed to run 'helm template --name tekton --namespace jx /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-402217070/tekton/chartFiles/tekton --output-dir /var/folders/yv/ttf8kg1s5w74b0vczzsby4440000gn/T/helm-template-workdir-402217070/tekton/output --debug --set  --set tillerNamespace= --set auth.git.username=999999999 --set auth.git.password=api token here' command in directory '', output: 'Error: render error in "tekton/templates/250-git-secret.yaml": template: tekton/templates/250-git-secret.yaml:5:43: executing "tekton/templates/250-git-secret.yaml" at <b64enc>: wrong type for value; expected string; got float64'`

**Comment by porterja31** [comment] 2019-06-07 15:19
Any tracking on this I talk to James about this on slack and it seems that the github username might need to be wrapped inside quotes so its interpreted as string in the code. This is blocking my team from trying out nextgen with our enterprise github because all our usernames are numeric

**Comment by porterja31** [comment] 2019-06-10 20:39
I believe now that the regex that creates a user or secret is expecting alphanumeric but our enterprise is only using numbers for internal reasons on our enterprise github. I've seen issues with PR builds, env controller chart installs and next gen chart installs.

**Comment by porterja31** [comment] 2019-06-10 20:41
I also get this error when I just try to do jx create user with creds like -l 999999999 -e "porterja31@github.com" -n porterja31

**Comment by jstrachan** [comment] 2019-06-24 10:33
wonder if this is a duplicate of https://github.com/jenkins-x/jx/issues/3731

**Closed** 2019-06-24 16:41 UTC
