### ISSUE TITLE
jx fails to install helm

### ISSUE THREAD

**Issue by jtnord** [jenkins-x/jx#2010] opened 2018-10-17 13:30 UTC
### Summary 

jx create detects helm is not installed and the auto install fails.

### Steps to reproduce the behavior

```
[gke-sso] C:\workarea\jx>jx create terraform --environment-git-owner cb-kubecd --verbose
? Missing required dependencies, deselect to avoid auto installing: terraform, helm
Downloading https://releases.hashicorp.com/terraform/0.11.9-beta1/terraform_0.11.9-beta1_windows_amd64.zip to C:\Users\jnord\.jx\bin\terraform.exe.zip...
Downloaded C:\Users\jnord\.jx\bin\terraform.exe.zip
Downloading https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-windows-amd64.tar.gz to C:\Users\jnord\.jx\bin\helm.exe.tgz...
Downloaded C:\Users\jnord\.jx\bin\helm.exe.tgz
Using helmBinary helm with feature flag: none
error: error installing helm: failed to run 'C:\Users\jnord\.jx\bin\helm.exe plugin install https://github.com/futuresimple/helm-secrets' command in directory '', output: 'Error: exec: "sh": executable file not found in %PATH%': exit status 1
```

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
Failed to find helm installs: failed to run 'helm list' command in directory '', output: 'Error: could not find tiller': exit status 1
Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Client: v2.11.0+g2e55dbe
Error: could not find tiller': exit status 1
NAME               VERSION
jx                 [32m1.3.441[0m
Kubernetes cluster [32mv1.9.7-gke.5[0m
kubectl            [32mv1.10.3[0m
git                [32mgit version 2.16.2.windows.1[0m
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

N/A

### Operating system / Environment

Windows 10

### Expected behavior

the auto install works

### Actual behavior

it does not

**Comment by agentgonzo** [comment] 2018-10-26 13:44
Dupe of #2007

**Closed by agentgonzo** 2018-10-26 13:44 UTC
Labels: windows
