### ISSUE TITLE
jx import hangs if not given a path

### ISSUE THREAD

**Issue by michaelneale** [jenkins-x/jx#328] opened 2018-03-01 07:36 UTC
eg: 

cd demo
jx import

it will hang. 

If you run `jx import .` it works but gets very confused by the . name. needs to be more hardening about where import is run.

**Comment by rajdavies** [comment] 2018-03-01 15:45
Couldn't reproduce - I'm using:
NAME        VERSION
jx          1.0.1
Jenkins X   0.0.242
Kubernetes  v1.7.12-gke.1
Helm Client v2.7.2+g8478fb4
Helm Server v2.7.2+g8478fb4
Git         git version 2.15.1

**Comment by michaelneale** [comment] 2018-03-01 23:09
@rajdavies and you cd'ed into say a spring boot, and typed just "jx import" on its own? if so - close this.

**Comment by michaelneale** [comment] 2018-03-05 08:48
@rajdavies I can easily reproduce this still - just unzip a sample spring project and run jx import from within it:
http://start.spring.io/  download anything: 

`jx import`

nothing happens (using gke)

NAME        VERSION
jx          1.0.113
Jenkins X   0.0.252
Kubernetes  v1.7.12-gke.1
Helm Client v2.7.2+g8478fb4
Helm Server v2.7.2+g8478fb4
Git         git version 2.14.1

**Comment by i0n** [comment] 2018-07-06 16:34
Let's have a look see.

**Comment by ccojocar** [comment] 2019-02-20 09:49
@michaelneale I am going to close this issue, since it seems quite old and the import has improved since then. Please feel free to open another issue if you are still encountering this problem. Thanks

**Closed by ccojocar** 2019-02-20 09:49 UTC
Labels: area/import, kind/bug, priority/important-soon
