### ISSUE TITLE
Pipeline image pull problem cased by cgw

### ISSUE THREAD

**Issue by YuTingLiu** [jenkins-x/jx#4809] opened 2019-07-20 02:07 UTC
### Summary 
jx pipeline  was coded pull image from gcr.io, which can not access from china.
### Steps to reproduce the behavior
1. install static jx.
2. clone a maven project to local disk.
3. run `jx import .` in this project.
### Expected behavior
mvn-pod running
### Actual behavior
`Back-off pulling image "gcr.io/jenkinsxio/builder-maven:0.1.586"`
### Jx version
The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.368
jenkins x platform 2.0.861
Kubernetes cluster v1.12.8
kubectl            v1.12.8
helm client        Client: v2.14.0+g05811b8
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.6.1810 (Core)
WARNING:
A new jx version is available: 2.0.493
```

### Jenkins type
- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [*] Classic Jenkins

### Kubernetes cluster
kops

### Operating system / Environment
cenos

**Comment by pmuir** [comment] 2019-07-25 13:44
Dupe of #3691

**Closed by pmuir** 2019-07-25 13:44 UTC
