### ISSUE TITLE
Jenkins Build fails with the error - failed to read the Helm version: failed to run 'helm version --short' command in directory '.', output: 'Client: v2.10.0+g9ad53a a

### ISSUE THREAD

**Issue by etSingh** [jenkins-x/jx#1998] opened 2018-10-16 15:13 UTC
### Summary 
Jenkins build fails with the message 
```
+ jx step helm release
No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Using helmBinary helm with feature flag: none
error: failed to build dependencies for chart from directory '.': failed to read the Helm version: failed to run 'helm version --short' command in directory '.', output: 'Client: v2.10.0+g9ad53aa
Error: forwarding ports: error upgrading connection: the server could not find the requested resource': exit status 1
```

### Steps to reproduce the behavior

 + Create a Kubernetes cluster in GKE
`jx create cluster gke --skip-login  --default-admin-password=mySecretPassWord123 -n myclustername`

+ Create a Spring boot service- `jx create spring -d web -d actuator` 

### Jx version

The output of `jx version` is: 
```
NAME               VERSION
jx                 1.3.439
jenkins x      platform 0.0.2771
Kubernetes  cluster v1.9.7-gke.6
kubectl         v1.10.7
helm client   v2.11.0+g2e55dbe
helm server  v2.11.0+g2e55dbe
git                git version 2.11.0
```

### Kubernetes cluster

Using a Kubernetes cluster with GKE which was created via the command
`jx create cluster gke --skip-login  --default-admin-password=password -n myclustername`

### Operating system / Environment
Google cloud shell

### Repository created by jx
https://github.com/etSingh/data_processor

**Comment by omermizrahi** [comment] 2018-10-16 17:31
happened to me today too, the only thing that helped me was to delete jx namespace and reinstall jx on the cluster.

**Comment by mikaelmh** [comment] 2018-10-17 04:33
Same here. Happened to me yesterday as well. I re-installed, deleted the cluster and re-installed several times, but still stuck. 

After downgrading helm to 2.10, it still fails {authorization denied) at the same step as it is trying to push the chart to `http://jenkins-x-chartmuseum:8080`  (it seems to essentially be the same error as I think it is not able to connect with local chart museum, though I can navigate to the chartmuseum URL in the browser).

Anyone able to solve this?

**Comment by hgajjar** [comment] 2018-10-18 11:15
Same here, I think its related to https://github.com/helm/helm/issues/4031
Jenkins X installs helm v2.10.0, which has this issue and it looks like its fixed in v2.11.0

How can we upgrade helm version in Jenkins X?

**Comment by jonathanbeber** [comment] 2018-10-20 10:41
same with version 2.11

```
❯ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.445
jenkins x platform 0.0.2771
Kubernetes cluster v1.10.7-gke.6
kubectl            v1.12.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.14.1
```

**Comment by bryanlarsen** [comment] 2018-10-22 14:57
The upgrade to 2.11 works for me when I manually run the step.

1. download helm 2.11
2. `helm init --upgrade`
3. cd charts/jxtest
4. `CHART_REPOSITORY=http://chartmuseum.jx.example.com jx step helm release`

The problem is that the helm binary in the `nodejs` container on my jenkins is still 2.10, even though my cluster has the 2.11 tiller.   How do I upgrade my container's helm client?

**Comment by VinodEgallapati** [comment] 2018-10-29 10:31
I am getting the same issue, though I upgrade helm to 2.11.0 in the container jenkinsxio/builder-go

I have done the below steps,

Downloaded jenkinsxio/builder-go image.
Downloaded helm 2.11.0 and performed the below steps,

wget https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz  | tar xzv && \
  mv linux-amd64/helm /usr/bin/ && \
  mv linux-amd64/tiller /usr/bin/ && \
  rm -rf linux-amd64

  helm init --client-only

And committed and tagged the docker image to use it for pipeline job

+ jx step helm release
Using helmBinary helm with feature flag: none
error: failed to build dependencies for chart from directory '.': failed to read the Helm version: failed to run 'helm version --short' command in directory '.', output: 'Client: v2.11.0+g2e55dbe
Error: forwarding ports: error upgrading connection: the server could not find the requested resource': exit status 1

Can you please help me with the fix.

**Comment by luca010** [comment] 2018-10-30 20:23
I had the same error. For some reason, I didn't have the global env TILLER_NAMESPACE configured. I setted it  to kube-system and now everything works fine.

**Comment by Marthijs-Berfelo** [comment] 2018-10-31 07:53
@luca010 : thanks for the hint. I solved the same error in our environment the same way!

**Comment by VinodEgallapati** [comment] 2018-11-01 13:46
Thank you for the hint,  I see some other error now,

+ jx step helm release
No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Using helmBinary helm with feature flag: none
error: failed to build dependencies for chart from directory '.': failed to add chart repositories: failed to retrieve the install charts: failed to list repositories: failed to run 'helm repo list' command in directory '.', output: 'Error: Couldn't load repositories file (/home/jenkins/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)': exit status 1

Using image jenkinsxio/builder-go , version: 0.1.33.

Is it due to helm version incompatibility between client and server.

**Comment by wangxiang5050** [comment] 2018-11-07 07:45
@VinodEgallapati I have the same error. Have you resolved it?

**Comment by ysaakpr** [comment] 2018-12-04 10:18
I had the same error. For some reason, I didn't have the global env TILLER_NAMESPACE configured. I setted it to kube-system and now everything works fine.

**Comment by M1123581E** [comment] 2018-12-21 03:43
jenkins configured global env TILLER_NAMESPACE but it doesn't work. so we need to configure it manually. is it a bug?

**Comment by sboardwell** [comment] 2019-01-17 19:53
I had the same problem. Adding `TILLER_NAMESPACE` to the Jenkinsfile environment block solved the problem. 

However, when I checked, the global variable was also empty. I've checked the helm chart and the `TILLER_NAMESPACE` is set everywhere. Really does seem like a bug. I will keep an eye on the global variable when updating. Has everyone else checked the global variable value?

**Comment by mbalaa-spring** [comment] 2019-02-11 19:28
For some reason `TILLER_NAMESPACE` was defined in our global Jenkins (X) config but it had no value; removing it solved this issue for us.

**Comment by polothy** [comment] 2019-02-15 16:31
We are experiencing the same problem.  Setting `TILLER_NAMESPACE` in our `Jenkinsfile` fixes it:
```
  environment {
    TILLER_NAMESPACE = "kube-system"
  }
```

Found two references to `TILLER_NAMESPACE` in the [jenkins-x-platform](https://github.com/jenkins-x/jenkins-x-platform) project:

https://github.com/jenkins-x/jenkins-x-platform/blob/e2819eea110d5936a489a00969667ba5b044db5a/values.yaml#L807

https://github.com/jenkins-x/jenkins-x-platform/blob/e2819eea110d5936a489a00969667ba5b044db5a/templates/jenkins-x-pod-templates.yaml#L78-L79

My gut says that's where it is coming from, but not 100% sure.  The odd thing is that it looks like Helm should be ignoring `TILLER_NAMESPACE` if it is empty:

https://github.com/helm/helm/blob/de5a6a931bfc47c1fa3a72db038002cbf68315ff/cmd/tiller/tiller.go#L238-L240

Anyways, it certainly is causing a problem for several people and for us.

**Comment by polothy** [comment] 2019-02-15 17:02
Just confirmed that if the `TILLER_NAMESPACE` env var is unset, then it also works.  I _think_ Jenkins protects env vars between step commands, so I had to do it in a single command, like so:
```
            sh 'unset TILLER_NAMESPACE && jx step helm build'
            sh 'unset TILLER_NAMESPACE && jx step helm apply'
```

**Comment by polothy** [comment] 2019-02-15 18:53
Proposed a fix in https://github.com/jenkins-x/jenkins-x-platform/pull/4864

**Comment by sboardwell** [comment] 2019-02-18 14:53
As a side note, perhaps having either 

1. an installation of the jenkins chart prior to [this commit](https://github.com/jenkins-x/charts/commit/fe5039faadb7c0c08fdb03388b9b80e175d69ec3) 
1. an older custom config map from a time prior to the commit

may be the root cause of the global variable `TILLER_NAMESPACE` being empty in Jenkins itself.

**Closed** 2019-02-22 17:42 UTC
Labels: area/helm, kind/bug, priority/important-soon

**Comment by LeoQuote** [comment] 2019-03-29 06:41
I got ``Error: Couldn't load repositories file (/home/jenkins/.helm/repository/repositories.yaml``

```
+ jx step helm release
No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080

error: failed to build dependencies for chart from directory '.': failed to add chart repositories: failed to retrieve the install charts: failed to list repositories: failed to run 'helm repo list' command in directory '.', output: 'Error: Couldn't load repositories file (/home/jenkins/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)'
```
jx version
```
jx                 1.3.1048
jenkins x platform 0.0.3657
Kubernetes cluster v1.13.3
kubectl            v1.13.3
helm client        v2.13.1+g618447c
helm server        v2.13.1+g618447c
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.2.1511 (Core)
```

**Comment by Qasim-Aziz** [comment] 2021-01-03 15:07
if any body have solution for this error 

WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file python-app-1-0.0.4.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 401 response: {"error":"unauthorized"}
error: Failed to post chart to http://jenkins-x-chartmuseum:8080/api/charts due to response 401: {"error":"unauthorized"}

Pipeline failed on stage 'from-build-pack' : container 'step-promote-helm-release'. The execution of the pipeline has stopped.

**Comment by KRams2019** [comment] 2021-03-05 04:55
@Qasim-Aziz  does your error got resolved, me also getting same error, 

WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file myjenkins-go-0.0.1.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 401 response: {"error":"unauthorized"}
error: Failed to post chart to http://jenkins-x-chartmuseum:8080/api/charts due to response 401: {"error":"unauthorized"}

Please help me out with this issues if anyone resolved this. 
@jstrachan
