### ISSUE TITLE
Pods deleted after adding Quickstart

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/jx#6318] opened 2019-12-10 13:33 UTC
### Summary 
Added quickstart to cluster.  Suddenly lost a bunch of pods (Deck, JX UI, Hooks).  Further investigation concluded they were deleted and confirmed by build log output.

https://gist.githubusercontent.com/deanesmith/977905d33855c43f4601eb8fda12281b/raw/c8fb7f03221efc3e9d4196b52c3c28bbc34107c6/build.log

Caveat here is that I am testing running Helm 2.16.1 locally, but total pod removal should not be a permitted side effect of that.

### Steps to reproduce the behavior
Added a quickstart to CJXD5 cluster.

### Expected behavior
Pods are not deleted

### Actual behavior
Pods are deleted

### Jx version
```
NAME               VERSION
jx                 2.0.1005-cjxd5-SNAPSHOT-66
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.13.11-dispatcher
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.1 build 19B88
```

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE

### Operating system / Environment
MAC OS Catalina

**Comment by abayer** [comment] 2019-12-10 13:44
Could be related to #6121, but it doesn't feel quite the same.

**Comment by tdcox** [comment] 2019-12-10 13:58
I have seen this happen when there are two concurrent builds running against a dev environment. I saw some discussion recently about updating Dev every time something was deployed in another environment, so if that has been implemented then we may be about to see a lot of disappearing jx installs due to this bug.

**Comment by deanesmith** [comment] 2019-12-10 17:19
@tdcox You're correct.  I noticed a hanging build in the JX UI at the same time I added a quickstart.

**Comment by deanesmith** [comment] 2019-12-10 18:22
This issue is recoverable by rerunning ```jx boot``` with the identical configuration.  I needed to reinstall my apps/addons

**Comment by deanesmith** [comment] 2020-01-23 00:21
I'm backing off the priority on this since the workaround is straightforward.

**Comment by daveconde** [comment] 2020-02-13 13:17
We believe this is a duplicate of #6167

**Closed by daveconde** 2020-02-13 13:17 UTC
Labels: area/helm, backlog, kind/bug, priority/critical
