### ISSUE TITLE
quickstarts fail to build if the project name != git repo name

### ISSUE THREAD

**Issue by mikecirioli** [jenkins-x/jx#2712] opened 2019-01-16 17:14 UTC
### Summary 
When creating a project whose `Project Name` != `git repo name`, the build will fail due to `jx` trying to checkout from a non-existent repo (ie. its using the `Project name`)
### Steps to reproduce the behavior
```
>$ jx create quickstart
? select the quickstart you wish to create golang-http
? Project name mikes golang test
Generated quickstart at /Users/mcirioli/go/src/github.com/jenkins-x/jx/mikes golang test
### NO charts folder /Users/mcirioli/go/src/github.com/jenkins-x/jx/mikes golang test/charts/golang-http
Created project at /Users/mcirioli/go/src/github.com/jenkins-x/jx/mikes golang test

? Which Git service do you wish to use https://github.com
No username defined for the current Git server!
? Do you wish to use mikecirioli as the Git user name: Yes
The directory /Users/mcirioli/go/src/github.com/jenkins-x/jx/mikes golang test is not yet using git
? Would you like to initialise git now? Yes
? Commit message:  Initial import

Git repository created
performing pack detection in folder /Users/mcirioli/go/src/github.com/jenkins-x/jx/mikes golang test
--> Draft detected Go (65.746753%)
selected pack: /Users/mcirioli/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/go
? Which organisation do you want to use? cb-kubecd
replacing placeholders in directory /Users/mcirioli/go/src/github.com/jenkins-x/jx/mikes golang test
app name: mikes-golang-test, git server: github.com, org: cb-kubecd, Docker registry org: cb-kubecd
skipping directory "/Users/mcirioli/go/src/github.com/jenkins-x/jx/mikes golang test/.git"
Using Git provider github.com at https://github.com


About to create repository mikes golang test on server https://github.com with user mikecirioli
? Enter the new repository name:  mike-golang42


Creating repository cb-kubecd/mike-golang42
Pushed Git repository to https://github.com/cb-kubecd/mike-golang42

Creating GitHub webhook for cb-kubecd/mike-golang42 for url https://hook.jx.jx.shared.dev.core.beescloud.com/hook

Watch pipeline activity via:    jx get activity -f mike-golang42 -w
Browse the pipeline log via:    jx get build logs cb-kubecd/mike-golang42/master
Open the Jenkins console via    jx console
You can list the pipelines via: jx get pipelines
When the pipeline is complete:  jx get applications

For more help on available commands see: https://jenkins-x.io/developing/browsing/

Note that your first pipeline may take a few minutes to start while the necessary images get downloaded!

k8s:(core-dev-1|racermud-shared-dev|jx)
```
Initial build of this project will fail: (partial build log output below).
```
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
[Pipeline] }
[Pipeline] // stage
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (CI Build and push snapshot)
Stage "CI Build and push snapshot" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Release)
[Pipeline] dir
Running in /home/jenkins/go/src/github.com/cb-kubecd/mikes-golang-test
[Pipeline] {
[Pipeline] git
Cloning the remote Git repository
Cloning repository https://github.com/cb-kubecd/mikes-golang-test.git
 > git init /home/jenkins/go/src/github.com/cb-kubecd/mikes-golang-test # timeout=10
Fetching upstream changes from https://github.com/cb-kubecd/mikes-golang-test.git
 > git --version # timeout=10
```
### Jx version

The output of `jx version` is:

```
>$ jx version
NAME               VERSION
jx                 1.3.719
jenkins x platform 0.0.3215
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.16.0
Operating System   Mac OS X 10.14.2 build 18C54
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Expected behavior

I can give my project a meaningful name that is different than the git repo name

### Actual behavior
my projects won't build because the git repo can't be cloned

**Comment by rawlingsj** [comment] 2019-01-16 17:18
this is a duplicate of https://github.com/jenkins-x/jx/issues/2699 - it's being worked on.  Closing.

**Closed by rawlingsj** 2019-01-16 17:18 UTC
