### ISSUE TITLE
For SCMs that are non-github, build logs cannot be fetched from CLI after pipeline run is complete

### ISSUE THREAD

**Issue by madhu1992blue** [jenkins-x/jx#6940] opened 2020-03-18 15:10 UTC
### Summary 
**After pipeline run is complete**, if the SCM is not github, the following error is received:

> error: there was a problem obtaining the log file from the github pages URL https://raw.githubusercontent.com/org/env-repo/gh-pages/jenkins-x/logs/org/env-repo/master/3.log: status 404 Not Found when performing GET on https://raw.githubusercontent.com/org/env-repo/gh-pages/jenkins-x/logs/org/env-repo/master/3.log

SCM base URL is incorrect for github pages URL. It is currently "https://raw.githubusercontent.com/org/env-repo/gh-pages/jenkins-x/logs/org/env-repo/master/3.log". The base URL, "**https://raw.githubusercontent.com**", is wrong. 

We noticed that pipelineactivity's **spec.buildLogsURL** field's value is incorrect. It has the wrong base URL, **https://raw.githubusercontent.com/**.

**We debugged further to notice that this code for non-github is hardcoded:**
**[https://github.com/jenkins-x/jx/blob/v2.0.1240/pkg/collector/git_collector.go#L166](https://github.com/jenkins-x/jx/blob/v2.0.1185/pkg/collector/git_collector.go#L166)**

### Steps to reproduce the behavior
Use SCM provider as Gitlab
Trigger a pipeline.
**Wait for the pipeline to complete.**
Then run `jx get build logs` and select the completed pipeline.

### Expected behavior
Should show logs.

### Actual behavior
error: there was a problem obtaining the log file from the github pages URL https://raw.githubusercontent.com/org/env-repo/gh-pages/jenkins-x/logs/org/env-repo/master/3.log: status 404 Not Found when performing GET on https://raw.githubusercontent.com/org/env-repo/gh-pages/jenkins-x/logs/org/env-repo/master/3.log

### Jx version
v2.0.1240

### Jenkins type
Serverless Jenkins X Pipelines (Tekton + Prow/Lighthouse)

### SCM 
Gitlab

**Comment by abayer** [comment] 2020-03-19 12:11
This is a duplicate of #6834

**Closed by abayer** 2020-03-19 12:11 UTC
