### ISSUE TITLE
Feature: Artifactory Documentation

### ISSUE THREAD

**Issue by cdenneen** [jenkins-x/jx#1464] opened 2018-08-10 17:41 UTC
Based on README and website I'd like to create this to track work on creating documentation for switching to Artifactory:

As mentioned here: https://jenkins-x.io/architecture/components/
2, 3, 4 should be able to be swapped out for Artifactory and how to do that would be worth having documentation on each:

- [ ] Replacing Nexus with Artifactory for binary repository
- [ ] Using Artifactory as Docker Registry
- [ ] Using Artifactory as Helm Chart Repository

I do not yet have any of these working or even a wip yet but wanted to created this for track just in case others have figured out what changes need to happen to make this a reality.

**Comment by pmuir** [comment] 2019-01-16 10:58
Dupe of #805

**Closed by pmuir** 2019-01-16 10:58 UTC
Labels: area/apps, kind/documentation, priority/important-soon
