### ISSUE TITLE
GC DNS records for preview environments when using external dns

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/jx#7394] opened 2020-06-25 11:27 UTC
### Summary 

Currently, the preview environment DNS records are not cleared down when the PR environment is removed.  We have nearly 8,000 on tekton weasel.

Can external dns be configured to remove entries that it doesn't need anymore?

**Comment by deanesmith** [comment] 2020-06-29 12:54
Duplicate of https://github.com/jenkins-x/jx/issues/7395

**Closed by deanesmith** 2020-06-29 12:54 UTC
