### ISSUE TITLE
jx preview image missing

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#353] opened 2018-03-05 17:22 UTC
> Using:
> NAME        VERSION
> jx          1.0.118
> Jenkins X   0.0.261
> Kubernetes  v1.7.12-gke.1
> Helm Client v2.8.1+g6af75a8
> Helm Server v2.8.1+g6af75a8
> Git         git version 2.14.3 (Apple Git-98)

Actions:
Create a spring boot app and deploy.
Create a branch and link upstream.
Edit branch, commit and push upstream.
On GitHub, create a PR and allow to build successfully.
1. In the root of the branch folder structure, type 
```
➜  jx preview --pr 4
Release "jx-dvsjersey-deleteme06-pr-4" does not exist. Installing it now.
Error: no Chart.yaml exists in directory "/Users/terry/Documents/code/deleteme06"
Error: Command failed  helm upgrade jx-dvsjersey-deleteme06-pr-4 . --install --wait --namespace jx-dvsjersey-deleteme06-pr-4
error: exit status 1
```
2.  Change to charts folder and try again:
```
➜ cd charts/deleteme06
➜ jx preview --pr 4                                                          
Created environment dvsjersey-deleteme06-pr-4
Release "jx-dvsjersey-deleteme06-pr-4" does not exist. Installing it now.
NAME:   jx-dvsjersey-deleteme06-pr-4
LAST DEPLOYED: Mon Mar  5 17:05:04 2018
NAMESPACE: jx-dvsjersey-deleteme06-pr-4
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                                     TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)  AGE
jx-dvsjersey-deleteme06-pr-4-deleteme06  ClusterIP  10.39.252.9  <none>       80/TCP   2s

==> v1beta1/Deployment
NAME                                     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
jx-dvsjersey-deleteme06-pr-4-deleteme06  1        1        1           0          2s

==> v1/Pod(related)
NAME                                                      READY  STATUS             RESTARTS  AGE
jx-dvsjersey-deleteme06-pr-4-deleteme06-2658699288-3pwln  0/1    ContainerCreating  0         2s


NOTES:

Get the application URL by running these commands:

kubectl get ingress jx-dvsjersey-deleteme06-pr-4-deleteme06

error: ingresses.extensions "deleteme06" not found

```
3. Check pod status:
```
➜ k describe pod jx-dvsjersey-deleteme06-pr-4-deleteme06-2658699288-3pwln -n jx-dvsjersey-deleteme06-pr-4
Name:		jx-dvsjersey-deleteme06-pr-4-deleteme06-2658699288-3pwln
Namespace:	jx-dvsjersey-deleteme06-pr-4
Node:		gke-dvs-dev-10-default-pool-7ff02072-gn5d/10.154.0.4
Start Time:	Mon, 05 Mar 2018 17:05:04 +0000
Labels:		app=jx-dvsjersey-deleteme06-pr-4-deleteme06
		draft=draft-app
		pod-template-hash=2658699288
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"jx-dvsjersey-deleteme06-pr-4","name":"jx-dvsjersey-deleteme06-pr-4-deleteme06-265...
Status:		Pending
IP:		10.36.0.30
Created By:	ReplicaSet/jx-dvsjersey-deleteme06-pr-4-deleteme06-2658699288
Controlled By:	ReplicaSet/jx-dvsjersey-deleteme06-pr-4-deleteme06-2658699288
Containers:
  deleteme06:
    Container ID:	
    Image:		jenkinsx/deleteme06:dev
    Image ID:		
    Port:		8080/TCP
    State:		Waiting
      Reason:		ErrImagePull
    Ready:		False
    Restart Count:	0
    Limits:
      cpu:	500m
      memory:	512Mi
    Requests:
      cpu:		400m
      memory:		512Mi
    Liveness:		http-get http://:8080/actuator/health delay=60s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:8080/actuator/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5r24m (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-5r24m:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-5r24m
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----							-------------			--------	------			-------
  59s		59s		1	default-scheduler									Normal		Scheduled		Successfully assigned jx-dvsjersey-deleteme06-pr-4-deleteme06-2658699288-3pwln to gke-dvs-dev-10-default-pool-7ff02072-gn5d
  58s		58s		1	kubelet, gke-dvs-dev-10-default-pool-7ff02072-gn5d					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-5r24m" 
  58s		14s		3	kubelet, gke-dvs-dev-10-default-pool-7ff02072-gn5d	spec.containers{deleteme06}	Normal		Pulling			pulling image "jenkinsx/deleteme06:dev"
  57s		13s		3	kubelet, gke-dvs-dev-10-default-pool-7ff02072-gn5d	spec.containers{deleteme06}	Warning		Failed			Failed to pull image "jenkinsx/deleteme06:dev": rpc error: code = 2 desc = Error response from daemon: {"message":"repository jenkinsx/deleteme06 not found: does not exist or no pull access"}
  57s		0s		6	kubelet, gke-dvs-dev-10-default-pool-7ff02072-gn5d					Warning		FailedSync		Error syncing pod
  56s		0s		3	kubelet, gke-dvs-dev-10-default-pool-7ff02072-gn5d	spec.containers{deleteme06}	Normal		BackOff			Back-off pulling image "jenkinsx/deleteme06:dev"
```
4. Check Jenkins build for PR:
```
[DVSJersey_deleteme06_PR-4-X6GRCQ2FOJSLU7OCPPRT5FGDKBTJVBJAUT4OXNP4XM7OHTGTCVRQ] Running shell script
+ docker build -f Dockerfile.release -t 10.39.251.118:5000/jenkinsx/deleteme06:0.0.0-SNAPSHOT-PR-4-1 .
Sending build context to Docker daemon  17.67MB

Step 1/6 : FROM openjdk:8-jdk-alpine
 ---> 224765a6bdbe
Step 2/6 : ENV PORT 8080
 ---> Using cache
 ---> e797c7172301
Step 3/6 : EXPOSE 8080
 ---> Using cache
 ---> 58ba77938515
Step 4/6 : COPY target/*.jar /opt/app.jar
 ---> c673b1703892
Removing intermediate container 42f5f949a292
Step 5/6 : WORKDIR /opt
 ---> 642818be2df6
Removing intermediate container a2eea64d1fe7
Step 6/6 : CMD java -jar app.jar
 ---> Running in 9967a72df8f7
 ---> 95dfa8192862
EXITCODE   0Removing intermediate container 9967a72df8f7
Successfully built 95dfa8192862
[Pipeline] sh
[DVSJersey_deleteme06_PR-4-X6GRCQ2FOJSLU7OCPPRT5FGDKBTJVBJAUT4OXNP4XM7OHTGTCVRQ] Running shell script
+ docker push 10.39.251.118:5000/jenkinsx/deleteme06:0.0.0-SNAPSHOT-PR-4-1
The push refers to a repository [10.39.251.118:5000/jenkinsx/deleteme06]
13b1f2fa54ba: Preparing
685fdd7e6770: Preparing
c9b26f41504c: Preparing
cd7100a72410: Preparing
cd7100a72410: Layer already exists
685fdd7e6770: Layer already exists
c9b26f41504c: Layer already exists
13b1f2fa54ba: Pushed
0.0.0-SNAPSHOT-PR-4-1: digest: sha256:c12b0addea99d995c1b681acaa5ac08a6ecfa7f174530ba1bc53cff6535f84cd size: 1159
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Release)
Stage 'Build Release' skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to Environments)
Stage 'Promote to Environments' skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

Finished: SUCCESS
```
Looks like the build creates ```docker push 10.39.251.118:5000/jenkinsx/deleteme06:0.0.0-SNAPSHOT-PR-4-1``` but the preview is looking for ```jenkinsx/deleteme06:dev```?

**Comment by tdcox** [comment] 2018-03-05 17:49
That looks like a red herring. I've just tried testing by editing the deployment to change the image name to jenkinsx/deleteme06:0.0.0-SNAPSHOT-PR-4-1 and it can't find that either.
It seems to be in the docker-registry:

```
name | "jenkinsx/deleteme06"
tags |  
   0 | "0.0.0-SNAPSHOT-PR-1-1"
   1 | "0.0.3"
   2 | "0.0.0-SNAPSHOT-PR-2-1
   3 | "0.0.0-SNAPSHOT-PR-4-1"
   4 | "0.0.0-SNAPSHOT-PR-3-1"
   5 | "0.0.2"
   6 | "0.0.1"
   7 | "0.0.4"
```

**Comment by jtnord** [comment] 2018-11-27 11:49
@tdcox is this still reproducible with the latest jx versions?

**Comment by ccojocar** [comment] 2019-01-14 17:09
Closing this since this issue seems to be outdated.

**Closed by ccojocar** 2019-01-14 17:09 UTC
Labels: x-internal, x-triaged
