### ISSUE TITLE
Failed to start minikube cluster

### ISSUE THREAD

**Issue by bbarin** [jenkins-x/jx#471] opened 2018-03-22 08:32 UTC
Tried to remove minikube cache, however the message error is the same.
Below the trace details

Moving files into cluster...
E0322 05:31:07.639235    9626 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: /Users/barin/.minikube/cache/localkube/localkube-v1.9.4: open /Users/barin/.minikube/cache/localkube/localkube-v1.9.4: no such file or directory
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
E0322 05:31:07.640087    9626 util.go:161] EOF
Error: Command failed  minikube start --memory 4096 --cpus 3 --vm-driver hyperkit --extra-config apiserver.Authorization.Mode=RBAC
error creating cluster exit status 1

**Comment by gtseres** [comment] 2018-03-22 10:29
Doesn't this look like a `minikube` issue or an issue in your local env? If so, maybe the place to file the issue is the [minikube](https://github.com/kubernetes/minikube) repo.

**Comment by rawlingsj** [comment] 2018-03-22 10:33
Yeah I agree with @gtseres - it looks like a minikube issue.  It might be worth trying a hard reset before asking on the minikube repo:

```
minikube delete
rm -rf ~/.minikube
jx create cluster minikube
```

**Comment by bbarin** [comment] 2018-03-28 10:42
Minikube works fine when I start other containers, I've already tried to reset minikube and start over. By the way I'm using fedora.

**Comment by rawlingsj** [comment] 2018-03-28 10:44
What version of minikube are you running?  Might be worth updating to the latest and trying again if you're not already on v0.25.2

**Comment by ccojocar** [comment] 2019-01-14 16:44
@bbarin Do you still encounter this issue? Thanks

**Comment by ccojocar** [comment] 2019-02-20 08:42
@bbarin I am going to close this issue. It seems to be quite old and the requested details weren't provided.

**Closed by ccojocar** 2019-02-20 08:42 UTC
Labels: area/minikube, kind/bug, priority/awaiting-more-evidence
