### ISSUE TITLE
'jx upgrade platform' error: failed to run 'helm upgrade'

### ISSUE THREAD

**Issue by igdianov** [jenkins-x/jx#1620] opened 2018-09-10 02:50 UTC
### Summary 
Running `jx upgrade platform` on freshly installed Jx cluster using `myvalues.yaml` in `.jx` folder fails with the error:
```
error: failed to run 'helm upgrade --namespace  --values C:\Users\Igor\.jx\myvalues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '', output: 'Error: UPGRADE 
FAILED: timed out waiting for the condition': exit status 1                                                                                                                       
```
After that, all attempts to run `jx upgrade platform` fail with another error:

```
error: failed to run 'helm upgrade --namespace  --values C:\Users\Igor\.jx\myvalues.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '', output: 'Error: UPGRADE FAILED: no ServiceAccount with the name "jenkins-x-controller-workflow" found': exit status 1
```

After failed upgrade, the Jenkins admin password is reset to 'admin'

### Steps to reproduce the behavior

1. Install Jx platform with `jx install --provider=gke`
2. Run `jx upgrade platform`

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.237
jenkins x platform 0.0.2328
kubernetes cluster v1.10.7-gke.1
kubectl            v1.10.0
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0.windows.1
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
kubernetes cluster v1.10.7-gke.1

### Operating system / Environment
Windows 10 / Gitbash 2.18

### Expected behavior
`jx upgrade platform` successfully upgrades and retains existing Jenkins admin password

### Actual behavior
'jx upgrade platform' fails and the Jenkins admin password is reset to 'admin'

**Comment by ccojocar** [comment] 2019-02-20 10:55
@igdianov The issue is fixed when upgrading the platform. I am going to close it. Thanks

**Closed by ccojocar** 2019-02-20 10:55 UTC
Labels: area/upgrade, kind/bug, priority/important-soon
