### ISSUE TITLE
Error on Expose pod when promote to jx-production env with ISTIO

### ISSUE THREAD

**Issue by igsys** [jenkins-x/jx#2356] opened 2018-11-28 13:56 UTC
### Summary 

Expose pod gives ERROR during promotion to production environment with ISTIO auto-sidecar injection turned on

### Steps to reproduce the behavior
1) Install ISTIO
2) Enable ISTIO auto-sidecar injection on jx-production namespace
3) Envoy sidecar auto injected on all pods created in jx-production namespace
4) Promote "jx quickstart -l go" repo to jx-production
5) Expose Pod got ERROR (Reason: an extra sidecar is installed)

### Jx version
jx                 1.3.603

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Operating system / Environment
AWS with kops

### Expected behavior
Expose Pod should get only 1 container, instead of 2 containers (extra sidecar container)
Isitio auto sidecar injection Turned off with 
annotations: { "sidecar.istio.io/inject": "false" }

Reference:
https://istio.io/docs/setup/kubernetes/sidecar-injection/
** Plz read the policy section

**Comment by polothy** [comment] 2019-01-04 18:36
Dupe of https://github.com/jenkins-x/jx/issues/2570?

**Comment by ccojocar** [comment] 2019-01-16 09:53
Dup of #2570

**Closed by ccojocar** 2019-01-16 09:53 UTC
