### ISSUE TITLE
Error when running on existing kops cluster

### ISSUE THREAD

**Issue by sreenuyedavalli** [jenkins-x/jx#894] opened 2018-05-23 20:08 UTC
Followed [these instructions](https://jenkins-x.io/getting-started/install-on-cluster/) including updating kops config. Get the following error when trying to install with jx install --provider=aws

error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

Here is my jx version output:

jx version
WARNING: Failed to connect to kubernetes: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
NAME        VERSION
jx          1.2.77
kubectl     v1.10.0
helm client v2.9.1+g20adb27
helm server v2.9.1+g20adb27
git         git version 2.16.1

I'm attempting to install jenkins on an existing k8s cluster built with kops btw.

**Comment by biancajiang** [comment] 2018-06-07 20:28
I also hit this.  After 'jx uninstall' and 'helm uninstall jxing' (b/c jxing wasn't uninstalled").

**Comment by Raichel** [comment] 2018-06-20 17:34
@sreenuyedavalli have you find a solution?

**Comment by jstrachan** [comment] 2018-06-29 10:37
@sreenuyedavalli this had me totally stumped until @rgauss mentioned something similar that was `KUBECONFIG` related.

@sreenuyedavalli @Raichel do you have `$KUBECONFIG` defined and does it include multiple paths? If so this issue is a duplicate of #1169 and its been fixed - release should be out in an hour

**Comment by uchanbi** [comment] 2018-07-06 06:33
@jstrachan 
I  tried "jx install" command and I am also getting same error. I Installed  latest jx . But my current-context is empaty . Is there any relationship between below  error and current-context . My K8s cluster in AWS . 

"jx install error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory" 

kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []

jx --version
1.3.63

**Closed** 2019-08-03 03:12 UTC
Labels: area/AWS, area/create-cluster, kind/bug, lifecycle/rotten, priority/backlog
