### ISSUE TITLE
Promotion log error

### ISSUE THREAD

**Issue by amuniz** [jenkins-x/jx#2492] opened 2018-12-12 10:20 UTC
### Summary 

Promotion builds are logging an error:

```
error: upgrading helm chart '.': failed to run 'helm upgrade --namespace jx-staging --install --wait --force --timeout 600 --values values.yaml jx-staging .' command in directory '.', output: 'Error: UPGRADE FAILED: no Release with the name "amuniz-golang-0.0.2" found': exit status 1
```

The promotion finishes correctly (the app is promoted).

### Steps to reproduce the behavior

Just merge a PR on an app and wait for the logs of the promotion build to staging.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.594
jenkins x platform 0.0.3044
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.9.1
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.16.0
Operating System   Mac OS X 10.13.3 build 17D47
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE (`jx create terraform`)

**Comment by beebird** [comment] 2018-12-12 10:59
Looks like jx couldn't find the chart in your own chartmusem, how did you configure the project in ``environment-xxxx-staging`` repo?

**Comment by ccojocar** [comment] 2019-01-16 11:40
@amuniz Is this still an issue? Please could you provide more details how to reproduce it? Thanks

**Comment by ccojocar** [comment] 2019-02-20 09:06
@amuniz I am going to close this issue, since the requested details weren't provided. Thanks

**Closed by ccojocar** 2019-02-20 09:06 UTC
Labels: area/promote, kind/bug, priority/awaiting-more-evidence
