### ISSUE TITLE
Problem install on local gitlab

### ISSUE THREAD

**Issue by Scisci75** [jenkins-x/jx#1021] opened 2018-06-13 07:54 UTC
Hi, I've tried to install jx on local openshift cluster and local gitlab server.

the command that I've used was : jx install --provider=openshift --git-provider-url=http://xxxxxx -git-username=xxxxxx  --git-api-token=xxxxxx

during installation when the system try to create a new repository xxxxx/environment-takeryellow-staging an error occured

error: POST https://gitlab.com/V4/projects: 401 {message: 401 Unauthorized}

Why the system tray to connect on  public gitlab and not on local gitlab ?
Thanks
Mirko

**Comment by wwadge** [comment] 2018-06-13 10:06
Dupe of this, probably: 
https://github.com/jenkins-x/jx/issues/40

**Comment by jstrachan** [comment] 2018-06-15 07:09
could be related to https://github.com/jenkins-x/jx/issues/704

**Comment by Scisci75** [comment] 2018-06-15 08:19
Hi, is it not relate to #704
The config on gitAuth.yaml is correct.

During the install, the system show the correct url server but when it try to create the repository  the post was sent to  https://gitlab.com/V4/projects and not to local server.

Thanks
Mirko

**Comment by ccojocar** [comment] 2019-02-20 10:18
dup of #40

**Closed by ccojocar** 2019-02-20 10:18 UTC
Labels: area/gitlab, kind/bug, priority/important-longterm
