### ISSUE TITLE
No matching credentials found for index.docker.io, falling back on anoynmous

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-x/jx#850] opened 2018-05-20 14:20 UTC
When I create a Spring demo via jx, then trigger the pipeline build, but got some erors below:
`
[uxSuRen_jx-demo-test_master-QONLRYNGRI7FHZWG56YVWEZKPCJUM6LDFHCAEMOCNMRKIY7EVBJA] Running shell script
++ cat VERSION
+ export VERSION=0.0.3
+ VERSION=0.0.3
+ skaffold run -f skaffold.yaml
Starting build...
2018/05/20 14:16:22 No matching credentials found for index.docker.io, falling back on anoynmous
time="2018-05-20T14:16:40Z" level=warning msg="Error processing base image for onbuild triggers: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fopenjdk%3Apull&service=registry.docker.io: net/http: TLS handshake timeout. Dependencies may be incomplete."
Sending build context to Docker daemon  528.4kB
Sending build context to Docker daemon  9.441MB
Sending build context to Docker daemon  17.47MB

Step 1/8 : FROM openjdk:8-jdk-slim
EXITCODE   0Error: running skaffold steps: build: build step: running build for artifact: running build: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
Usage:
  skaffold run [flags]

Flags:
  -f, --filename string       Filename or URL to the pipeline file (default "skaffold.yaml")
  -h, --help                  help for run
  -p, --profile stringArray   Activate profiles by name
  -t, --tag string            The optional custom tag to use for images which overrides the current Tagger configuration
      --toot                  Emit a terminal beep after the deploy is complete

Global Flags:
  -v, --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")

[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Promote to Environments)
Stage 'Promote to Environments' skipped due to earlier failure(s)
`

**Comment by rentallect** [comment] 2018-05-21 22:15
I'm also seeing this problem:

```
+ skaffold run -f skaffold.yaml
Starting build...
2018/05/21 21:24:22 No matching credentials found for index.docker.io, falling back on anoynmous

```

Here is my "jx version" output:

```
NAME               VERSION
jx                 1.2.70
jenkins x platform 0.0.1038
kubernetes cluster v1.9.3
kubectl            v1.8.6
helm client        v2.9.0+gf6025bb
helm server        v2.9.0+gf6025bb
git                git version 2.17.0
```

**Comment by rentallect** [comment] 2018-05-23 11:45
I set myself up for "Hacking on JX", and will attempt to debug this. If you have any tips/pointers concerning where I might look first (since this is my first dive into the src code), that will be very helpful.

**Comment by ccojocar** [comment] 2018-07-05 10:08
@rentallect I am wondering if this is not fixed in the current skaffold version. It would be great if you could try to reproduce it with the current version of Jenkins X.

**Comment by c4p7-n30k** [comment] 2018-11-04 11:55
I am also seeing this error:
Starting build...
Building []...
2018/11/04 09:51:07 No matching credentials found for index.docker.io, falling back on anonymous
Sending build context to Docker daemon

FATA[0003] build step: building []: build artifact: running build: docker build: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=60260ea7d58b221d0dec7cc2a4e48651&target=&ulimits=null: creating docker context: getting relative tar paths: file pattern [build/libs/*.jar] must match at least one file
```
▶ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.508
jenkins x platform 0.0.2806
Kubernetes cluster v1.11.2-gke.9
kubectl            v1.10.7
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.19.1
```

**Comment by ccojocar** [comment] 2019-02-20 10:15
@LinuxSuRen I am going to close this issue. Please have a look at this doc  https://jenkins-x.io/architecture/docker-registry/#update-the-config-json-secret. Thanks

**Closed by ccojocar** 2019-02-20 10:15 UTC
Labels: area/build, kind/bug, priority/important-soon
