### ISSUE TITLE
Missing commit message and author in PA

### ISSUE THREAD

**Issue by romainverduci** [jenkins-x/jx#6728] opened 2020-02-12 09:38 UTC
### Summary 
controller_build fails to update PipelineActivity with author and commit message information

From the controller_build logs:
```
{"level":"info","msg":"[BuildInfo] Completing build info for PipelineActivity=your-org-dub-inc-master-5","time":"2020-02-12T09:15:20Z"}
{"level":"warning","msg":"Error completing build information: no pipeline git auth could be found","time":"2020-02-12T09:15:20Z"}
```

Looks like it could be related to this change: https://github.com/jenkins-x/jx/commit/64791d738d136f8cc9bfeb228721491d19090f3a#diff-456e90af6b74e1bf1636617e0936ccb1

### Steps to reproduce the behavior
1. Start a new pipeline
2. kubectl get pipelineactivity your-pipeline
3. Look for pullTitle and author fields

### Expected behavior
They should be populated

### Actual behavior
They are not

### Jx version
```
Romains-MacBook-Pro:~ romain$ jx version
NAME               VERSION
jx                 2.0.1139+cjxd.6
Kubernetes cluster v1.13.12-gke.25
kubectl            v1.16.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.1 (Apple Git-122.3)
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [*] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE

### Operating system / Environment

Unrelated

**Comment by romainverduci** [comment] 2020-02-12 09:39
Linked to the UI issue: https://github.com/cloudbees/jxui-frontend/issues/1191

**Comment by abayer** [comment] 2020-02-12 17:32
this was actually #6568 and was fixed a while ago - CJXD 6 just happened to get a `jenkins-x-platform` version from juuuuust before it was fixed.

**Comment by abayer** [comment] 2020-02-12 18:57
Closing as a duplicate of #6568 - we'll be handling getting the fix into a new CJXD release in an internal issue.

**Closed by abayer** 2020-02-12 18:57 UTC
Labels: area/activity, area/build, in progress, priority/critical
