### ISSUE TITLE
Preview link does not show up in github PR

### ISSUE THREAD

**Issue by srehmanproov** [jenkins-x/jx#6706] opened 2020-02-06 16:26 UTC
### Summary 
 Created PR on quickstart python repo, the environment exists but link on PR missing.
### Steps to reproduce the behavior
Create a PR on imported repo, python quick-start in this case.
PR built and available in a preview environment xxx-jenkinsxpipeline-pr-2
But there is no link to click on it. In Kubernetes there is link available to view the app.
### Expected behavior
Link should be on the PR so developer can have a look at app just deployed,
### Actual behavior
Only text added no link.
### Jx version
2.0.1180
The output of `jx version` is:
`NAME               VERSION
jx                 2.0.1180
Kubernetes cluster v1.13.11-gke.23
kubectl            v1.15.0
helm client        Client: v2.16.1+gbbdfe5e
git                2.25.0
Operating System   Mac OS X 10.15.2 build 19C57`
```
COPY OUTPUT HERE
```

### Jenkins type
Serverless

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE

**Comment by abayer** [comment] 2020-02-09 08:30
Duplicate of https://github.com/jenkins-x/jx/issues/6431

**Closed by abayer** 2020-02-09 08:30 UTC
