### ISSUE TITLE
External Secrets didn't remove when remove them from the application chart file

### ISSUE THREAD

**Issue by falsedlah** [jenkins-x/jx#8119] opened 2022-04-01 09:11 UTC
**issue**
When you add a secret.yaml file into the application chart, it gets deployed correctly and the secret will be present in that application namespace but when you remove the secret file and deploy it, you expect the secret will be removed from that namespace. Unfortunately, the secret is still there, even if you remove it manually it gets back. 

**Step to reproduce:**
 1. Use external secret storage (my case aws secrets manager)
 2. Add a secret file to your application, and deploy it. 
 3. The secret will be shown in the application's namespace 
 4. Delete the secret file and deploy the application 
 5. The secret will still show even the file was deleted. 
 
 **Workaround**
 1. Remove the secret manually from the external secret storage 
 2. Remove the secret manually by kubectl from the k8s

**Comment by msvticket** [comment] 2022-07-28 20:05
Duplicate of #8024
/close

**Closed** 2022-07-28 20:05 UTC
