### ISSUE TITLE
JX promote fails: staging environment PR is not auto merged

### ISSUE THREAD

**Issue by jeffkhull** [jenkins-x/jx#6020] opened 2019-11-04 10:35 UTC
### Summary 

In the `jx promote` step of the staging environment, JX fails to automatically merge the environment repository pull request. Thus, JX polls the PR status until it times out. If the PR is merged manually, the promote step completes successfully.

### Steps to reproduce the behavior

1. Create JX cluster with a static jenkins server and integrate with github
2. Promote an app commit to staging

### Expected behavior

JX automatically merges the staging environment PR.

### Actual behavior

The staging environment PR has to be merged manually.  Otherwise, promote times out after 1 hour.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.861
jenkins x platform 2.0.1441
Kubernetes cluster v1.15.2
kubectl            v1.16.2
helm client        Client: v2.15.0+gc244026
git                2.20.1
Operating System   Ubuntu 19.10
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X ] Classic Jenkins

### Kubernetes cluster

Minikube env't created with jx create cluster minikube

### Operating system / Environment

Ubuntu 19.10

**Comment by jeffkhull** [comment] 2019-11-04 10:39
Here are screenshots of the behavior in the Jenkins UI.

![image](https://user-images.githubusercontent.com/17109209/68115019-6d766980-fec5-11e9-8e4e-09d2f9724c20.png)
...
![image](https://user-images.githubusercontent.com/17109209/68115041-749d7780-fec5-11e9-8f33-6b46538ae9c3.png)

**Comment by patrickleet** [comment] 2019-11-04 18:40
there should be logs from the environment repo as well - what are they?

**Comment by jeffkhull** [comment] 2019-11-05 10:55
Hi @patrickleet.  So, the environment repo pipeline doesn't kick off until I manually merge the environment PR.  If I don't click the merge button manually, the application repo promotion times out after 1 hour, and the staging environment pipeline never runs.

**Comment by jeffkhull** [comment] 2019-11-05 11:05
These are the logs I get in the application pipeline after clicking the env repo PR merge button:

![image](https://user-images.githubusercontent.com/17109209/68202146-2655aa80-ff91-11e9-89d0-fbff1c2b68f9.png)

And here are the environment repo logs when the environment pipeline does kick off:

![image](https://user-images.githubusercontent.com/17109209/68202713-3457fb00-ff92-11e9-995c-2ae23fc739e2.png)
![image](https://user-images.githubusercontent.com/17109209/68202735-40dc5380-ff92-11e9-964a-9d25c3fdbb5f.png)

**Comment by patrickleet** [comment] 2019-11-05 17:28
> So, the environment repo pipeline doesn't kick off until I manually merge the environment PR.

Do you have something like branch protection preventing the env PR from automatically merging?

With that merge your release should have gone out - the auto-promotion portion of the pipeline failed.

**Comment by jeffkhull** [comment] 2019-11-06 11:00
Hey @patrickleet, no branch protection rules are turned on:

![image](https://user-images.githubusercontent.com/17109209/68292450-e1497b00-0059-11ea-90b3-c5293456a84c.png)

I'm not sure I understand your comment:

> With that merge your release should have gone out - the auto-promotion portion of the pipeline failed.

When I click the merge button manually in the environment repo, the promotion does succeed and the new version of the app is deployed.

Does it matter that I am triggering the pipeline manually from within the Jenkins UI?

Thank you for your help, btw.

**Comment by bnerDY** [comment] 2019-11-20 10:00
same issue. pull request on custom environment is not auto merged.

**Comment by srehmanproov** [comment] 2020-02-10 11:46
Same issue on gitHub though the PR is auto merged on staging repo but promotion to staging does not work:
```
Failed to query the Pull Request last commit status for https://github.com/****, 
WARNING: Could not find the service URL in namespace **-staging for names jenkinsxpipeline
```

**Comment by mdcsaenz** [comment] 2020-02-10 23:21
WARNING: Failed to query the Pull Request last commit status for https://github.com/****,

but it stays like this for 30 minutes (my timeout) and nothing occurs.

**Comment by wanare-2017** [comment] 2020-05-28 12:16
We are also facing same issue,  pull request on default and custom environment is not auto merged.

**Comment by deanesmith** [comment] 2020-05-28 12:35
@wanare-2017, are you using Jenkins static masters?

**Comment by wanare-2017** [comment] 2020-06-05 08:13
Yes, I have used Static Jenkins,

+ jx promote -b --all-auto --no-wait=true --timeout 1h --version 0.0.2
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app modules version 0.0.2 to namespace jx-dev1
WARNING:
Created Pull Request: http://ec2-X-X-X-X.us-east-2.compute.amazonaws.com/awanare/environment-jx-dev1/-/merge_requests/1
WARNING: Adding labels not supported on gitlab yet for repo awanare/environment-jx-dev1 issue 1 labels [updatebot]
Added label updatebot to Pull Request http://ec2-X-X-X-X.us-east-2.compute.amazonaws.com/awanare/environment-jx-dev1/-/merge_requests
/1
WARNING: Failed to query the Pull Request last commit status for http://ec2-X-X-X-X.us-east-2.compute.amazonaws.com/awanare/environme
nt-jx-dev1/-/merge_requests/1 ref d4baddd35e238ac66f64fc8929568002ff03852e could not find a status for repository 103 with ref d4baddd35e
238ac66f64fc8929568002ff03852e
WARNING: Failed to query the Pull Request last commit status for http://ec2-X-X-X-X.us-east-2.compute.amazonaws.com/awanare/environme
nt-jx-dev1/-/merge_requests/1 ref d4baddd35e238ac66f64fc8929568002ff03852e could not find a status for repository 103 with ref d4baddd35e
238ac66f64fc8929568002ff03852e
WARNING: Failed to query the Pull Request last commit status for http://ec2-X-X-X-X.us-east-2.compute.amazonaws.com/awanare/environme
nt-jx-dev1/-/merge_requests/1 ref d4baddd35e238ac66f64fc8929568002ff03852e could not find a status for repository 103 with ref d4baddd35e
238ac66f64fc8929568002ff03852e
Pull Request http://ec2-X-X-X-X.us-east-2.compute.amazonaws.com/awanare/environment-jx-dev1/-/merge_requests/1 is merged at sha e4508
073279e631f0ca6528b51490f570665090f
Pull requests are merged, No wait on promotion to complete

**Comment by hoaitang** [comment] 2020-06-11 02:13
I am having the same issue, the cause is the Pull Request pipeline of staging is Pending
But the Release build is running so when I do the merge manually, the promotion works.

Is there a way that we can check or make sure the Pull Request pipeline is triggered?

**Closed** 2020-08-10 04:05 UTC
Labels: area/jenkins, area/minikube, lifecycle/rotten, priority/awaiting-more-evidence
