### ISSUE TITLE
Install issue: GKE - why are my maven pods stuck in Pending state?

### ISSUE THREAD

**Issue by stevef1uk** [jenkins-x/jx#521] opened 2018-03-29 09:29 UTC
Just started again with a  new Google Kubernetes cluster.

Noticed maven pods in Pending Status:

maven-1vz3f                                      0/2       Pending   0          1m
maven-svb6l                                      0/2       Pending   0          1m
maven-vhtbb                                      0/2       Pending   0     

using get logs shows absolutely nothing for maven or jnlp

Noticed a couple of errors when using kubectl cluster-info dump

E0329 09:25:18.357742       1 reflector.go:205] github.com/rawlingsj/pipeline-controller/main.go:110: Failed to list *v1.Pipeline: pipelines.jenkins.io is forbidden: User "system:serviceaccount:jx:pipelinecontroller" cannot list pipelines.jenkins.io in the namespace "default": Unknown user "system:serviceaccount:jx:pipelinecontroller"

Basically, dead in the water!

**Comment by rawlingsj** [comment] 2018-03-29 09:52
I wonder if there's enough resources in the cluster.  Is this on GKE / AKS / your own kubernetes cluster etc?  
Also can you `kubectl describe` one of the pending build pods?

e.g.
```
kubectl describe pod maven-vhtbb
```

**Comment by jstrachan** [comment] 2018-03-29 11:43
`kubectl top node` may help too, to check there's enough compute and memory etc.

BTW the first time you create a cluster it can take a minute for builds to actually start on GKE; but should not be longer than that.

`jx logs jenkins` might help too in case there's bad stuff in the jenkins master pod log

**Comment by stevef1uk** [comment] 2018-03-29 12:39
Thanks guys I am recreating my cluster now and will edit this message to add any details.

**Comment by cloudbring** [comment] 2018-03-29 22:32
I'm doing some testing but, it looks like currently like `n1-standard-2` with  `(2 vCPUs, 7.5 GB memory)` is the minimum needed to get the demo working. It's really strange. Somehow if you have `n1-standard-1` it complains of too few CPU resources to build the basic `jx create spring -d web -d actuator` project.

The Jenkins slave won't run because it seems the maven slave pod needs at least 2 CPUs?

**Comment by ccojocar** [comment] 2019-01-14 17:38
The issue is the cluster size, which does not have enough resources to run Jenkins X, therefore I am closing this issue.

**Closed by ccojocar** 2019-01-14 17:38 UTC
