### ISSUE TITLE
nodes have insufficient iam rights to deploy docker container via skaffold on AWS

### ISSUE THREAD

**Issue by sekmarco** [jenkins-x/jx#1252] opened 2018-07-10 16:21 UTC
### Summary 
After a successful deployment of a spring boot application on jenkins-x via
>  `jx create spring -d web -d actuator`

the jenkins step encounters following error during the master build at the step
 ```Shell Script -- export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml --``` :

```time="2018-07-10T11:31:24Z" level=fatal msg="build step: pushing [604370441254.dkr.ecr.us-east-1.amazonaws.com/sekmarco/demo:0.0.1]: denied: User: arn:aws:sts::604370441254:assumed-role/nodes.aws1.cluster.k8s.local/i-01255404cb302b204 is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-east-1:604370441254:repository/sekmarco/demo"```
### Steps to reproduce the behavior
After a successful 
> `kops create cluster --name aws1.cluster.k8s.local --node-count 3 --authorization RBAC --zones 
us-east-1a,us-east-1b --yes`

preparation of the cluster along [jenkins-x documentation](https://github.com/jenkins-x/jx-docs/blob/master/content/getting-started/install-on-cluster.md)

installation of jenkins-x via `jenkins install --provider aws`
and deployment of a spring boot demo via
 `jx create spring -d web -d actuator` without any error.
The jenkins job will fail.
### Jx version
jx                 1.3.76
jenkins x platform 0.0.1722
kubernetes cluster v1.9.6
kubectl            v1.11.0
git                git version 2.15.2 (Apple Git-101.1)
### Kubernetes cluster provider / Version
AWS
### Expected behavior
The nodes should have the necessary IAM privileges for skaffold:
```
"ecr:InitiateLayerUpload",
"ecr:UploadLayerPart",
"ecr:CompleteLayerUpload",
"ecr:PutImage"
```
and the jenkins job succeeds
### Actual behavior
The nodes have insufficient IAM privilege and fail.

**Comment by jstrachan** [comment] 2018-07-11 08:29
BTW this regression happened as we switched to using ECR by default on EKS and AWS; we could disable the use of ECR on AWS and just use it on EKS to avoid this issue? Or we could try figure out how to fix up the policies of the nodes on kops

**Comment by sekmarco** [comment] 2018-07-11 09:22
I think the solution is to add via `kops edit` following lines:
```
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [""ecr:InitiateLayerUpload", "ecr:UploadLayerPart","ecr:CompleteLayerUpload","ecr:PutImage""],
          "Resource": ["*"]
        }
      ]
```
I will test it in 2 hours.

**Comment by jstrachan** [comment] 2018-07-11 11:57
@sekmarco ah great thx! Am just trying to see if I can default that into `jx create cluster aws`.

BTW I guess there's a typo there with the double quotes right? Should that be:
```yaml
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["ecr:InitiateLayerUpload", "ecr:UploadLayerPart","ecr:CompleteLayerUpload","ecr:PutImage"],
          "Resource": ["*"]
        }
      ]
```
rather than the `""""` at the beginning and end of the `Action` array

**Comment by jstrachan** [comment] 2018-07-11 12:00
@sekmarco btw do you have any ideas on this one too? #1256 - any help gratefully received!

**Comment by sekmarco** [comment] 2018-07-11 12:11
@jstrachan yes this was typo. I cannot discover the additional Policies ins AWS console. So I will run the complete tool again to verify that this will resolve the issue.
If this is not working, i will use the aws-cli. Manually setting these policies in the AWS konsole is resolves the issue.

**Comment by jstrachan** [comment] 2018-07-11 13:53
have a PR where this seems to be working fine btw!

**Comment by sekmarco** [comment] 2018-07-11 14:14
Very nice, mine is also working.

Maybe adding a Sid is helpful. Can discover everything 
```
spec:
  additionalPolicies:
    node: |
      [
        {
          "Sid": "kopsK8sECRwrite",
          "Effect": "Allow",
          "Action": ["ecr:InitiateLayerUpload", "ecr:UploadLayerPart","ecr:CompleteLayerUpload","ecr:PutImage"],
          "Resource": ["*"]
        }
      ]
```

**Comment by polothy** [comment] 2018-09-13 22:48
Getting this exact same error after doing `jx create cluster eks` and creating a project via `jx create quickstart`.  Any tips on how to fix?

**Comment by jstrachan** [comment] 2018-09-14 09:48
@polothy aha thanks for the update!

**Comment by polothy** [comment] 2018-09-17 16:46
Actually, once I sorted out the region problem, I still get the same error.

**Comment by polothy** [comment] 2018-09-17 20:54
Found a bug in `eksctl`, see https://github.com/weaveworks/eksctl/pull/216 for details/workarounds.

**Comment by ccojocar** [comment] 2019-02-20 10:25
@sekmarco I am going to close this issue since the original issue was fixed. Thanks

**Closed by ccojocar** 2019-02-20 10:25 UTC
Labels: area/AWS, area/install, kind/bug, priority/important-soon
