### ISSUE TITLE
No job killer in prow for knative builds

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#2811] opened 2019-01-22 19:49 UTC
### Summary 
Prow has code to cancel out of date jobs (jobs that are superceded by more recent code changes on a PR) but for some reason it's in plank only so doesn't get applied for knative builds.

Would be useful to add this.

**Comment by jstrachan** [comment] 2019-01-23 05:11
probably a duplicate of #2792

**Closed** 2019-08-03 16:25 UTC
Labels: area/prow, kind/bug, lifecycle/rotten, priority/important-soon
