### ISSUE TITLE
Tekton pipelines not properly loading version from version stream

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#4656] opened 2019-07-10 11:02 UTC
### Summary 
In our infra cluster you can't make it load a version of an image from the version stream.

It seems to use the pod templates to resolve the version, and the pod template is set to `jenkinsxio/builder-<name>:latest`

**Comment by abayer** [comment] 2019-07-10 11:41
This is, as it turns out, a dupe of #4615, though I’m not sure why it’s showing up in our infra cluster, since we’re running an old version of `pipelinerunner` there...

**Closed by abayer** 2019-07-10 11:41 UTC
Labels: area/tekton, kind/bug, priority/important-soon
