### ISSUE TITLE
Vault doesn't get upgraded by the jenkins x boot pipeline

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#6122] opened 2019-11-14 20:21 UTC
Even if the version stream specifies an upgrade it doesn't get applied

Note that when we enable this it will cause other problems...

**Comment by hferentschik** [comment] 2019-11-15 08:40
Is this not related or even a duplicate of #5867

**Comment by hferentschik** [comment] 2019-11-15 15:00
Closing this as a duplicate of #5867

**Closed by hferentschik** 2019-11-15 15:00 UTC
Labels: kind/bug, priority/critical-urgent
