### ISSUE TITLE
Tekton pipelines not starting

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/jx#3928] opened 2019-05-12 23:06 UTC
### Summary 

On a fresh install of `jx` in an existing GKE cluster, tekton pipelines are not starting. Judging from logs in the `jx` namespace, everything seems to be fine and I can see from the GitHub repository that webhooks trigger successfully.

Please let me know which info (e.g., logs, events) can help to debug the issue.

### Steps to reproduce the behavior

* Create a GKE cluster.
* Install nginx Ingress.

```bash
jx install --provider gke \
    --external-ip $LB_IP \
    --domain acme.com \
    --default-admin-password $JX_PASS \
    --ingress-namespace ingress-nginx \
    --ingress-deployment nginx-ingress-controller \
    --ingress-service ingress-nginx \
    --namespace cd \
    --no-tiller \
    --prow \
    --tekton \
    --batch-mode \
    --verbose

kubectl get pods -w
```

### Expected behavior

The output of `kubectl get pods` should return Pods used by Tekton pipeline runs.

### Actual behavior

The output of `kubectl get pods` does NOT return Pods used by Tekton pipeline runs.

### Jx version

```
NAME               VERSION
jx                 2.0.118
jenkins x platform 2.0.191
Kubernetes cluster v1.12.6-gke.10
kubectl            v1.14.0
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

macOS

**Comment by heroic** [comment] 2019-05-13 19:01
@vfarcic do you have pipelinerunner working? I had this issue yesterday. my install was missing pipelinerunner. re-install fixed it.

**Comment by sharepointoscar** [comment] 2019-05-14 19:58
@heroic I have the same issue, and reinstall does not fix it unfortunately.  In addition, in this version of `jx` another issue surfaced that actually prevents install. https://github.com/jenkins-x/jx/issues/3345
```
NAME               VERSION
jx                 2.0.119
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.14.0
git                git version 2.21.0
Operating System   Mac OS X 10.14.3 build 18D42
```

**Comment by jstrachan** [comment] 2019-05-14 20:06
@vfarcic does missing the LB IP + domain help?

**Comment by heroic** [comment] 2019-05-14 20:15
@sharepointoscar try using 2.0.118 to install. That worked for me yesterday. platform version 2.0.276

**Comment by EamonKeane** [comment] 2019-05-15 12:27
Having an issue with tekton pipelines too, this may be unrelated but will mention it here. Happens on 2.0.118 and 2.0.119.

>>>NAME               VERSION
jx                 2.0.118
Kubernetes cluster v1.12.7-gke.10
kubectl            v1.12.2
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14.4 build 18E215a

```{"level":"error","msg":"failed to apply Tekton CRDs: failed to create/update PipelineResource logistio-environment-jx-te-mast in namespace jx: failed to get PipelineResource logistio-environment-jx-te-mast with pipelineresources.tekton.dev \"logistio-environment-jx-te-mast\" not found after failing to create a new one: Internal error occurred: failed calling admission webhook \"webhook.tekton.dev\": Post https://tekton-pipelines-webhook.jx.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) failed to apply Tekton CRDs: failed to create/update PipelineResource logistio-environment-jx-te-mast in namespace jx: failed to get PipelineResource logistio-environment-jx-te-mast with pipelineresources.tekton.dev \"logistio-environment-jx-te-mast\" not found after failing to create a new one: Internal error occurred: failed calling admission webhook \"webhook.tekton.dev\": Post https://tekton-pipelines-webhook.jx.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"2019-05-15T12:13:13Z"}```

**Comment by vfarcic** [comment] 2019-05-15 15:37
@heroic `pipelinerunner` is running.

That there was an `jx` installation from a few months ago. I uninstalled it and tried installing it again. My best guess is that there is a left-over from the initial installation that was not removed with `jx uninstall`. Indeed, left-over CRDs were not removed so I opened #3962. I removed them manually and installed `jx` again but there is still no sign of tekton Pods being created even though Webhook from the repo is green.

I'll try @jstrachan recommendation to skip specifying LB IP and domain and report back what happens.

**Comment by vfarcic** [comment] 2019-05-15 15:48
@jstrachan I installed `jx` with LB IP and domain and there's still no difference. Is there a way to get a clue what's wrong? Any pointer where to look would be useful.

P.S. I can create a new cluster and avoid those problems but I guess that we'd lose the opportunity to find out what the issue is.

**Comment by chaoyangnz** [comment] 2019-06-24 11:09
Hav you solved? 

> Having an issue with tekton pipelines too, this may be unrelated but will mention it here. Happens on 2.0.118 and 2.0.119.
> 
> > > > NAME               VERSION
> > > > jx                 2.0.118
> > > > Kubernetes cluster v1.12.7-gke.10
> > > > kubectl            v1.12.2
> > > > git                git version 2.17.2 (Apple Git-113)
> > > > Operating System   Mac OS X 10.14.4 build 18E215a
> 
> `{"level":"error","msg":"failed to apply Tekton CRDs: failed to create/update PipelineResource logistio-environment-jx-te-mast in namespace jx: failed to get PipelineResource logistio-environment-jx-te-mast with pipelineresources.tekton.dev \"logistio-environment-jx-te-mast\" not found after failing to create a new one: Internal error occurred: failed calling admission webhook \"webhook.tekton.dev\": Post https://tekton-pipelines-webhook.jx.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) failed to apply Tekton CRDs: failed to create/update PipelineResource logistio-environment-jx-te-mast in namespace jx: failed to get PipelineResource logistio-environment-jx-te-mast with pipelineresources.tekton.dev \"logistio-environment-jx-te-mast\" not found after failing to create a new one: Internal error occurred: failed calling admission webhook \"webhook.tekton.dev\": Post https://tekton-pipelines-webhook.jx.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"2019-05-15T12:13:13Z"}`

**Comment by jstrachan** [comment] 2019-06-24 11:17
I saw that issue today; bouncing the tekton pods seemed to fix it

**Comment by EamonKeane** [comment] 2019-06-24 11:17
@chaoyangnz no, sorry. I didn't have time to debug so stuck with static master jenkins. Let me know if you find a resolution although I haven't tried again recently so it may not be reproduced.

**Comment by jstrachan** [comment] 2019-06-24 11:18
@vfarcic if you get issues with pipelines not being triggered there's usually a good error message in the `pipelinerunner` pod - or worst case maybe something in the `pipeline` pod

**Comment by chaoyangnz** [comment] 2019-06-24 11:23
OK. I raised an issue for that. it is so much frustrating to install Jenkins X these days. See so many open issues and the documentation like kidding, I suppose Jenkins X is far not production-ready. If someone wants to have a try, I definetely discourage them. 

> @chaoyangnz no, sorry. I didn't have time to debug so stuck with static master jenkins. Let me know if you find a resolution although I haven't tried again recently so it may not be reproduced.

**Comment by hferentschik** [comment] 2019-07-09 14:12
@vfarcic is your original problem solved? Trying to figure out what the next steps on this issue would be atm. Are you saying you cannot standup a cluster using Tekton?

**Comment by vfarcic** [comment] 2019-07-09 15:03
I haven't experienced the problem for a while now. You can close it unless there are others with the same issue.

**Comment by hferentschik** [comment] 2019-07-10 20:26
I'll close it. We can always reopen or even better create a new one with a bit more context.

**Closed** 2019-07-10 20:26 UTC
Labels: area/GKE, area/ng-pipeline, area/tekton, kind/bug, priority/critical-urgent

**Comment by tpoerio-argo** [comment] 2019-08-08 19:50
Hi all,

I'm seeing this same issue, at present.

I can open a new ticket, or update here.

I'm also using a GKE cluster.

```
$ kubectl apply -f task.yaml
Error from server (InternalError): error when creating "task.yaml": Internal error occurred: failed calling admission webhook "webhook.tekton.dev": Post https://tekton-pipelines-webhook.jx.svc:443/?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

If I can provide info to help troubleshoot, let me know.

**Comment by solsson** [comment] 2019-10-15 09:08
I'm having the same problem, on a fresh GKE `1.14.6-gke.13` cluster, after applying the 0.7.0 release.

**Comment by solsson** [comment] 2019-10-15 12:18
Resolved using the fix for port 8443 on GKE private clusters suggested in https://github.com/knative/serving/issues/4868 and documented since https://github.com/kubernetes/kubernetes/issues/79739#issuecomment-529623687
