### ISSUE TITLE
EKS nodes in NotReady state after 10 hours

### ISSUE THREAD

**Issue by jicowan** [jenkins-x/jx#1108] opened 2018-06-21 13:57 UTC
10 hours after installing `jx` on EKS, 2 of the 3 nodes in my cluster are in a NotReady state.  It doesn't appears as if the nodes are resource constrained, however there is an event when I describe the nodes in the NotReady state: 
```
Events:
  Type     Reason             Age                   From                                                    Message
  ----     ------             ----                  ----                                                    -------
  Warning  ContainerGCFailed  14s (x1011 over 17h)  kubelet, <internal_ip>.us-west-2.compute.internal  rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4196279 vs. 4194304)
```

There are also a lot of jobs in an error state too.

**Comment by jstrachan** [comment] 2018-07-12 19:49
I wonder if there's any information in the Cloud Formation console in AWS? btw are you using this command which seems to work pretty well https://jenkins-x.io/commands/jx_create_cluster_eks/

**Comment by vochicong** [comment] 2018-08-07 01:41
@jstrachan Creating a new cluster using the command `jx create cluster eks` you recommended didn't help.

**Comment by jstrachan** [comment] 2018-08-07 07:43
this seems to be an issue with EKS; sometimes nodes go `NotReady` - I'm not sure what to do about it on AWS; on other managed kubernetes clusters invalid nodes tend to get deleted + recreated. 

I raised this issue to see if we could add something to `eksctl` to try auto-restart failed nodes or something: https://github.com/weaveworks/eksctl/issues/143

any ideas welcome on how we can make EKS more solid (we never see this issue on GKE for example)

**Comment by vochicong** [comment] 2018-08-10 02:30
I found that after delete NotReady nodes and recreate new ones, sometimes the jenkins pod readiness probe failed with HTTP statuscode 503 and it is unhealthy forever.

```
$ kubectl describe po jenkins-675cf9cb46-mn7z6
Name:           jenkins-675cf9cb46-mn7z6
Namespace:      jx
Node:           ip-192-168-97-179.us-west-2.compute.internal/192.168.97.179
Start Time:     Fri, 10 Aug 2018 11:20:20 +0900
Labels:         app=jenkins
                chart=jenkins-0.10.29
                component=jenkins-x-jenkins-master
                heritage=Tiller
                pod-template-hash=2317957602
                release=jenkins-x
Annotations:    checksum/config=64d179f0a1871a3438877bbf8ee65d6bbbc6f5cc9d063382fdeec9bcc2e963dd
Status:         Running
IP:             192.168.75.25
Controlled By:  ReplicaSet/jenkins-675cf9cb46
Init Containers:
  copy-default-config:
    Container ID:  docker://a05127a8e05026648ac6b62fdd71ee3f26ed3a5437bbec31ead4fdffeacb440b
    Image:         jenkinsxio/jenkinsx:0.0.26
    Image ID:      docker-pullable://jenkinsxio/jenkinsx@sha256:f7463bbb3c3b2bc77d05e8d87fc988707686a72197c28faa743d019115affc56
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      /var/jenkins_config/apply_config.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 10 Aug 2018 11:20:58 +0900
      Finished:     Fri, 10 Aug 2018 11:20:58 +0900
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (rw)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkins-token-t9smn (ro)
Containers:
  jenkins:
    Container ID:  docker://25088d486fab6425cbc199f27efb1a39d580fc25f74a1a2cc607872bef28956c
    Image:         jenkinsxio/jenkinsx:0.0.26
    Image ID:      docker-pullable://jenkinsxio/jenkinsx@sha256:f7463bbb3c3b2bc77d05e8d87fc988707686a72197c28faa743d019115affc56
    Ports:         8080/TCP, 50000/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
      --argumentsRealm.roles.$(ADMIN_USER)=admin
    State:          Running
      Started:      Fri, 10 Aug 2018 11:20:59 +0900
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      200m
      memory:   256Mi
    Liveness:   http-get http://:8080/login delay=60s timeout=5s period=10s #success=1 #failure=10
    Readiness:  http-get http://:8080/login delay=10s timeout=5s period=10s #success=1 #failure=3
    Environment:
      DOCKER_REGISTRY:  <set to the key 'docker.registry' of config map 'jenkins-x-docker-registry'>  Optional: false
      JAVA_OPTS:        -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Djenkins.displayurl.provider=org.jenkinsci.plugins.blueoceandisplayurl.BlueOceanDisplayURLImpl
      JENKINS_OPTS:
      ADMIN_PASSWORD:   <set to the key 'jenkins-admin-password' in secret 'jenkins'>  Optional: false
      ADMIN_USER:       <set to the key 'jenkins-admin-user' in secret 'jenkins'>      Optional: false
    Mounts:
      /usr/share/jenkins/ref/secrets/ from secrets-dir (rw)
      /var/jenkins_config from jenkins-config (ro)
      /var/jenkins_home from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkins-token-t9smn (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  jenkins-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jenkins
    Optional:  false
  plugin-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  secrets-dir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  jenkins-home:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  jenkins
    ReadOnly:   false
  jenkins-token-t9smn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jenkins-token-t9smn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age   From                                                   Message
  ----     ------                  ----  ----                                                   -------
  Normal   Scheduled               3m    default-scheduler                                      Successfully assigned jenkins-675cf9cb46-mn7z6 to ip-192-168-97-179.us-west-2.compute.internal
  Warning  FailedAttachVolume      3m    attachdetach-controller                                Multi-Attach error for volume "pvc-efd5a8a2-96be-11e8-8b89-0a552faeccd2" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulMountVolume   3m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  MountVolume.SetUp succeeded for volume "secrets-dir"
  Normal   SuccessfulMountVolume   3m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  MountVolume.SetUp succeeded for volume "plugin-dir"
  Normal   SuccessfulMountVolume   3m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  MountVolume.SetUp succeeded for volume "jenkins-config"
  Normal   SuccessfulMountVolume   3m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  MountVolume.SetUp succeeded for volume "jenkins-token-t9smn"
  Normal   SuccessfulAttachVolume  3m    attachdetach-controller                                AttachVolume.Attach succeeded for volume "pvc-efd5a8a2-96be-11e8-8b89-0a552faeccd2"
  Normal   SuccessfulMountVolume   3m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  MountVolume.SetUp succeeded for volume "pvc-efd5a8a2-96be-11e8-8b89-0a552faeccd2"
  Normal   Pulling                 3m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  pulling image "jenkinsxio/jenkinsx:0.0.26"
  Normal   Pulled                  2m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  Successfully pulled image "jenkinsxio/jenkinsx:0.0.26"
  Normal   Created                 2m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  Created container
  Normal   Started                 2m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  Started container
  Normal   Pulled                  2m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  Container image "jenkinsxio/jenkinsx:0.0.26" already present on machine
  Normal   Created                 2m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  Created container
  Normal   Started                 2m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  Started container
  Warning  Unhealthy               2m    kubelet, ip-192-168-97-179.us-west-2.compute.internal  Readiness probe failed: HTTP probe failed with statuscode: 503
```

**Comment by htplbc** [comment] 2018-09-24 01:16
I was able to reproduce this issue and it seems to be caused by disk-space.

**Comment by htplbc** [comment] 2018-09-24 01:49
Looks like for me issue #1705 caused the volumes to fill up.

**Comment by hekonsek** [comment] 2018-09-24 09:35
I can confirm that the issue is result of https://github.com/jenkins-x/jx/issues/1705. This issue hits EKS clusters really hard as EKS uses a bit old Kubernetes version with this (https://github.com/kubernetes/kubernetes/issues/62382) bug. As a result any GC job error starts a loop which brings cluster down if you don't stop the job manually fast enough.

As #1705 has been fixed now, this error should not happen anymore.

**Closed** 2019-01-15 10:55 UTC
