### ISSUE TITLE
jx boot fails to install correctly using secretStorage: vault

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/jx#4684] opened 2019-07-11 14:07 UTC
### Summary 
When attempting to install with external-dns and vault for secret storage, the pipeline runs very slowly and eventually starts to report:

```
failed to create system vault in namespace jx due to wait for vault to be initialized and unsealed: reading vault health: Get http://jx-vault-d55.jx.kill-9.uk/v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: dial tcp: lookup jx-vault-d55.jx.kill-9.uk on 192.168.50.1:53: no such host
```
### Steps to reproduce the behavior
```
cluster:
  clusterName: d56
  environmentGitOwner: bootstrap-labs
  project: jx-mar19
  provider: gke
  zone: europe-west1-d
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: kill-9.uk
  externalDNS: true
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: local
storage:
  logs:
    enabled: true
    url: ""
  reports:
    enabled: true
    url: ""
  repository:
    enabled: true
    url: ""
```

This looks like it may be the old chestnut that vault needs a domain name but external-dns hasn't created any yet.

**Comment by pmuir** [comment] 2019-07-18 13:39
@daveconde is this one working now?

**Comment by renatoaraujoc** [comment] 2019-07-30 18:09
I can confirm this bug. Has anyone been able to successfully install JX Boot with Vault?

**Comment by sharepointoscar** [comment] 2019-08-21 03:26
It worked for me only when I used a custom domain, set `externalDNS:true` and enabled TLS as follows

```
ingress:
  domain: jx.sharepointoscar.com
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: me@sharepointoscar.com
    enabled: true
    production: true
kaniko: true
secretStorage: vault
```

**Comment by renatoaraujoc** [comment] 2019-08-21 03:28
@sharepointoscar this fails for me even on custom domains, weird...

**Comment by sharepointoscar** [comment] 2019-08-21 03:33
Sorry to hear that @renatoaraujoc .  I ran the `jx diagnose` and it looks like I have some version stream errors as well.

```
➜ jx diagnose
Running in namespace: jx
ERROR: Unable to get the Jenkins X Version
error: Command failed 'jx version --no-version-check': WARNING: Failed to find helm installs: running helm list --all --namespace : failed to run 'helm list --all --namespace ' command in directory '', output: 'Error: could not find tiller'
WARNING: Failed to get helm version: failed to run 'helm version --short' command in directory '', output: 'Client: v2.13.1+g618447c
Error: could not find tiller'
NAME               VERSION
jx                 2.0.598
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.3
git                2.21.0
Operating System   Mac OS X 10.14.3 build 18D42
WARNING: could not find a stable package version for git from /Users/omedina/.jx/jenkins-x-versions
For background see: https://jenkins-x.io/architecture/version-stream/
Please lock this version down via the command: jx step create version pr -k package -n git
error: package jx is on version 2.0.598 but the version stream requires version 2.0.404 exit status 1

```

and my vault operator pod keeps crashing

```
pod/vault-operator-5fbdfcdbc8-zsrng   0/1     ImagePullBackOff   0          3h19m
```

**Comment by ccojocar** [comment] 2019-09-05 14:38
I believe this is fixed in the latest version. Do you still experience this issue?

**Comment by ccojocar** [comment] 2020-01-23 09:51
@tdcox I am closing this since it was fixed.

**Closed by ccojocar** 2020-01-23 09:51 UTC
Labels: area/boot, kind/bug, priority/important-soon
