### ISSUE TITLE
Random error when get pod on pipeline step

### ISSUE THREAD

**Issue by jrx-sjg** [jenkins-x/jx#6059] opened 2019-11-08 09:57 UTC
### Summary 

Jenkins X returns an error on any random step of any random build. The error is like this:

![Captura de pantalla de 2019-11-08 10-46-25](https://user-images.githubusercontent.com/46709427/68467308-40ec8580-0216-11ea-8b7a-3bff4fdc2fdc.png)

or

![Captura de pantalla de 2019-11-08 10-55-50](https://user-images.githubusercontent.com/46709427/68467385-5d88bd80-0216-11ea-9ef0-2748139be42b.png)

### Steps to reproduce the behavior

The error is random, not easy to reproduce

### Expected behavior

The pipeline is executed properly.

### Actual behavior

The pipeline fails on a random step.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.927
jenkins x platform 2.0.1540
Kubernetes cluster v1.14.6
kubectl            v1.15.3
helm client        Client: v2.15.1+gcf1de4f
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS

```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [X] Classic Jenkins

### Kubernetes cluster

Digital Ocean Kubernetes service

### Operating system / Environment

Ubuntu 18.04 LTS

**Comment by hferentschik** [comment] 2019-11-12 13:24
Could you please provide some more context? How does the project look like? Do you have some more detailed build logs, etc. 

Anything really to be able to reproduce the issue.

**Comment by deanesmith** [comment] 2020-05-01 15:55
Hey, @jrx-sjg,

We are closing this issue because static Jenkins masters have been deprecated and removed from Jenkins X in favor of focusing on Tekton pipelines.

This blog has more information as to the reasons why: https://jenkins-x.io/blog/2020/03/11/tekton/

If you’d like to discuss this in more detail, please join our Jenkins X channels in the Kubernetes Slack and tag any of our product leadership (Deane Smith, Viktor Farcic, Ethan Jones, Dave Conde, James Rawlings, James Strachan) and we’d be happy to discuss further. 

If this is a surprise to you, consider joining the Jenkins X newsletter and other community channels to make sure that important notices like this always make it to you: https://jenkins-x.io/community/ https://jenkins-x.io/community/

**Closed by deanesmith** 2020-05-01 15:55 UTC
Labels: area/jenkins, lifecycle/rotten, priority/awaiting-more-evidence
