### ISSUE TITLE
jx boot exits with errors on existing k8 1.18.2

### ISSUE THREAD

**Issue by feczo** [jenkins-x/jx#7193] opened 2020-05-15 20:55 UTC
### Steps to reproduce the behavior
set provider: kubernetes in jx-requirements.yaml
run jx boot

### Expected behavior
clean install without errors

### Actual behavior
deployment.apps/tekton-pipelines-controller unchanged
unable to recognize "/tmp/helm-template-workdir-159820873/jenkins-x/output/namespaces/jx/env/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-159820873/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/chartmuseum/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "/tmp/helm-template-workdir-159820873/jenkins-x/output/namespaces/jx/env/charts/jenkins-x-platform/charts/heapster/templates/part0-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"'error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''

the system was partially installed, eg. I can access nexus-jx and hook-jx
yet to try if everything works, but its concerning that the installation did not finish cleanly

### Jx version

NAME               VERSION
jx                 2.1.37
Kubernetes cluster v1.18.2
kubectl            v1.13.2
helm client        2.12.2
git                2.17.1
Operating System   Ubuntu 18.04.2 LTS

### Kubernetes cluster

self-managed k8 with knative and tekton on gce as per below

https://kubernetes.io/docs/setup/production-environment/turnkey/gce/
https://knative.dev/docs/install/installing-istio/
https://knative.dev/docs/install/knative-with-operators/
kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

### Operating system / Environment

  Ubuntu 18.04.2 LTS

**Comment by ankitm123** [comment] 2020-05-16 10:38
@feczo v1.18.2 is not supported yet. See #6957. You can downgrade your cluster to K8s 1.15, and it should work.

**Comment by daveconde** [comment] 2020-05-18 12:35
duplicate of #6957

**Comment by ankitm123** [comment] 2020-05-18 14:05
@daveconde I think the versions jx supports should be documented, else we will have lot of duplicate tickets, wdyt? https://github.com/jenkins-x/jx-docs/issues/2746

**Comment by feczo** [comment] 2020-05-18 16:41
At least have jx boot to check the version of the cluster and display the known issue if the version is too high.

**Comment by ankitm123** [comment] 2020-05-31 10:07
@feczo can you try this: https://github.com/jenkins-x/jx/issues/6957#issuecomment-636336110

**Closed** 2020-10-28 12:05 UTC
Labels: area/kubernetes, kind/enhancement, lifecycle/rotten, priority/important-longterm, triage/duplicate
