### ISSUE TITLE
"jx get build logs" can include failed-but-auto-retried-by-Prow pipelines

### ISSUE THREAD

**Issue by abayer** [jenkins-x/jx#6061] opened 2019-11-08 10:46 UTC
There are a couple race conditions in Tekton that can result in a `PipelineRun` failing for no good reason. We've tweaked Prow to automatically retry in those scenarios, but you can still get errors running `jx get build logs` in batch mode with a report that there are multiple builds matching the filter. We should just exclude the fail-right-away-and-retry cases from `jx get build logs`.

**Comment by hferentschik** [comment] 2019-11-11 11:14
> There are a couple race conditions in Tekton that can result in a PipelineRun failing

Do you have any pointers to this? That does not really sound so good. Are we saying these are race conditions by design or are these bugs which are going to be fixed? In the latter case whatever we put into code now to mitigate this should maybe be marked as temporary.

**Closed** 2019-11-14 09:03 UTC
Labels: area/logs, area/pipeline, kind/bug, priority/important-soon
