### ISSUE TITLE
setting up AWS wildcard DNS for an ELB?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx#1256] opened 2018-07-11 06:57 UTC
We're super close to great EKS support in Jenkins X but we're stuck right now on setting up wildcard DNS on an AWS ELB so that:

`myapp.myns.elbid.us-west-2.elb.amazonaws.com` can map to the IP address of `dualstack.elbid.us-west-2.elb.amazonaws.com` so that it can be served up by an `Ingress` that points to the ELB along these lines:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  name: jenkins
  namespace: jx
spec:
  rules:
  - host: jenkins.jx.elbid.us-west-2.elb.amazonaws.com
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
```

So far I've tried creating an A or CNAME of `*` on the ELB host name using Alias `Yes` - then when that failed, with `No` and could never `nslookup / dig` any wildcard DNS names (e.g. looking up `foo.elbid.us-west-2.elb.amazonaws.com` or `foo.bar.elbid.us-west-2.elb.amazonaws.com`)

There must be some way to do this - anyone know how?

As a fallback we could switch to using path based ingress; so using host `elbid.us-west-2.elb.amazonaws.com` and then specifying a path in each `Ingress` resource - the downside is this then means every microservice deployed in kubernetes typically needs custom configuration to specify the path its deployed within - which adds lots of complexity and generally breaks most apps OOTB without lots of manual tweaks which would make AWS a much worse place to develop on k8s than AKS / GKE

**Comment by gabeduke** [comment] 2018-07-11 11:49
Just a note: we've noticed that it can take up to 20 minutes for a new elb to register with route 53.

**Comment by jstrachan** [comment] 2018-07-11 11:54
@gabeduke ah thanks! 

Have you ever managed to setup a wildcard sub domains on an ELB host via route 53? Just wondering if its even possible really - maybe I just need to wait an hour or two ;)

**Comment by gabeduke** [comment] 2018-07-11 12:35
Yes a wild card subdomain with either alias or cname will work as long as it's not the Apex record. We generally use the dns name that's generated by the elb until the route53 dns starts resolving. Also our TTL is quite short (around 5 minutes) and it still takes a while to register. The other thing to note is this only is an issue on elb creation.

**Comment by jstrachan** [comment] 2018-07-11 12:47
@gabeduke many thanks. I wonder what I'm doing wrong. I tried creating a CNAME alias for "*" and hours later it still doesn't resolve to a sub domain:

```
$ nslookup foo.ab3b4ed5d80e411e8875b06439f0e641-1796460012.us-west-2.elb.amazonaws.com
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find foo.ab3b4ed5d80e411e8875b06439f0e641-1796460012.us-west-2.elb.amazonaws.com: NXDOMAIN

$ dig ns foo.ab3b4ed5d80e411e8875b06439f0e641-1796460012.us-west-2.elb.amazonaws.com

; <<>> DiG 9.10.6 <<>> ns foo.ab3b4ed5d80e411e8875b06439f0e641-1796460012.us-west-2.elb.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 63233
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;foo.ab3b4ed5d80e411e8875b06439f0e641-1796460012.us-west-2.elb.amazonaws.com. IN	NS

;; AUTHORITY SECTION:
us-west-2.elb.amazonaws.com. 59	IN	SOA	ns-332.awsdns-41.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 60

;; Query time: 72 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jul 11 13:46:37 BST 2018
;; MSG SIZE  rcvd: 182

```

**Comment by jstrachan** [comment] 2018-07-11 12:47
@gabeduke you are using a `Hosted zone` to setup the route 53 CNAME alias right?

**Comment by gabeduke** [comment] 2018-07-11 12:58
@jstrachan I think I know what the issue is. I don't know that it's possible to use the ELB DNS name as an actual route53 record, it would have to be the target. So in your Hosted zone you would point `*.[zone name].com` at the target `ab3b4ed5d80e411e8875b06439f0e641-1796460012.us-west-2.elb.amazonaws.com`. Let me know if that helps!

**Comment by jstrachan** [comment] 2018-07-11 13:02
not sure what the `[zone name]` is as right now the zone domain name is the ELB domain name. Or do you mean we'd need to create a new hosted zone for a new DNS name? Basically am trying to do the smallest possible change to get Ingress working on AWS/EKS without requiring folks have a custom DNS name pre-registered with a registrar that they can use for ingress; was hoping to setup some kind of wildcard DNS with the existing ELB domain name.

**Comment by gabeduke** [comment] 2018-07-11 13:09
I was misunderstanding what you are trying to do. As far as I know `[zone name]` would have to be a public DNS zone in order to access externally. Unfortunately, I don't think you would be able to modify records in the AWS provided zone.

**Comment by fabiodouek** [comment] 2018-07-11 13:15
Hi @gabeduke , that's right, there is no way to add records for the out of the box ELB public DNS names. I agree with you, these names will need to be registered in Hosted Zone associated to the VPC. Would be great if there was an option to specify also a Route 53 Private Hosted Zone, as in some cases you might want to have a private cluster, with an internal Load Balancer rather than internet-facing.

**Comment by jstrachan** [comment] 2018-07-11 16:07
OK another option to look at is can we use an NLB with the nginx-ingress controller     https://aws.amazon.com/blogs/opensource/network-load-balancer-support-in-kubernetes-1-9/
 then we'd get a static IP address for the NLB then we can use that as the domain and use nip.io for wildcard DNS on AWS/EKS

**Comment by patrickleet** [comment] 2018-07-11 17:08
@jstrachan I saw this approach when I was trying to research yesterday as well. Saw this article but haven't gone through it yet, but maybe it's helpful: https://medium.com/ww-engineering/k8s-ws-aws-elb-nlb-5a23834d4f14

**Comment by jstrachan** [comment] 2018-07-12 12:09
tried an NLB then used one of its IP addresses; seemed to work first time on kops but never worked on EKS. So its probably time to chuck in the towel and go back to using the ELB host name and relative paths on the Ingress instead

**Comment by jstrachan** [comment] 2018-07-23 09:17
BTW the code should work right now for setting up the Route53 CNAME wildcard load balancer

**Comment by thienlh** [comment] 2018-10-30 07:49
Do we have any update on this issue? Is there a way to config a DNS instead of using *.nip.io? This is a deal breaker for us really 😢

**Comment by jstrachan** [comment] 2018-10-30 09:32
there's some docs here which we're hoping to publish on the AWS blog soon...

https://docs.google.com/document/d/1EgqGU3nrMTigPvfohNH7o0rHHZbGuoQbQ__KqhmQsUc/edit?usp=sharing

**Comment by stormmore** [comment] 2019-01-09 22:52
I know I have mentioned this, I still believe that is wrong to have to give Jenkins X a full wildcard domain. Why isn't the choice to use something like `external-dns` to actually configure the required addresses inside the cloud provider's DNS (e.g. Route53, etc.). It is has a lot of the cloud provider dns options covered including Google, Azure and interestingly enough even CoreDNS.

**Comment by jstrachan** [comment] 2019-01-10 07:19
external-dns sounds great to me - maybe we can create an addon for it?

**Comment by stormmore** [comment] 2019-01-10 08:10
That would be awesome if it could do away with the need for providing a wildcard domain, it would be even better.

**Closed** 2019-08-04 00:33 UTC
Labels: area/AWS, area/ingress, area/install, help wanted, kind/bug, lifecycle/rotten, priority/important-soon
