### ISSUE TITLE
Pipeline fails when creating quickstart or import project

### ISSUE THREAD

**Issue by ismaeIfm** [jenkins-x/jx#2516] opened 2018-12-14 20:25 UTC
### Summary 
If try to create a quickstart or import a project, the pipeline fails in the post stage with the same error:
![selection_006](https://user-images.githubusercontent.com/7130927/50025397-0a2cd180-ffab-11e8-8607-97cf8c5a4022.png)
Checking the build logs I got two exeptions:
 ```
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
Error when executing always post condition:
java.lang.IllegalArgumentException: Failed to prepare cleanWs step
```
AND
```
Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected

GitHub has been notified of this commit’s build result

org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: jenkins-x-chartmuseum
```
I copy the whole build log in Actual Behavior.
Thanks in advanced, I'm really new to jenkins x and jenkis, so if I'm doing something stupid please point me in the right direction.
 ### Steps to reproduce the behavior
```
jx create quickstart
```
(selecting python-http)

or (inside the git repo)
```
jx import
```
(I'm using a fork of this [repo](https://github.com/lvthillo/python-flask-docker))
### Jx version

The output of `jx version` is:

```
 NAME               VERSION
jx                 1.3.661
jenkins x platform 0.0.3036
Kubernetes cluster v1.12.3
kubectl            v1.13.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.7.4
Operating System   Ubuntu 16.04.5 LTS

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
Managed Kubernetes from DigitalOcean version 1.12.3. To install jenkins x I run the following command
```bash
jx install --provider=kubernetes
```

### Operating system / Environment
Ubuntu 16.04

### Expected behavior
Finish the pipeline.

### Actual behavior
The build logs outputs:
```
Started by user admin
Replayed #1
Connecting to https://api.github.com with no credentials, anonymous access
GitHub API Usage: Current quota has 51 remaining (6 under budget). Next quota of 60 in 46 min
Obtained Jenkinsfile from 11d21e184ff87fbd9e6efd4791c4ba3ad92dcb63
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor
Agent python-k5gsf is provisioned from template Kubernetes Pod Template
Agent specification [Kubernetes Pod Template] (jenkins-python): 
* [jnlp] jenkinsci/jnlp-slave:3.26-1-alpine(resourceRequestCpu: 100m, resourceRequestMemory: 128Mi)
* [python] jenkinsxio/builder-python:0.1.136(resourceRequestCpu: 400m, resourceRequestMemory: 512Mi, resourceLimitCpu: 2, resourceLimitMemory: 2048Mi)

Running on python-k5gsf in /home/jenkins/workspace/aeIfm_python-flask-docker_master
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/ismaeIfm/python-flask-docker.git
 > git init /home/jenkins/workspace/aeIfm_python-flask-docker_master # timeout=10
Fetching upstream changes from https://github.com/ismaeIfm/python-flask-docker.git
 > git --version # timeout=10
 > git fetch --no-tags --progress https://github.com/ismaeIfm/python-flask-docker.git +refs/heads/master:refs/remotes/origin/master
 > git config remote.origin.url https://github.com/ismaeIfm/python-flask-docker.git # timeout=10
Fetching without tags
Checking out Revision 11d21e184ff87fbd9e6efd4791c4ba3ad92dcb63 (master)
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/ismaeIfm/python-flask-docker.git # timeout=10
Fetching upstream changes from https://github.com/ismaeIfm/python-flask-docker.git
 > git fetch --no-tags --progress https://github.com/ismaeIfm/python-flask-docker.git +refs/heads/master:refs/remotes/origin/master
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 11d21e184ff87fbd9e6efd4791c4ba3ad92dcb63
Commit message: "Draft create"
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] cleanWs
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
Error when executing always post condition:
java.lang.IllegalArgumentException: Failed to prepare cleanWs step
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeDescribable(DSL.java:401)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:181)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor375.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:74)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.delegateAndExecute(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:133)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.runPostConditions(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:773)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:418)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:416)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.runPostConditions(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:772)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.runPostConditions(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:767)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.executePostBuild(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:744)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.replay(CpsStepContext.java:499)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:299)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:209)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeDescribable(DSL.java:399)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:181)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor375.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	... 33 more
Caused by: org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
	at org.jenkinsci.plugins.workflow.steps.StepDescriptor.checkContextAvailability(StepDescriptor.java:260)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:262)
	... 54 more

[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
 > git rev-list --no-walk 11d21e184ff87fbd9e6efd4791c4ba3ad92dcb63 # timeout=10

Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected


GitHub has been notified of this commit’s build result

org.jenkinsci.plugins.credentialsbinding.impl.CredentialNotFoundException: jenkins-x-chartmuseum
	at org.jenkinsci.plugins.pipeline.modeldefinition.model.CredentialsBindingHandler.forId(CredentialsBindingHandler.java:107)
	at org.jenkinsci.plugins.pipeline.modeldefinition.model.CredentialsBindingHandler$forId.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:482)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.callClosureForMapEntry(CpsDefaultGroovyMethods:5226)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2107)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:480)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:76)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(jar:file:/var/jenkins_home/plugins/pipeline-model-definition/WEB-INF/lib/pipeline-model-definition.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy:605)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.checkoutAndRun(jar:file:/var/jenkins_home/plugins/pipeline-model-extensions/WEB-INF/lib/pipeline-model-extensions.jar!/org/jenkinsci/plugins/pipeline/modeldefinition/agent/CheckoutScript.groovy:63)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:76)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by ismaeIfm** [comment] 2018-12-20 22:23
Also happens with the lastest version 1.13.1-do.1 of the managed Kubernetes of digitalocean

**Comment by ismaeIfm** [comment] 2018-12-21 21:43
FYI ALL compliance tests are passed with this config

**Comment by ccojocar** [comment] 2019-01-16 11:54
@ismaeIfm Which quickstart did you try? Does the Jenkins X installation run properly? Do you see any failures in Kubernetes? Try to run `kubectl get all -n jx`.

**Comment by ismaeIfm** [comment] 2019-01-21 19:17
I tried the python-http quickstart. Yes it seems that the Jenkins X installation is running properly And I don't see any failures:
```NAME                                                    READY   STATUS    RESTARTS   AGE
pod/jenkins-6679d864cd-t786q                            1/1     Running   0          21m
pod/jenkins-x-chartmuseum-67f75c4884-qf4b6              1/1     Running   0          32m
pod/jenkins-x-controllercommitstatus-668d7c6984-7wkr2   1/1     Running   0          21m
pod/jenkins-x-controllerrole-69884794fc-cjjf8           1/1     Running   0          32m
pod/jenkins-x-controllerteam-9bc4698f8-4lm2k            1/1     Running   0          21m
pod/jenkins-x-controllerworkflow-66c948658-n5nbf        1/1     Running   0          32m
pod/jenkins-x-docker-registry-589d4d79c4-m7zf8          1/1     Running   0          32m
pod/jenkins-x-heapster-c476795-jwbdz                    2/2     Running   0          21m
pod/jenkins-x-mongodb-5b9957c694-kdw6z                  1/1     Running   0          21m
pod/jenkins-x-monocular-api-98bcb4c68-56gkk             1/1     Running   4          32m
pod/jenkins-x-monocular-prerender-64fb689cfd-x6dmw      1/1     Running   0          32m
pod/jenkins-x-monocular-ui-7f65d9c75c-2j8gt             1/1     Running   0          32m
pod/jenkins-x-nexus-69df7696c5-bjxq4                    1/1     Running   0          21m

NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/heapster                        ClusterIP   10.245.90.226    <none>        8082/TCP    32m
service/jenkins                         ClusterIP   10.245.6.6       <none>        8080/TCP    32m
service/jenkins-agent                   ClusterIP   10.245.42.51     <none>        50000/TCP   32m
service/jenkins-x-chartmuseum           ClusterIP   10.245.134.227   <none>        8080/TCP    32m
service/jenkins-x-docker-registry       ClusterIP   10.245.69.121    <none>        5000/TCP    32m
service/jenkins-x-mongodb               ClusterIP   10.245.27.216    <none>        27017/TCP   32m
service/jenkins-x-monocular-api         ClusterIP   10.245.34.146    <none>        80/TCP      32m
service/jenkins-x-monocular-prerender   ClusterIP   10.245.139.32    <none>        80/TCP      32m
service/jenkins-x-monocular-ui          ClusterIP   10.245.112.250   <none>        80/TCP      32m
service/nexus                           ClusterIP   10.245.87.162    <none>        80/TCP      32m

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jenkins                            1/1     1            1           32m
deployment.apps/jenkins-x-chartmuseum              1/1     1            1           32m
deployment.apps/jenkins-x-controllercommitstatus   1/1     1            1           32m
deployment.apps/jenkins-x-controllerrole           1/1     1            1           32m
deployment.apps/jenkins-x-controllerteam           1/1     1            1           32m
deployment.apps/jenkins-x-controllerworkflow       1/1     1            1           32m
deployment.apps/jenkins-x-docker-registry          1/1     1            1           32m
deployment.apps/jenkins-x-heapster                 1/1     1            1           32m
deployment.apps/jenkins-x-mongodb                  1/1     1            1           32m
deployment.apps/jenkins-x-monocular-api            1/1     1            1           32m
deployment.apps/jenkins-x-monocular-prerender      1/1     1            1           32m
deployment.apps/jenkins-x-monocular-ui             1/1     1            1           32m
deployment.apps/jenkins-x-nexus                    1/1     1            1           32m

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/jenkins-6679d864cd                            1         1         1       32m
replicaset.apps/jenkins-x-chartmuseum-67f75c4884              1         1         1       32m
replicaset.apps/jenkins-x-controllercommitstatus-668d7c6984   1         1         1       32m
replicaset.apps/jenkins-x-controllerrole-69884794fc           1         1         1       32m
replicaset.apps/jenkins-x-controllerteam-9bc4698f8            1         1         1       32m
replicaset.apps/jenkins-x-controllerworkflow-66c948658        1         1         1       32m
replicaset.apps/jenkins-x-docker-registry-589d4d79c4          1         1         1       32m
replicaset.apps/jenkins-x-heapster-c476795                    1         1         1       32m
replicaset.apps/jenkins-x-mongodb-5b9957c694                  1         1         1       32m
replicaset.apps/jenkins-x-monocular-api-98bcb4c68             1         1         1       32m
replicaset.apps/jenkins-x-monocular-prerender-64fb689cfd      1         1         1       32m
replicaset.apps/jenkins-x-monocular-ui-7f65d9c75c             1         1         1       32m
replicaset.apps/jenkins-x-nexus-69df7696c5                    1         1         1       32m

NAME                                   SCHEDULE         SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/jenkins-x-gcactivities   0/30 */3 * * *   False     0        <none>          32m
cronjob.batch/jenkins-x-gcpods         0/30 */3 * * *   False     0        <none>          32m
cronjob.batch/jenkins-x-gcpreviews     0 */3 * * *      False     0        <none>          32m
```

**Comment by sonyali03** [comment] 2019-01-26 00:17
same issue here with jx 1.3.809. I compared with my previous successful log and found the previous version has username and token when connecting to https://api.github.com, but the failed one Connecting to https://api.github.com with no credentials, anonymous access.

**Comment by BrainCell23** [comment] 2019-01-27 15:39
I have also had an identical problem with the quickstart golang and spring-boot-rest-prometheus examples. I have tried to import a Python Flask project using [this tutorial](https://itnext.io/deploy-a-basic-python-application-using-jenkins-x-kubernetes-4adace2fe345)

The problem seems the same in all cases. 

I can see the Jenkins running on its endpoint (I am using nip.io) The staging and production environments are showing Bright sunshine, but each application I try to build shows Thundercloud status. 

Interestingly Jenkins is reporting that the last successful build was within the last 10 minutes, and when I check for further detail Jenkins is reporting that it has not detected any remote changes.

**Comment by apeckys** [comment] 2019-01-30 15:28
I think this is related to this - https://issues.jenkins-ci.org/browse/JENKINS-54278

I have removed the cleanWs() from the post actions and the error goes away. 

Looks like a bug in 0.36 of the plugin

**Comment by ismaeIfm** [comment] 2019-01-31 02:10
@apeckys sorry to bother, but removing cleanWs() changes in some way the expected behavior?

**Comment by ccojocar** [comment] 2019-02-20 09:07
@ismaeIfm I am going to close this issue since the problem is in the Jenkins plugin not in jx.

**Closed by ccojocar** 2019-02-20 09:07 UTC
Labels: area/build, area/jenkins, area/quickstart, kind/bug, priority/awaiting-more-evidence
