### ISSUE TITLE
 Failed to create devpod namespace on Windows 10

### ISSUE THREAD

**Issue by igdianov** [jenkins-x/jx#967] opened 2018-06-04 21:14 UTC
[Create a DevPod](https://jenkins-x.io/developing/devpods/#creating-a-devpod) on Windows 10 with `jx create devpod --label=maven` command fails with the following error message:
```
error: Failed to create Namespace jx-edit-machine-user Namespace "jx-edit-machine-user" is invalid: metadata.labels: Invalid value: "machine\\user": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

$ jx version
```
NAME               VERSION
jx                 1.2.100
jenkins x platform 0.0.1175
kubernetes cluster v1.10.0
kubectl            v1.10.3
helm client        v2.9.1+g20adb27
helm server        v2.9.1+g20adb27
git                git version 2.9.0.windows.1
```

**Comment by adamsmith448** [comment] 2018-06-11 12:29
I think this duplicates #823 (I'm having the same issue on Windows 10).

**Comment by rawlingsj** [comment] 2018-12-07 00:31
@igdianov did you username have special chars in it?  It is sounding like a duplicate of #823 as @adamsmith448 suggests, can you confirm please?

/kind bug
/triage duplicate

**Comment by igdianov** [comment] 2018-12-08 20:06
@jstrachan Here is the output of `jx create devpod` without `--username` attribute in Gitbash on Windows 10. 
```
Igor@m6800 MINGW64 
$ jx create devpod 
? Pick which kind of DevPod you wish to create:  jx-base
error: Failed to create Namespace jx-edit-m6800-igor Namespace "jx-edit-m6800-igor" is invalid: metadata.labels: Invalid value: "m6800\\Igor": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

jx version:

```
$ jx version
NAME               VERSION
jx                 1.3.632
jenkins x platform 0.0.2902
Kubernetes cluster v1.11.2-gke.18
kubectl            v1.13.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.18.0.windows.1
Operating System   Windows 10 Pro 1803 build 17134
```

**Closed** 2019-08-03 04:13 UTC
Labels: area/devpod, area/windows, kind/bug, lifecycle/rotten, priority/backlog, triage/duplicate
