### ISSUE TITLE
Ask for CloudProvider during install

### ISSUE THREAD

**Issue by Larzack** [jenkins-x/jx#5817] opened 2019-10-15 08:19 UTC
### Summary 

When I do `jx boot` the default provider is `GCP`. When I want to install with `EKS` or `IKS` the install process stop. I have to edit the `requirements.yaml` file and change `gcp` to my provider then restart `jx boot`

Maybe you should ask before for the provider 

### Jx version

The output of `jx version` is:

MBP-JM:~ jmorgado$ jx version
NAME               VERSION
jx                 2.0.861
Kubernetes cluster v1.14.7+IKS
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.14.6 build 18G95

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

IKS , EKS , AKS

### Operating system / Environment

OS X 10.14.6

**Comment by abayer** [comment] 2019-10-22 12:11
Dupe of #5754

**Closed by abayer** 2019-10-22 12:11 UTC
Labels: area/boot, kind/enhancement
