### ISSUE TITLE
Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://chartmuseum.build.cd.jenkins-x.io/index.yaml: dial tcp 35.205.186.189:443: connect: operation timed out': exit status 1

### ISSUE THREAD

**Issue by matakan** [jenkins-x/jx#2100] opened 2018-10-26 16:31 UTC
### Summary 

When I try to install jenkins-X into my existing AKS cluster, I am getting this error

### Steps to reproduce the behavior

It is happening when I ran "jx install --provider=aks ...."

### Jx version

The output of `jx version` is:
$ jx version
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.482
Kubernetes cluster v1.11.3
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.1 (Apple Git-112)

### Kubernetes cluster
AKS

What kind of Kubernetes cluster are you using & how did you create it?
over terraform

**Comment by pmuir** [comment] 2018-10-26 17:07
Dupe of #2099. Apologies, we have an outage at the moment. We are working to get the server back.

**Closed by pmuir** 2018-10-26 17:07 UTC

**Comment by garethjevans** [comment] 2019-01-17 20:47
@RajeshAjjarapu http://chartmuseum.jenkins-x.io is a HA google storage bucket, do you have any network config/issues that would stop you from accessing google storage?

**Comment by RajeshAjjarapu** [comment] 2019-01-17 21:45
Thanks for responding Gareth.   I am checking network config settings, proxy etc..

**Comment by RajeshAjjarapu** [comment] 2019-01-17 21:51
past that error. It's my proxy/network setting on my terminal.  Will post if I run into further issues.  Greatly appreciate quick response!!

**Comment by siddharthkaushal90** [comment] 2019-08-30 09:14
Hi @garethjevans I am trying to install jenkins-x on GKE, everything works fine but while installing jenkins-x platform helm chart its is throwing below error:

Installing Jenkins X platform helm chart from: /root/.jx/cloud-environments/env-gke
Adding missing helm repo: jenkins-x https://chartmuseum.build.cd.jenkins-x.io
error creating cluster failed to add the jenkinx-x helm repo: failed to add the repository 'jenkins-x' with URL 'https://chartmuseum.build.cd.jenkins-x.io': failed to run 'helm repo add jenkins-x https://chartmuseum.build.cd.jenkins-x.io' command in directory '', output: 'Error: Looks like "https://chartmuseum.build.cd.jenkins-x.io" is not a valid chart repository or cannot be reached: Get https://chartmuseum.build.cd.jenkins-x.io/index.yaml: dial tcp 35.205.186.189:443: connect: connection timed out.
Can you please help me in this issue.

Thanks

**Comment by s50600822** [comment] 2020-03-05 12:21
> @RajeshAjjarapu http://chartmuseum.jenkins-x.io is a HA google storage bucket, do you have any network config/issues that would stop you from accessing google storage?

Are there verbose logging anywhere to help identify this?

**Comment by sandyrayala** [comment] 2020-07-31 06:18
> proxy/network setting on my terminal.

Hi , I am facing a similar error , can u please tell me ,what settings have to be configured

**Comment by Qasim-Aziz** [comment] 2020-12-17 07:30
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
error: failed to add chart repositories: failed to add Helm repository 'http://chartmuseum.jenkins-x.io': prompting for creds for http://chartmuseum.jenkins-x.io: checking status code of http://chartmuseum.jenkins-x.io/index.yaml: Get http://chartmuseum.jenkins-x.io/index.yaml: EOF
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''

installing jenkins x with GKE thorugh jenkinx documentation
