### ISSUE TITLE
error: strconv.Atoi: parsing "$BUILD_ID": invalid syntax

### ISSUE THREAD

**Issue by rawlingsj** [jenkins-x/jx#2532] opened 2018-12-18 12:22 UTC
Looks like `gcactivities` are having an issue on the the latest prow based builds:

```
kubectl logs jenkins-x-gcactivities-1545134400-xpgn5
error: strconv.Atoi: parsing "$BUILD_ID": invalid syntax
```

@garethjevans does this seem related to the BUILD_ID stuff from last week?
/bug
/garethjevans

**Comment by garethjevans** [comment] 2018-12-18 13:11
@rawlingsj I think this is caused by bad data in the pipeline activity records.  I think I should be able to remove them manually and it should recover.  Would be interested to see if its affecting anyone else.

**Comment by garethjevans** [comment] 2018-12-18 13:12
`kubectl get pipelineactivities | grep build-id`

These are the offending records

**Comment by garethjevans** [comment] 2018-12-18 14:42
Closing this as pods are starting correctly now

**Closed by garethjevans** 2018-12-18 14:42 UTC
Labels: kind/bug
