### ISSUE TITLE
`jx install` fails to configure docker registry on EKS

### ISSUE THREAD

**Issue by faucherb94** [jenkins-x/jx#5841] opened 2019-10-16 15:14 UTC
### Summary

I'm trying to install a new instance of Jenkins X on an EKS cluster. I'm using the same process I've been using for months that's been working fine, but now I'm encountering a cryptic error.

### Steps to reproduce the behavior

1. `jx install --provider=eks --no-default-environments --git-provider-url=*** --static-jenkins`
1. 'No' to wildcard DNS
1. 'Yes' to wait for IP resolution
1. 'Yes' to magic DNS name
1. Configure git options

### Expected behavior

Install completes successfully

### Actual behavior

```
WARNING: unable to calculate docker registry values - parsing the current Kubeernetes context kubernetes: unable to parse kubernetes as <cluster_name>.<region>.*
```

happens immediately after starting `jx install`, and

```
error: configuring the docker registry: configure cloud provider docker registry: parsing the current Kubeernetes context kubernetes: unable to parse kubernetes as <cluster_name>.<region>.*
```

happens right after finishing git server configuration.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.876
Kubernetes cluster v1.13.11-eks-5876d6
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.23.0
Operating System   Ubuntu 16.04.6 LTS
```

also tested on

```
NAME               VERSION
jx                 2.0.876
Kubernetes cluster v1.13.11-eks-5876d6
kubectl            v1.15.1
helm client        Client: v2.12.3+geecf22f
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKS via custom creation scripts

### Operating system / Environment

Ubuntu 16.04 and macOS 10.14.6

**Comment by rousl4n** [comment] 2019-10-17 15:42
same here... @jstrachan

**Comment by rousl4n** [comment] 2019-10-18 09:04
after investigation I confirm that the issue is linked to the jx version. I rolled back and it works fine again

**Comment by rousl4n** [comment] 2019-10-18 09:11
working version v2.0.860

**Comment by andrewhertog** [comment] 2019-10-21 19:08
I'm having the same issue. Also seeing it with `jx boot`

### jx version
```
NAME               VERSION
jx                 2.0.893
Kubernetes cluster v1.14.7-eks-e9b1d0
kubectl            v1.16.1
helm client        Client: v2.13.1+g618447c
git                2.23.0
Operating System   Mac OS X 10.14.5 build 18F132
```

**Comment by faucherb94** [comment] 2019-10-21 21:25
Thanks @rousl4n for confirming it's an issue with the CLI. A workaround I figured out is just to use the `--docker-registry` flag.

**Comment by andrewhertog** [comment] 2019-10-23 19:30
#5845  Is a possible fix for this

**Closed** 2019-10-30 21:42 UTC
Labels: area/eks, area/fox, backlog, kind/bug, priority/critical

**Comment by hack19-hub** [comment] 2019-11-01 10:21
Im too getting same error with JX version 2.0.933

error: configuring the docker registry: configure cloud provider docker registry: parsing the current Kubeernetes context arn:aws:eks:us-west-2:823024120868:cluster/jenkins: unable to parse arn:aws:eks:us-west-2:823024120868:cluster/jenkins as <cluster_name>.<region>.*
