### ISSUE TITLE
jx create spring fails on first build

### ISSUE THREAD

**Issue by agentgonzo** [jenkins-x/jx#2416] opened 2018-12-05 09:25 UTC
### Summary 
I did a `jx create spring` and selected `web` from the possible spring options.
It started building the master branch, but failed at the end with

### Steps to reproduce the behavior
`jx create spring`

### Jx version
1.3.615

The output of `jx version` is:

```
NAME               VERSION
jx                 ?[32m1.3.615?[0m
Kubernetes cluster ?[32mv1.9.7-gke.11?[0m
kubectl            ?[32mv1.10.3?[0m
helm client        ?[32mv2.11.0+g2e55dbe?[0m
helm server        ?[32mv2.11.0+g2e55dbe?[0m
git                ?[32mgit version 2.15.1.windows.2?[0m
Operating System   ?[32mWindows 10 Pro 1809 build 17763?[0m

```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
GKE, `jx create terraform`

### Operating system / Environment
Windows

### Expected behavior
The first build of my jx create spring project succeeds

### Actual behavior
it fails at the end of the build with 
```
The push refers to a repository [10.43.249.244:5000/cb-bugbash-windows/demo]
d643d193ea6c: Preparing
2016044ff2b2: Preparing
9f89204fd3b0: Preparing
1219c65bb75a: Preparing
12bc6638f550: Preparing
6f9340f5323e: Preparing
9ea63cdbc429: Preparing
ef68f6734aa4: Preparing
6f9340f5323e: Waiting
9ea63cdbc429: Waiting
ef68f6734aa4: Waiting
12bc6638f550: Pushed
2016044ff2b2: Pushed
9f89204fd3b0: Pushed
6f9340f5323e: Pushed
9ea63cdbc429: Pushed
d643d193ea6c: Pushed
ef68f6734aa4: Pushed
1219c65bb75a: Pushed
0.0.1: digest: sha256:920b7eac0c88c324dd5816e1e8d5f446603ea4d961dd2add2a16c1adfc81e86c size: 1994
Build complete in 24.152949362s
changeme -> 10.43.249.244:5000/cb-bugbash-windows/demo:0.0.1
[Pipeline] sh
[job] Running shell script
+ cat VERSION
+ jx step post build --image 10.43.249.244:5000/cb-bugbash-windows/demo:0.0.1
no CVE provider running in the current jx namespace so skip adding image to be analysed[Pipeline] }
[Pipeline] // stage
[Pipeline] stage```

**Comment by romainverduci** [comment] 2018-12-05 13:52
This is a duplicate of https://github.com/jenkins-x/jx/issues/2288

**Closed** 2018-12-05 13:53 UTC
Labels: kubecd-imported, kubecd-triaged
