### ISSUE TITLE
Can't use user as org during jx create addon cloudbees --sso

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx#1769] opened 2018-09-25 09:39 UTC
### Summary 

If you select a user as an org during the `jx create addon cloudbees --sso` then you get an error when you try to login using github saying (something like) 'User data cannot be retrieved'.

### Steps to reproduce the behavior

Select a user (rather than a real org) at the question:

```
? Select GitHub organizations to authorize users from:
```

And then complete the install. Then try to log in to the web UI using GitHub.

### Jx version

The output of `jx version` is:

✔ pmuir:~ ➭ jx version
Using helmBinary helm, with noTiller false
NAME               VERSION
jx                 1.3.310
jenkins x platform 0.0.2544
kubernetes cluster v1.9.7-gke.6
kubectl            v1.11.2
helm client        v2.10.0+g9ad53aa
helm server        v2.10.0+g9ad53aa
git                git version 2.18.0

### Kubernetes cluster

GKE

### Expected behavior

The user accounts shouldn't appear in the org list if they don't work.

**Comment by ccojocar** [comment] 2018-09-26 05:35
I think this is a duplicate of #1771. We will filter out the non orgs from the prompted list when the `sso` addon is created.

**Comment by pmuir** [comment] 2018-09-26 08:03
Actually they are different. #1771 refers to the fact that you can select NO entries from the list (i.e. the result of running the command can be a list of orgs of length 0) and proceed (wheras for anything to work you need to select at least one). #1769 refers to the fact you can select a non-org from the list.

**Closed** 2018-09-27 08:14 UTC
Labels: kubecd
