### ISSUE TITLE
Refactor jenkins-x.yaml pipeline types in to a dedicated go module

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/jx#7199] opened 2020-05-18 09:16 UTC
### Summary 

The types needed to walk a jenkins-x.yaml file are currently scattered in a few different packages in jenkins-x/jx. This means that for developers to be able to write code that loads and manipulates a pipeline they must import all of the jx repository in to their project. 

Extracting the pipeline types and utility functions in to a dedicated library would make it easier for developers to be able to write apps that work with the pipeline. It would also make it easier to understand and reason about the pipeline model.

Acceptance Criteria:
- A new jenkins-x/pipelines go library is created on github
- config.ProjectConfig, systax.* and all associated types are moved in to the new project above
- jenkins-x/jx is updated to use the new library
- Utility code for reading, writing and manipulating the pipeline is moved to the new library
- The new library has a minimum of 80% code coverage

**Comment by hferentschik** [comment] 2020-05-18 09:35
Sounds like a duplicate of #4627. WDYT?

**Comment by hferentschik** [comment] 2020-05-18 09:37
> Extracting the pipeline types and utility functions in to a dedicated library would make it easier for developers to be able to write apps that work with the pipeline. It would also make it easier to understand and reason about the pipeline model.

+1, unfortunately, a simple move of relevant packages will still pull in a lot of jx. There needs to be some refactoring as well to make sure that the exported API is self-contained.

**Comment by daveconde** [comment] 2020-05-18 09:46
> > Extracting the pipeline types and utility functions in to a dedicated library would make it easier for developers to be able to write apps that work with the pipeline. It would also make it easier to understand and reason about the pipeline model.
> 
> +1, unfortunately, a simple move of relevant packages will still pull in a lot of jx. There needs to be some refactoring as well to make sure that the exported API is self-contained.

Yep thats basically what I saw, I tried to move them around and saw lots of the other dependencies that were needed, we'll need a bit of a refactor also.

**Closed** 2020-10-15 14:05 UTC
Labels: area/pipeline, kind/task, lifecycle/rotten, priority/important-soon
