### ISSUE TITLE
Unable to configure git during installation

### ISSUE THREAD

**Issue by cortopy** [jenkins-x/jx#3799] opened 2019-04-29 16:16 UTC
### Summary 

When I try to install Jenkins X in existing cluster, the script errors when trying to configure git

### Steps to reproduce the behavior

```
jx install \
--git-username=user-bot \
--environment-git-owner=MyOrg \
--git-private=true \
--provider=aws \
--domain=domain.example \
--helm-tls=true \
--ng=true \
--aws-s3-bucket=my-bucket \
--aws-s3-region=eu-west-1 \
--aws-kms-key-id=some-id \
--aws-kms-region=eu-west-1 \
--aws-secret-access-key=some-secret
```

I've also tried providing no git options and different combinations of git options, with the same result

### Expected behavior
It installs correctly 

### Actual behavior

I get the following error:

```
error: configuring the git auth: creating the git auth config service: wait for vault to be initialized and unsealed: reading vault health: Get /v1/sys/health?drsecondarycode=299&performancestandbycode=299&sealedcode=299&standbycode=299&uninitcode=299: unsupported protocol scheme ""
```

### Jx version
`jx version` actually hangs, but my version is 2.0.66-1

### Jenkins type

- [x] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster

AWS EKS

### Operating system / Environment

Linux Manjaro

**Comment by jstrachan** [comment] 2019-04-30 05:29
does supplying `--git-api-token=whatever` help?

**Comment by Wizofgoz** [comment] 2019-05-03 20:19
I'm having this issue as well and got the same error after trying your suggestion. Here's the command I tried:
```sh
jx install \
--provider eks \
--aws-access-key-id REDACTED \
--aws-kms-key-id REDACTED \
--aws-kms-region us-west-2 \
--aws-s3-bucket REDACTED \
--aws-s3-region us-west-2 \
--aws-secret-access-key REDACTED \
--default-admin-password REDACTED \
--domain REDACTED \
--environment-git-owner REDACTED \
--git-private \
--git-provider-url https://github.com \
--ng \
--git-api-token REDACTED
```

**Comment by Wizofgoz** [comment] 2019-05-06 19:08
Also tried specifying a DynamoDB as well. Below is my most recently tried command:
```sh
jx install \
--provider eks \
--aws-access-key-id REDACTED \
--aws-kms-key-id REDACTED \
--aws-kms-region us-west-2 \
--aws-s3-bucket REDACTED \
--aws-s3-region us-west-2 \
--aws-secret-access-key REDACTED \
--aws-dynamodb-region us-west-2 \
--aws-dynamodb-table REDACTED \
--default-admin-password REDACTED \
--domain REDACTED \
--environment-git-owner REDACTED \
--git-private \
--git-provider-url https://github.com \
--ng \
--git-api-token REDACTED \
--git-username Wizofgoz \
--register-local-helmrepo
```

**Comment by Wizofgoz** [comment] 2019-05-06 20:31
It looks like a vault resource is being created with an invalid name. Here's an excerpt from the vault pod logs:

```json
{"level":"error","ts":1557173962.1832447,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"vault-controller","request":"jx/jx-vault-something.us-west","error":"failed to create service: Service \"jx-vault-something.us-west\" is invalid: metadata.name: Invalid value: \"jx-vault-something.us-west\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')","stacktrace":"github.com/banzaicloud/bank-vaults/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by Wizofgoz** [comment] 2019-05-06 22:51
@jstrachan I was able to work around the issue by renaming the kube context and the user and cluster it uses to not have periods (`.`) in them but ran into another issue. It looks like it tried to use Kaniko when it was not specified in the command I used. Below is an excerpt from the output of jx install:
```shell
Lets set up a Git user name and API token to be able to perform CI/CD

? Do you wish to use Wizofgoz as the local Git user for GitHub server: Yes
Select the CI/CD pipelines Git server and user
? Do you wish to use GitHub as the pipelines Git server: Yes
Setting the pipelines Git server https://github.com and user name Wizofgoz.
Saving the Git authentication configuration
Current configuration dir: /Users/user/.jx
versionRepository: https://github.com/jenkins-x/jenkins-x-versions.git git ref: 
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /Users/user/.jx/jenkins-x-versions
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Compressing objects: 100% (10/10), done.
Total 1270 (delta 0), reused 7 (delta 0), pack-reused 1260
Current configuration dir: /Users/user/.jx
options.Flags.CloudEnvRepository: https://github.com/jenkins-x/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /Users/user/.jx/cloud-environments
? A local Jenkins X cloud environments repository already exists, recreate with latest? Yes
Current configuration dir: /Users/user/.jx
options.Flags.CloudEnvRepository: https://github.com/jenkins-x/cloud-environments
options.Flags.LocalCloudEnvironment: false
Cloning the Jenkins X cloud environments repo to /Users/user/.jx/cloud-environments
Enumerating objects: 1382, done.
Total 1382 (delta 0), reused 0 (delta 0), pack-reused 1382
error: unable to generate the Kaniko configuration: Kaniko is not supported for eks provider
```

**Comment by Wizofgoz** [comment] 2019-05-06 23:30
@jstrachan I found the offending line: https://github.com/jenkins-x/jx/blob/f6b077a56e403fb431ed9b317fa8c850379c925b/pkg/jx/cmd/install.go#L408

I'm not sure if that's intended behavior but it's not documented in the install command. I'll try another install with Kaniko disabled and report back.

**Comment by ccojocar** [comment] 2020-01-23 09:18
Closing this since now the recommended way to install Jenkins X is boot instead of `install -ng` which is deprecated.

**Closed by ccojocar** 2020-01-23 09:18 UTC
Labels: area/eks, area/git, kind/bug, priority/important-soon
