### ISSUE TITLE
ELB target group health checks fails with unhealthy

### ISSUE THREAD

**Issue by ypto** [jenkins-x/jx#3124] opened 2019-02-15 17:51 UTC
### Summary 

Brand new deployment of Jenkin X and EKS results on not finalizing jenkins x installation.
Two days ago, i did a full deployment and worked without an issue. Today, i deleted the entire deployment, and tried to do a new one and failed. Tried to deploy in a different region as well. (first deployment was on eu-west-1 and second on eu-central-1)

```
Configure Jenkins API Token

retrying after error:checking health of Jenkins server "http://jenkins.jx.domain.com": pinging Jenkins server "http://jenkins.jx.domain.com/login": executing ping request against URL "http://jenkins.jx.domaian.com/login": Get http://jenkins.jx.domain.com/login: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Nodes are active, and working correctly inside Kubernetes. nginx ingress has the correct elb endpoint.

The only thing failing is the target group getting both nodes as unhealthy on the port expose by nginx ingress. (in my case was 31164).

### Steps to reproduce the behavior

jx create eks

Choices:

No existing ingress controller found in the kube-system namespace, shall we install one? Yes

Select Jenkins installation type: Static Master Jenkins

Pick workload build pack:  Kubernetes Workloads: Automated CI+CD with GitOps Promotion

### Expected behavior

Complete installation and get url to access Jenkins.

### Actual behavior

retrying after error:checking health of Jenkins server "http://jenkins.jx.domain.com": pinging Jenkins server "http://jenkins.jx.yptogroup.com/login": executing ping request against URL "http://jenkins.jx.domain.com/login": Get http://jenkins.jx.domain.com/login: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

retrying after error:checking health of Jenkins server "http://jenkins.jx.domain.com": pinging Jenkins server "http://jenkins.jx.domain.com/login": executing ping request against URL "http://jenkins.jx.yptogroup.com/login": Get http://jenkins.jx.domain.com/login: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

error: configuring Jenkins: creating Jenkins API token: after 3 attempts, last error: checking health of Jenkins server "http://jenkins.jx.domain.com": pinging Jenkins server "http://jenkins.jx.domain.com/login": executing ping request against URL "http://jenkins.jx.domain.com/login": Get http://jenkins.jx.domain.com/login: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 1.3.879
jenkins x platform 0.0.3402
Kubernetes cluster v1.11.5-eks-6bad6d
kubectl            v1.13.3
helm client        v2.12.3+geecf22f
helm server        v2.12.3+geecf22f
git                git version 2.17.1 (Apple Git-112)
Operating System   Mac OS X 10.13.6 build 17G2208
```

### Jenkins type

- [x] Classic Jenkins

### Kubernetes cluster

EKS
jx create eks 

### Operating system / Environment

macOS 10.13.6 (17G2208)

**Comment by ypto** [comment] 2019-02-18 10:41
Mark this issue to be deleted. Was an issue with not generating the security group correctly with the ports matching http and https. (would not open to external access)

**Comment by ccojocar** [comment] 2019-02-19 10:39
@ypto Thanks for update. I am going to close this issue.

**Closed by ccojocar** 2019-02-19 10:39 UTC

**Comment by romil-punetha** [comment] 2019-02-27 03:35
@ypto How did you fix the security group issue? My security groups were generated by the eksctl command. What entries did you make on the security groups to make it work? My nginx-ingress is exposed on 30851

**Comment by ypto** [comment] 2019-02-27 20:18
@romil-punetha 

you need go to the nodes security group and map the ports manually.

by example for your port 30851, you need to have two lines in there:

Custom TCP Rule   TCP   30851   192.168.0.0/16 (if you have your nodes on this network)
Custom TCP Rule   TCP   30851   0.0.0.0/0

Then go to your target group and confirm that the health checks are being perform on this port and not on "traffic port"

Normally this get generated automatically if you change on the nginx ingress the ports to access but sometimes it fails to generate and you need to map it manually. You need to this for the HTTP port and for the HTTPS port in order for the nodes to become healthy.

**Comment by romil-punetha** [comment] 2019-02-28 03:12
@ypto All these entries are already there. The problem is that the ingress controller is unable to route the traffic according to the rules specified in the ingress resources. Do you have a solution for that?
